'use client';
import React, { useState } from 'react';
import ViewHeader from '@/components/shared/ViewHeader';
import VerseCard from '@/components/shared/VerseCard';
import SummaryCard from '@/components/shared/SummaryCard';
import { Input } from '@/components/ui/input';

interface SurahAalImranViewProps {
  goBack: () => void;
}

const verses = [
  { number: "3:1", arabic: "الم", lao: "ອາລີຟ ລາມ ມີມ.", english: "Alif, Lam, Meem." },
  { number: "3:2", arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ", lao: "ອັນລໍ, ບໍ່ມີພຣະເຈົ້າອື່ນໃດນອກຈາກພຣະອົງ, ຜູ້ຊົງມີຊີວິດ, ຜູ້ຊົງດຳລົງຢູ່ສະເໝີ.", english: "Allah - there is no deity except Him, the Ever-Living, the Self-Sustaining." },
  { number: "3:3", arabic: "نَزَّلَ عَلَيْكَ الْكِتَابَ بِالْحَقِّ مُصَدِّقًا لِّمَا بَيْنَ يَدَيْهِ وَأَنزَلَ التَّوْرَاةَ وَالْإِنجِيلَ", lao: "ພຣະອົງໄດ້ຊົງປະທານຄຳພີລົງມາໃຫ້ເຈົ້າດ້ວຍຄວາມຈິງ, ເພື່ອຢັ້ງຢືນສິ່ງທີ່ຢູ່ກ່ອນໜ້ານັ້ນ. ແລະ ພຣະອົງໄດ້ຊົງປະທານຄຳພີເຕົາຣອດ ແລະ ຄຳພີອິນຈີລລົງມາ.", english: "He has sent down upon you, [O Muhammad], the Book in truth, confirming what was before it. And He revealed the Torah and the Gospel." },
  { number: "3:4", arabic: "مِن قَبْلُ هُدًى لِّلنَّاسِ وَأَنزَلَ الْفُرْقَانَ ۗ إِنَّ الَّذِينَ كَفَرُوا بِآيَاتِ اللَّهِ لَهُمْ عَذَابٌ شَدِيدٌ ۗ وَاللَّهُ عَزِيزٌ ذُو انتِقَامٍ", lao: "ກ່ອນໜ້ານີ້ ເພື່ອເປັນທາງນຳແກ່ມະນຸດຊາດ, ແລະ ພຣະອົງໄດ້ຊົງປະທານອັລ-ຟຸຣກອນ (ສິ່ງທີ່ຈຳແນກ) ລົງມາ. ແທ້ຈິງ, ບັນດາຜູ້ທີ່ປະຕິເສດສັນຍານຂອງອັນລໍ, ພວກເຂົາຈະໄດ້ຮັບການລົງໂທດຢ່າງໜັກໜ່ວງ. ແລະ ອັນລໍເປັນຜູ້ຊົງອຳນາດ, ເຈົ້າແຫ່ງການຕອບແທນ.", english: "Before, as guidance for the people. And He revealed the Qur'an. Indeed, those who disbelieve in the verses of Allah will have a severe punishment, and Allah is exalted in Might, the Owner of Retribution." },
  { number: "3.5", arabic: "إِنَّ اللَّهَ لَا يَخْفَىٰ عَلَيْهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ", lao: "ແທ້ຈິງ, ບໍ່ມີສິ່ງໃດໃນແຜ່ນດິນ ແລະ ໃນຊັ້ນຟ້າທີ່ຈະซ่อนเร้นຈາກອັນລໍໄດ້.", english: "Indeed, from Allah nothing is hidden in the earth nor in the heaven." },
  { number: "3:6", arabic: "هُوَ الَّذِي يُصَوِّرُكُمْ فِي الْأَرْحَامِ كَيْفَ يَشَاءُ ۚ لَا إِلَٰهَ إِلَّا هُوَ الْعَzِيزُ الْحَكِيمُ", lao: "ພຣະອົງຄືຜູ້ທີ່ສ້າງຮູບຮ່າງຂອງພວກເຈົ້າໃນມົດລູກຕາມທີ່ພຣະອົງຊົງປະສົງ. ບໍ່ມີພຣະເຈົ້າອື່ນໃດນອກຈາກພຣະອົງ, ຜູ້ຊົງອຳນາດ, ຜູ້ຊົງມີປັນຍາ.", english: "It is He who forms you in the wombs however He wills. There is no deity except Him, the Exalted in Might, the Wise." },
  { number: "3:7", arabic: "هُوَ الَّذِي أَنزَلَ عَلَيْكَ الْكِتَابَ مِنْهُ آيَاتٌ مُّحْكَمَاتٌ هُنَّ أُمُّ الْكِتَابِ وَأُخَرُ مُتَشَابِهَاتٌ ۖ فَأَمَّا الَّذِينَ فِي قُلُوبِهِمْ زَيْغٌ فَيَتَّبِعُونَ مَا تَشَابَهَ مِنْهُ ابْتِغَاءَ الْفِتْنَةِ وَابْتِغَاءَ تَأْوِيلِهِ ۗ وَمَا يَعْلَمُ تَأْوِيلَهُ إِلَّا اللَّهُ ۗ وَالرَّاسِخُونَ فِي الْعِلْمِ يَقُولُونَ آمَنَّا بِهِ كُلٌّ مِّنْ عِندِ رَبِّنَا ۗ وَمَا يَذَّكَّرُ إِلَّا أُولُو الْأَلْبَابِ", lao: "ພຣະອົງຄືຜູ້ທີ່ໄດ້ຊົງປະທານຄຳພີລົງມາໃຫ້ເຈົ້າ. ໃນນັ້ນມີອາຍະຕ່າງໆທີ່ຊັດเจน, ເຊິ່ງເປັນແມ່ບົດຂອງຄຳພີ, ແລະ ມີອາຍະຕ່າງໆທີ່ບໍ່ຊັດเจน. ສ່ວນຜູ້ທີ່ໃນໃຈຂອງພວກເຂົາມີຄວາມບິດເບືອນ, ພວກເຂົາຈະຕິດຕາມສິ່ງທີ່ບໍ່ຊັດเจน, ເພື່ອສະແຫວງຫາຄວາມວຸ້ນວາຍ ແລະ ສະແຫວງຫາການຕີຄວາມໝາຍຂອງມັນ. ແລະ ບໍ່ມີຜູ້ໃດຮູ້ການຕີຄວາມໝາຍຂອງມັນນອກຈາກອັນລໍ. ແລະ ຜູ້ທີ່ໝັ້ນຄົງໃນຄວາມຮູ້ຈະກ່າວວ່າ: 'ພວກເຮົາເຊື່ອໃນມັນ, ທັງໝົດມາຈາກພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ.' ແລະ ບໍ່ມີຜູ້ໃດທີ່ຈະລະນຶກນອກຈາກຜູ້ທີ່ມີປັນຍາ.", english: "It is He who has sent down to you, [O Muhammad], the Book; in it are verses [that are] precise - they are the foundation of the Book - and others unspecific. As for those in whose hearts is deviation [from truth], they will follow that of it which is unspecific, seeking discord and seeking an interpretation [suitable to them]. And no one knows its [true] interpretation except Allah. But those firm in knowledge say, 'We believe in it. All [of it] is from our Lord.' And no one will be reminded except those of understanding." },
  { number: "3:8", arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ الْوَهَّابُ", lao: "ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ, ຂໍຢ່າເຮັດໃຫ້ໃຈຂອງພວກເຮົາບິດເບືອນຫຼັງຈາກທີ່ພຣະອົງໄດ້ຊົງນຳພາພວກເຮົາ, ແລະ ຂໍໃຫ້ປະທານຄວາມເມດຕາຈາກພຣະອົງໃຫ້ແກ່ພວກເຮົາ. ແທ້ຈິງ, ພຣະອົງຄືຜູ້ຊົງປະທານ.", english: "'Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.'" },
  { number: "3:9", arabic: "رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ ۚ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ", lao: "ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ, ແທ້ຈິງພຣະອົງຈະຊົງຮວບຮວມມະນຸດຊາດໃນວັນທີ່ບໍ່ມີຄວາມສົງໄສ. ແທ້ຈິງ, ອັນລໍບໍ່ຊົງຜິດສັນຍາ.", english: "'Our Lord, surely You will gather the people for a Day about which there is no doubt. Indeed, Allah does not fail in His promise.'" },
  { number: "3:10", arabic: "إِنَّ الَّذِينَ كَفَرُوا لَن تُغْنِيَ عَنْهُمْ أَمْوَالُهُمْ وَلَا أَوْلَادُهُم مِّنَ اللَّهِ شَيْئًا ۖ وَأُولَٰئِكَ هُمْ وَقُودُ النَّارِ", lao: "ແທ້ຈິງ, ບັນດາຜູ້ທີ່ປະຕິເສດ, ຊັບສິນຂອງພວກເຂົາ ແລະ ລູກຫຼານຂອງພວກເຂົາຈະບໍ່ສາມາດຊ່ວຍພວກເຂົາຈາກອັນລໍໄດ້ເລີຍ. ແລະ ພວກເຂົາຄືເຊື້ອໄຟຂອງນະລົກ.", english: "Indeed, those who disbelieve - never will their wealth or their children avail them against Allah at all. And it is they who are fuel for the Fire." },
  { number: "3:11", arabic: "كَدَأْبِ آلِ فِرْعَوْنَ وَالَّذِينَ مِن قَبْلِهِمْ ۚ كَذَّبُوا بِآيَاتِنَا فَأَخَذَهُمُ اللَّهُ بِذُنُوبِهِمْ ۗ وَاللَّهُ شَدِيدُ الْعِقَابِ", lao: "ເໝືອນດັ່ງສະພາບຂອງພรรคພວກຟີຣະໂອນ ແລະ ບັນດາຜູ້ທີ່ຢູ່ກ່ອນໜ້າພວກເຂົາ. ພວກເຂົາໄດ້ປະຕິເສດສັນຍານຂອງພວກເຮົາ, ດັ່ງນັ້ນອັນລໍຈຶ່ງໄດ້ລົງໂທດພວກເຂົາຍ້ອນບາບຂອງພວກເຂົາ. ແລະ ອັນລໍເປັນຜູ້ຊົງລົງໂທດຢ່າງໜັກໜ່ວງ.", english: "Like the behavior of the people of Pharaoh and those before them. They denied Our signs, so Allah seized them for their sins. And Allah is severe in penalty." },
  { number: "3:12", arabic: "قُل لِّلَّذِينَ كَفَرُوا سَتُغْلَبُونَ وَتُحْشَرُونَ إِلَىٰ جَهَنَّمَ ۚ وَبِئْسَ الْمِهَادُ", lao: "ຈົ່ງກ່າວແກ່ບັນດາຜູ້ທີ່ປະຕິເສດວ່າ: 'ພວກເຈົ້າຈະຖືກເອົາຊະນະ ແລະ ຈະຖືກຮວບຮວມໄປສູ່ນະລົກ, ແລະ ມັນເປັນທີ່พำนักທີ່ຊົ່ວຊ້າ.'", english: "Say to those who disbelieve, 'You will be overcome and gathered together to Hell, and wretched is the resting place.'" },
  { number: "3:13", arabic: "قَدْ كَانَ لَكُمْ آيَةٌ فِي فِئَتَيْنِ الْتَقَتَا ۖ فِئَةٌ تُقَاتِلُ فِي سَبِيلِ اللَّهِ وَأُخْرَىٰ كَافِرَةٌ يَرَوْنَهُم مِّثْلَيْهِمْ رَأْيَ الْعَيْنِ ۚ وَاللَّهُ يُؤَيِّدُ بِنَصْرِهِ مَن يَشَاءُ ۗ إِنَّ فِي ذَٰلِكَ لَعِبْرَةً لِّأُولِي الْأَبْصَارِ", lao: "ແນ່ນອນ, ມີສັນຍານໜຶ່ງສຳລັບພວກເຈົ້າໃນສອງກຸ່ມທີ່ໄດ້ພົບກັນ: ກຸ່ມໜຶ່ງຕໍ່ສູ້ໃນທາງຂອງອັນລໍ ແລະ ອີກກຸ່ມໜຶ່ງເປັນผู้ปฏิเสธ, ພວກເຂົາເຫັນອີກฝ่ายໜຶ່ງເປັນສອງເທົ່າດ້ວຍຕາຂອງຕົນ. ແລະ ອັນລໍຊົງສະໜັບສະໜູນผู้ที่พระองค์ทรงประสงค์ด้วยความช่วยเหลือของพระองค์. ແທ້ຈິງໃນນັ້ນມີບົດຮຽນສຳລັບຜູ້ທີ່ມີສາຍຕາ.", english: "Already there has been for you a sign in the two armies which met - one fighting in the cause of Allah and another of disbelievers. They saw them [to be] twice their [own] number by [their] eyesight. But Allah supports with His victory whom He wills. Indeed in that is a lesson for those of vision." },
  { number: "3:14", arabic: "زُيِّنَ لِلنَّاسِ حُبُّ الشَّهَوَاتِ مِنَ النِّسَاءِ وَالْبَنِينَ وَالْقَنَاطِيرِ الْمُقَنطَرَةِ مِنَ الذَّهَبِ وَالْفِضَّةِ وَالْخَيْلِ الْمُسَوَّمَةِ وَالْأَنْعَامِ وَالْحَرْثِ ۗ ذَٰلِكَ مَتَاعُ الْحَيَاةِ الدُّنْيَا ۖ وَاللَّهُ عِندَهُ حُسْنُ الْمَآبِ", lao: "ຄວາມຮັກໃນສິ່ງທີ່ປາຖະໜາໄດ້ຖືກປະດັບປະດາให้สวยงามແກ່ມະນຸດ - ຈາກผู้หญิง, ລູກຊາຍ, ຊັບສິນທີ່ສະສົມໄວ້ - ຄຳ, ເງິນ, ມ້າທີ່ຖືກเลี้ยงดูอย่างดี, ສັດລ້ຽງ, และที่ดิน. ນັ້ນຄືຄວາມສຸກຂອງຊີວິດນີ້, ແຕ່ກັບອັນລໍຄືທີ່กลับທີ່ດີທີ່ສຸດ.", english: "Beautified for people is the love of that which they desire - of women and sons, heaped-up sums of gold and silver, fine branded horses, and cattle and tilled land. That is the enjoyment of worldly life, but Allah has with Him the best return." },
  { number: "3:15", arabic: "قُلْ أَؤُنَبِّئُكُم بِخَيْرٍ مِّن ذَٰلِكُمْ ۚ لِلَّذِينَ اتَّقَوْا عِندَ رَبِّهِمْ جَنَّاتٌ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ خَالِدِينَ فِيهَا وَأَزْوَاجٌ مُّطَهَّرَةٌ وَرِضْوَانٌ مِّنَ اللَّهِ ۗ وَاللَّهُ بَصِيرٌ بِالْعِبَادِ", lao: "ຈົ່ງກ່າວວ່າ: 'ຂ້ອຍจะบอกพวกเจ้าถึงสิ่งที่ดีกว่าນັ້ນບໍ?' ສຳລັບຜູ້ທີ່ຢຳເກງ, ກັບພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຂົາຄືสวนสวรรค์ที่มีแม่น้ำไหลผ่าน, ພວກເຂົາຈະอยู่ในนั้นตลอดไป, ແລະมีคู่ครองที่บริสุทธิ์, และความพอใจจากอัลลอฮ์. ແລະອັນລໍทรงเห็นบ่าวของพระองค์.", english: "Say, 'Shall I inform you of [something] better than that? For those who fear Allah will be gardens in the presence of their Lord beneath which rivers flow, wherein they will abide forever, and purified spouses and approval from Allah. And Allah is Seeing of [His] servants -'" },
  { number: "3:16", arabic: "الَّذِينَ يَقُولُونَ رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ", lao: "ຜູ້ທີ່ກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ, ແທ້ຈິງພວກເຮົາເຊື່ອแล้ว, ດັ່ງນັ້ນຂໍให้อภัยบาปของเราและปกป้องเราจากการลงโทษของไฟนรก.'", english: "Those who say, 'Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire,' -" },
  { number: "3:17", arabic: "الصَّابِرِينَ وَالصَّادِقِينَ وَالْقَانِتِينَ وَالْمُنفِقِينَ وَالْمُسْتَغْfِرِينَ بِالْأَسْحَارِ", lao: "ຜູ້ທີ່อดทน, ຜູ້ที่สัตย์จริง, ຜູ້ที่เชื่อฟัง, ຜູ້ที่บริจาค, และผู้ที่ขออภัยในยามเช้าตรู่.", english: "The patient, the true, the obedient, the spending [in the way of Allah], and those who seek forgiveness before dawn." },
  { number: "3:18", arabic: "شَهِدَ اللَّهُ أَنَّهُ لَا إِلَٰهَ إِلَّا هُوَ وَالْمَلَائِكَةُ وَأُولُو الْعِلْمِ قَائِمًا بِالْقِسْطِ ۚ لَا إِلَٰهَ إِلَّا هُوَ الْعَzِيزُ الْحَكِيمُ", lao: "ອັນລໍทรงเป็นพยานว่าไม่มีพระเจ้าอื่นใดนอกจากพระองค์, และทูตสวรรค์และผู้ที่มีความรู้ก็เป็นพยาน. [พระองค์ทรง] รักษาความยุติธรรม. ບໍ່ມີພຣະເຈົ້າອື່ນໃດນອກຈາກພຣະອົງ, ຜູ້ຊົງອຳນາດ, ຜູ້ຊົງມີປັນຍາ.", english: "Allah witnesses that there is no deity except Him, and [so do] the angels and those of knowledge - [that He is] maintaining [creation] in justice. There is no deity except Him, the Exalted in Might, the Wise." },
  { number: "3:19", arabic: "إِنَّ الدِّينَ عِندَ اللَّهِ الْإِسْلَامُ ۗ وَمَا اخْتَلَفَ الَّذِينَ أُوتُوا الْكِتَابَ إِلَّا مِن بَعْدِ مَا جَاءَهُمُ الْعِلْمُ بَغْيًا بَيْنَهُمْ ۗ وَمَن يَكْfُرْ بِآيَاتِ اللَّهِ فَإِنَّ اللَّهَ سَرِيعُ الْحِسَابِ", lao: "ແທ້ຈິງ, ສາສະໜາที่ອັນລໍทรงยอมรับຄືອິສລາມ. ແລະຜູ້ที่ได้รับคัมภีร์ບໍ່ได้ขัดแย้งกันนอกจากหลังจากที่ความรู้ได้มาถึงพวกเขาแล้ว, ດ້ວຍความอิจฉาระหว่างกัน. ແລະຜູ້ໃດທີ່ປະຕິເສດສັນຍານຂອງອັນລໍ, ແທ້ຈິງອັນລໍทรงรวดเร็วในการคิดบัญชี.", english: "Indeed, the religion in the sight of Allah is Islam. And those who were given the Scripture did not differ except after knowledge had come to them - out of jealous animosity between themselves. And whoever disbelieves in the verses of Allah, then indeed, Allah is swift in account." },
  { number: "3:20", arabic: "فَإِنْ حَاجُّوكَ فَقُلْ أَsْلَمْتُ وَجْهِيَ لِلَّهِ وَمَنِ اتَّبَعَنِ ۗ وَقُل لِّلَّذِينَ أُوتُوا الْكِتَابَ وَالْأُمِّيِّينَ أَأَسْلَمْتُمْ ۚ فَإِنْ أَsْلَمُوا فَقَدِ اهْتَدَوا ۖ وَّإِن تَوَلَّوْا فَإِنَّمَا عَلَيْكَ الْبَلَاغُ ۗ وَاللَّهُ بَصِيرٌ بِالْعِبَادِ", lao: "ແລະຖ້າພວກເຂົາຖຽງກັບເຈົ້າ, ຈົ່ງກ່າວວ່າ: 'ຂ້ອຍໄດ້ຍອມຈຳນົນຕໍ່ອັນລໍ, ແລະຜູ້ທີ່ຕິດຕາມຂ້ອຍກໍເຊັ່ນກັນ.' ແລະຈົ່ງກ່າວແກ່ຜູ້ที่ได้รับคัมภีร์และผู้ที่ไม่รู้หนังสือว่า: 'ພວກເຈົ້າໄດ້ຍອມຈຳນົນແລ້ວບໍ?' ແລະຖ້າພວກເຂົາຍອມຈຳນົນ, ພວກເຂົາກໍໄດ້ຮັບການຊີ້ແນະ. ແຕ່ຖ້າພວກເຂົາຫັນໜີ, ໜ້າທີ່ຂອງເຈົ້າຄືການປະກາດ. ແລະອັນລໍทรงเห็นบ่าวของพระองค์.", english: "So if they argue with you, say, 'I have submitted myself to Allah [in Islam], and [so have] those who follow me.' And say to those who were given the Scripture and [to] the unlearned, 'Have you submitted yourselves?' And if they submit, then they are rightly guided; but if they turn away - then upon you is only the [duty of] notification. And Allah is Seeing of [His] servants." },
  { number: "3:21", arabic: "إِنَّ الَّذِينَ يَكْفُرُونَ بِآيَاتِ اللَّهِ وَيَقْتُلُونَ النَّبِيِّينَ بِغَيْرِ حَقٍّ وَيَقْتُلُونَ الَّذِينَ يَأْمُرُونَ بِالْقِسْطِ مِنَ النَّاسِ فَبَشِّرْهُم بِعَذَابٍ أَلِيمٍ", lao: "ແທ້ຈິງ, ບັນດາຜູ້ທີ່ປະຕິເສດສັນຍານຂອງອັນລໍ ແລະ ຂ້າສາດສະດາໂດຍບໍ່ມີສິດ, ແລະ ຂ້າຜູ້ທີ່ສັ່ງສອນຄວາມຍຸດຕິທຳໃນหมู่ມະນຸດ, ຈົ່ງແຈ້ງຂ່າວການລົງໂທດທີ່ເຈັບປວດແກ່ພວກເຂົາ.", english: "Indeed, those who disbelieve in the signs of Allah and kill the prophets without right and kill those who order justice from among the people - give them tidings of a painful punishment." },
  { number: "3:22", arabic: "أُولَٰئِكَ الَّذِينَ حَبِطَتْ أَعْمَالُهُمْ فِي الدُّنْيَا وَالْآخِرَةِ وَمَا لَهُم مِّن نَّاصِرِينَ", lao: "ພວກເຂົາຄືຜູ້ທີ່ການກະທຳຂອງພວກເຂົາสูญเปล่าในโลกนี้และโลกหน้า, และพวกเขาไม่มีผู้ช่วยเหลือ.", english: "Those are the ones whose deeds have become worthless in this world and the Hereafter, and for them there will be no helpers." },
  { number: "3:23", arabic: "أَلَمْ تَرَ إِلَى الَّذِينَ أُوتُوا نَصِيبًا مِّنَ الْكِتَابِ يُدْعَوْنَ إِلَىٰ كِتَابِ اللَّهِ لِيَحْكُمَ بَيْنَهُمْ ثُمَّ يَتَوَلَّىٰ فَرِيقٌ مِّنْهُمْ وَهُم مُّعْرِضُونَ", lao: "ເຈົ້າບໍ່ເຫັນບໍผู้ที่ได้รับส่วนหนึ่งของคัมภีร์? ພວກເຂົາຖືກເອີ້ນໃຫ້ມາສູ່ຄຳພີຂອງອັນລໍເພື່ອຕັດສິນລະຫວ່າງພວກເຂົາ, ແລ້ວກຸ່ມໜຶ່ງໃນພວກເຂົາກໍหันหลังกลับໃນຂະນະที่พวกเขากำลังຜິນຫຼັງ.", english: "Have you not considered those who were given a portion of the Scripture? They are invited to the Book of Allah that it should judge between them; then a party of them turns away while they are refusing." },
  { number: "3:24", arabic: "ذَٰلِكَ بِأَنَّهُمْ قَالُوا لَن تَمَسَّنَا النَّارُ إِلَّا أَيَّامًا مَّعْدُودَاتٍ ۖ وَغَرَّهُمْ فِي دِينِهِم مَّا كَانُوا يَfْتَرُونَ", lao: "ນັ້ນเป็นเพราะพวกเขากล่าวว่า: 'ไฟนรกจะไม่แตะต้องเรายกเว้นສອງສາມວັນ.' ແລະສິ່ງที่ພວກເຂົາเคยสร้างຂຶ້ນໄດ້ຫຼອກລວງພວກເຂົາในศาสนาของพวกเขา.", english: "That is because they say, 'Never will the Fire touch us except for a number of days.' And they were deluded in their religion by what they used to invent." },
  { number: "3:25", arabic: "فَكَيْfَ إِذَا جَمَعْنَاهُمْ لِيَوْmٍ لَّا رَيْbَ فِيهِ وَوُfِّيَتْ كُلُّ نَفْسٍ مَّا كَسَبَتْ وَهُمْ لَا يُظْلَمُونَ", lao: "ແລ້ວจะเป็นอย่างไรເມື່ອเราຮวບຮວມพวกเขาในວັນที่ไม่มีความสงสัย? ແລະທຸກຄົນຈະได้รับการตอบแทนอย่างเต็มที่สำหรับสิ่งที่ได้ทำ, ແລະພວກເຂົາจะไม่ถูกทำร้าย.", english: "So how will it be when We assemble them for a Day about which there is no doubt? And each soul will be compensated [in full for] what it has earned, and they will not be wronged." },
  { number: "3.26", arabic: "قُلِ اللَّهُمَّ مَالِكَ الْمُلْكِ تُؤْتِي الْمُلْكَ مَن تَشَاءُ وَتَنzِعُ الْمُلْكَ مِمَّn تَشَاءُ وَتُعِzُّ مَن تَشَاءُ وَتُذِلُّ مَن تَشَاءُ ۖ بِيَدِكَ الْخَيْرُ ۖ إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", lao: "ຈົ່ງກ່າວວ່າ: 'ໂອ້ ອັນລໍ, ເຈົ້າແຫ່ງອຳນາດ, ພຣະອົງทรงให้อำนาจแก่ผู้ที่พระองค์ทรงประสงค์และถอดถอนอำนาจจากผู้ที่พระองค์ทรงประสงค์, และພຣະອົງทรงให้เกียรติผู้ที่พระองค์ทรงประสงค์และทรงทำให้อัปยศผู้ที่พระองค์ทรงประสงค์. ໃນພຣະຫັດຂອງພຣະອົງຄືຄວາມດີ. ແທ້ຈິງ, ພຣະອົງทรงมีอำนาจเหนือทุกสิ่ง.'", english: "Say, 'O Allah, Owner of Sovereignty, You give sovereignty to whom You will and You take sovereignty away from whom You will. You honor whom You will and You humiliate whom You will. In Your hand is [all] good. Indeed, You are over all things competent.'" },
  { number: "3.27", arabic: "تُولِjُ اللَّيْلَ فِي النَّهَarِ وَتُولِjُ النَّهَarَ فِي اللَّيْلِ ۖ وَتُخْرِjُ الْحَيَّ مِنَ الْمَيِّتِ وَتُخْرِjُ الْمَيِّتَ مِنَ الْحَيِّ ۖ وَتَرْzُقُ مَن تَشَاءُ بِغَيْرِ حِسَابٍ", lao: "ພຣະອົງทรงทำให้ກາງຄືນເຂົ້າไปໃນกลางวันແລະทรงทำให้กลางวันເຂົ້າไปໃນกลางคืน. ແລະພຣະອົງทรงนำສິ່ງທີ່ມີຊີວິດອອກຈາກສິ່ງທີ່ຕາຍແລະทรงนำສິ່ງທີ່ຕາຍອອກຈາກສິ່ງທີ່ມີຊີວິດ. ແລະພຣະອົງทรงให้ปัจจัยแก่ผู้ที่พระองค์ทรงประสงค์โดยไม่มีการคำนวณ.", english: "You cause the night to enter the day, and You cause the day to enter the night; and You bring the living out of the dead, and You bring the dead out of the living. And You give provision to whom You will without account." },
  { number: "3.28", arabic: "لَّا يَتَّخِذِ الْمُؤْمِنُونَ الْكَافِرِينَ أَوْلِيَاءَ مِن دُونِ الْمُؤْمِنِينَ ۖ وَمَن يَfْعَلْ ذَٰلِكَ فَلَيْsَ مِنَ اللَّهِ فِي شَيْءٍ إِلَّا أَن تَتَّقُوا مِنْهُمْ تُقَاةً ۗ وَيُحَذِّرُكُمُ اللَّهُ نَفْسَهُ ۗ وَإِلَى اللَّهِ الْمَصِيرُ", lao: "ຢ່າให้ผู้ศรัทธาเอาผู้ปฏิเสธมาเป็นพันธมิตรแทนผู้ศรัทธา. ແລະຜູ້ໃດທີ່ทำเช่นนั้นກໍບໍ່ມີอะไรจากอัลลอฮ์, ยกเว้นกรณีที่พวกเจ้าต้องระวังพวกเขา. ແລະອັນລໍทรงเตือนพวกเจ้าให้ระวังพระองค์. ແລະການກັບไปอยู่กับອັນລໍ.", english: "Let not believers take disbelievers as allies rather than believers. And whoever [of you] does that has nothing with Allah, except when taking precaution against them in prudence. And Allah warns you of Himself, and to Allah is the [final] destination." },
  { number: "3.29", arabic: "قُلْ إِن تُخْfُوا مَا فِي صُدُورِكُمْ أَوْ تُbْدُوهُ يَعْلَمْهُ اللَّهُ ۗ وَيَعْلَمُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ وَاللَّهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", lao: "ຈົ່ງກ່າວວ່າ: 'ຖ້າพวกเจ้าปกปิดสิ่งที่อยู่ในใจหรือเปิดเผยมัน, อัลลอฮ์ทรงรู้. ແລະພຣະອົງทรงรู้สิ่งที่อยู่ในชั้นฟ้าและสิ่งที่อยู่ในแผ่นดิน. ແລະອັນລໍทรงมีอำนาจเหนือทุกสิ่ง.'", english: "Say, 'Whether you conceal what is in your breasts or reveal it, Allah knows it. And He knows that which is in the heavens and that which is on the earth. And Allah is over all things competent.'" },
  { number: "3.30", arabic: "يَوْمَ تَjِدُ كُلُّ نَفْسٍ مَّا عَمِلَتْ مِنْ خَيْرٍ مُّحْضَرًا وَمَا عَمِلَتْ مِن sūءٍ تَوَدُّ لَوْ أَنَّ بَيْنَهَا وَبَيْنَهُ أَمَدًا بَعِيدًا ۗ وَيُحَذِّrُكُمُ اللَّهُ نَفْسَهُ ۗ وَاللَّهُ رَءُوفٌ بِالْعِبَادِ", lao: "ວັນທີ່ທຸກຄົນຈະພົບການກະທຳດີທີ່ໄດ້ทำไว้ปรากฏอยู่, และการกระทำชั่วที่ได้ทำไว้, ລາວจะปรารถนาให้มีระยะทางห่างไกลระหว่างລາวกับมัน. ແລະອັນລໍทรงเตือนพวกเจ้าให้ระวังพระองค์. ແລະອັນລໍทรงเมตตาต่อบ่าว.", english: "On the Day when every soul will be confronted with all the good it has done and all the evil it has done, it will wish that there were a great distance between it and its evil. And Allah warns you of Himself, and Allah is Kind to [His] servants." },
  { number: "3:31", arabic: "قُلْ إِن كُنتُمْ تُحِبُّونَ اللَّهَ فَاتَّbِعُونِي يُحْبِبْكُمُ اللَّهُ وَيَغْfِرْ لَكُمْ ذُنُوبَكُمْ ۗ وَاللَّهُ غَفُورٌ رَّحِيمٌ", lao: "ຈົ່ງກ່າວວ່າ: 'ຖ້າพวกเจ้ารักอัลลอฮ์, ກໍຈົ່ງตามข้า, อัลลอฮ์จะทรงรักพวกเจ้าและอภัยบาปให้พวกเจ้า.' ແລະອັນລໍทรงอภัย, ทรงเมตตา.", english: "Say, [O Muhammad], 'If you should love Allah, then follow me, [so] Allah will love you and forgive you your sins. And Allah is Forgiving and Merciful.'" },
  { number: "3.32", arabic: "قُلْ أَطِيعُوا اللَّهَ وَالرَّsُولَ ۖ فَإِن تَوَلَّوْا فَإِنَّ اللَّهَ لَا يُحِبُّ الْكَافِرِينَ", lao: "ຈົ່ງກ່າວວ່າ: 'ຈົ່ງເຊື່ອຟັງອັນລໍແລະศาสดา.' ແຕ່ຖ້າພວກເຂົາຫັນໜີ, ແທ້ຈິງອັນລໍບໍ່ทรงรักผู้ปฏิเสธ.", english: "Say, 'Obey Allah and the Messenger.' But if they turn away - then indeed, Allah does not love the disbelievers." },
  { number: "3:33", arabic: "إِنَّ اللَّهَ اصْطَفَىٰ آدَمَ وَنُوحًا وَآلَ إِبْرَاهِيمَ وَآلَ عِمْرَانَ عَلَى الْعَالَمِينَ", lao: "ແທ້ຈິງ, ອັນລໍໄດ້ຊົງເລືອກອາດັມ, ນູຫ໌, ຄອບຄົວຂອງອີບຣາຮີມ, ແລະ ຄອບຄົວຂອງອີມຣອນເໜືອໂລກ.", english: "Indeed, Allah chose Adam and Noah and the family of Abraham and the family of 'Imran over the worlds -" },
  { number: "3.34", arabic: "ذُرِّيَّةً بَعْضُهَا مِن بَعْضٍ ۗ وَاللَّهُ سَمِيعٌ عَلِيمٌ", lao: "ລູກຫຼານ, ບາງຄົນມາຈາກຄົນອື່ນ. ແລະອັນລໍทรงได้ยิน, ทรงรอบรู้.", english: "Descendants, some of them from others. And Allah is Hearing and Knowing." },
  { number: "3:35", arabic: "إِذْ قَالَتِ امْرَأَتُ عِمْرَانَ رَبِّ إِنِّي نَذَرْتُ لَكَ مَا فِي بَطْنِي مُحَرَّrًا فَتَقَبَّلْ مِنِّي ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ", lao: "ເມື່ອภรรยาຂອງອີມຣອນກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງข้า, ແທ້ຈິງข้าໄດ້ສັນຍາว่าจะอุทิศสิ่งที่อยู่ในท้องของข้าให้แก่ພຣະອົງ, ດັ່ງນັ້ນขอให้ทรงรับจากข้า. ແທ້ຈິງ, ພຣະອົງทรงได้ยิน, ทรงรอบรู้.'", english: "[Mention] when the wife of 'Imran said, 'My Lord, indeed I have pledged to You what is in my womb, consecrated [for Your service], so accept this from me. Indeed, You are the Hearing, the Knowing.'" },
  { number: "3:36", arabic: "فَلَمَّا وَضَعَتْهَا قَالَتْ رَبِّ إِنِّي وَضَعْتُهَا أُنثَىٰ وَاللَّهُ أَعْلَمُ بِمَا وَضَعَتْ وَلَيْsَ الذَّكَرُ كَالْأُنثَىٰ ۖ وَإِنِّي سَمَّيْتُهَا مَرْيَمَ وَإِنِّي أُعِيذُهَا بِكَ وَذُرِّيَّتَهَا مِنَ الشَّيْطَانِ الرَّjِيمِ", lao: "ແລະເມື່อนางคลอดบุตร, นางกล่าวว่า: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າของข้า, ແທ້ຈິງข้าคลอดเป็นผู้หญิง.' ແລະອັນລໍทรงรู้ดีกว่าว่านางคลอดอะไร. และชายไม่เหมือนหญิง. 'ແລະແທ້ຈິງข้าได้ตั้งชื่อนางว่ามัรยัม, ແລະข้าขอความคุ้มครองจากພຣະອົງให้นางและลูกหลานของนางพ้นจากชัยฏอนที่ถูกสาปแช่ง.'", english: "But when she delivered her, she said, 'My Lord, I have delivered a female.' And Allah was most knowing of what she delivered, 'And the male is not like the female. And I have named her Mary, and I seek refuge for her in You and [for] her descendants from Satan, the expelled [from the mercy of Allah].'" },
  { number: "3:37", arabic: "فَتَقَبَّلَهَا رَبُّهَا بِقَبُولٍ حَسَنٍ وَأَنbَتَهَا نَبَاتًا حَسَنًا وَكَfَّلَهَا zَكَرِيَّا ۖ كُلَّمَا دَخَلَ عَلَيْهَا zَكَرِيَّا الْمِحْرَابَ وَjَدَ عِندَهَا رِzْقًا ۖ قَالَ يَا مَرْيَمُ أَنَّىٰ لَكِ هَٰذَا ۖ قَالَتْ هُوَ مِنْ عِندِ اللَّهِ ۖ إِنَّ اللَّهَ يَرْzُقُ مَن يَشَاءُ بِغَيْرِ حِسَابٍ", lao: "ດັ່ງນັ້ນ, ພຣະຜູ້ເປັນເຈົ້າຂອງນາງຈຶ່ງໄດ້ຮັບນາງด้วยการยอมรับที่ดีและเลี้ยงดูนางอย่างดี, ແລະໄດ້มอบให้นางอยู่ในความดูแลของซะกะรียา. ທຸກຄັ້ງທີ່ซะกะรียาเข้านางในห้องอธิษฐาน, ລາວພົບอาหารอยู่กับนาง. ລາວກ່າວວ່າ: 'ໂອ້ มัรยัม, ສິ່ງນີ້ມາจากไหน?' นางกล่าวว่า: 'ມັນມາຈາກອັນລໍ. ແທ້ຈິງອັນລໍทรงให้ปัจจัยแก่ผู้ที่พระองค์ทรงประสงค์โดยไม่มีการคำนวณ.'", english: "So her Lord accepted her with good acceptance and caused her to grow in a good manner and put her in the care of Zechariah. Every time Zechariah entered upon her in the prayer chamber, he found with her provision. He said, 'O Mary, from where is this [coming] to you?' She said, 'It is from Allah. Indeed, Allah provides for whom He wills without account.'" },
  { number: "3:38", arabic: "هُنَالِكَ دَعَا zَكَرِيَّا رَبَّهُ ۖ قَالَ رَبِّ هَبْ لِي مِن لَّdُنكَ ذُرِّيَّةً طَيِّbَةً ۖ إِنَّكَ سَمِيعُ الدُّعَاءِ", lao: "ທີ່ນັ້ນ, ซะกะรียาได้วิงวอนต่อพระเจ้าของเขา. ລາວກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງຂ้า, ຂໍให้ประทานลูกหลานที่ดีแก่ข้าจากພຣະອົງ. ແທ້ຈິງ, ພຣະອົງทรงได้ยินคำวิงวอน.'", english: "At that, Zechariah called upon his Lord, saying, 'My Lord, grant me from Yourself a good offspring. Indeed, You are the Hearer of supplication.'" },
  { number: "3:39", arabic: "فَنَاdَتْهُ الْمَلَائِكَةُ وَهُوَ قَائِمٌ يُصَلِّي فِي الْمِحْرَابِ أَنَّ اللَّهَ يُbَشِّrُكَ بِيَحْيَىٰ مُصَدِّqًا بِكَلِمَةٍ مِّنَ اللَّهِ وَsَيِّdًا وَحَصُورًا وَنَبِيًّا مِّنَ الصَّالِحِينَ", lao: "แล้วทูตสวรรค์ได้เรียกเขาในขณะที่เขากำลังยืนอธิษฐานในห้องอธิษฐานว่า: 'ແທ້ຈິງອັນລໍทรงแจ้งข่าวดีแก่ท่านเกี่ยวกับยะห์ยา, ผู้ที่จะมายืนยันคำจากอัลลอฮ์, เป็นผู้นำ, ผู้ทรงพรต, และเป็นศาสดาจากผู้ที่ชอบธรรม.'", english: "So the angels called him while he was standing in prayer in the chamber, 'Indeed, Allah gives you good tidings of John, confirming a word from Allah and [who will be] honorable, abstaining [from women], and a prophet from among the righteous.'" },
  { number: "3:40", arabic: "قَالَ رَبِّ أَنَّىٰ يَكُونُ لِي غُلَامٌ وَقَدْ بَلَغَنِيَ الْكِبَرُ وَامْرَأَتِي عَاقِرٌ ۖ قَالَ كَذَٰلِكَ اللَّهُ يَfْعَلُ مَا يَشَاءُ", lao: "ລາວກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງข้า, ຂ้าจะมีลูกชายได้อย่างไรในเมื่อความแก่ได้มาถึงข้าแล้วและภรรยาของข้าก็เป็นหมัน?' [ทูตสวรรค์] ກ່າວວ່າ: 'เช่นนั้นแหละ, อัลลอฮ์ทรงทำในสิ่งที่พระองค์ทรงประสงค์.'", english: "He said, 'My Lord, how will I have a boy when I have reached old age and my wife is barren?' The angel said, 'Such is Allah ; He does what He wills.'" },
  { number: "3:41", arabic: "قَالَ رَبِّ اجْعَل لِّي آيَةً ۖ قَالَ آيَتُكَ أَلَّا تُكَلِّمَ النَّاسَ ثَلَاثَةَ أَيَّامٍ إِلَّا رَمْzًا ۗ وَاذْكُر رَّbَّكَ كَثِيرًا وَsَبِّحْ بِالْعَشِيِّ وَالْإِبْكَarِ", lao: "ລາວກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງຂ้า, ຂໍให้ทรงกำหนดສັນຍານให้แก่ข้า.' [ทูตสวรรค์] ກ່າວວ່າ: 'ສັນຍານของท่านคือท่านจะไม่สามารถพูดกับผู้คนได้เป็นเวลาສາມວັນยกเว้นการใช้ท่าทาง. ແລະຈົ່ງລະນຶກເຖິງພຣະຜູ້ເປັນເຈົ້າຂອງท่านให้มากๆ และสรรเสริญพระองค์ในยามเย็นและยามเช้า.'", english: "He said, 'My Lord, make for me a sign.' He said, 'Your sign is that you will not speak to the people for three days except by gesture. And remember your Lord much and exalt [Him with praise] in the evening and the morning.'" },
  { number: "3:42", arabic: "وَإِذْ قَالَتِ الْمَلَائِكَةُ يَا مَرْيَمُ إِنَّ اللَّهَ اصْطَفَاكِ وَطَهَّrَكِ وَاصْطَفَاكِ عَلَىٰ نِسَاءِ الْعَالَمِينَ", lao: "ແລະເມື່ອทูตสวรรค์กล่าวว่า: 'ໂອ້ มัรยัม, ແທ້ຈິງອັນລໍໄດ້ทรงเลือกเจ้าແລະชำระล้างเจ้าແລະเลือกเจ้าເໜືອผู้หญิงທັງหลายในโลก.'", english: "And [mention] when the angels said, 'O Mary, indeed Allah has chosen you and purified you and chosen you above the women of the worlds.'" },
  { number: "3:43", arabic: "يَا مَرْيَمُ اقْنُتِي لِرَبِّكِ وَاسْjُdِي وَarْكَعِي مَعَ الرَّاكِعِينَ", lao: "'ໂອ້ มัรยัม, ຈົ່ງเชื่อฟังພຣະຜູ້ເປັນເຈົ້າຂອງเจ้าและกราบไหว้และโค้งคำนับพร้อมกับผู้ที่โค้งคำนับ.'", english: "'O Mary, be devoutly obedient to your Lord and prostrate and bow with those who bow [in prayer].'" },
  { number: "3:44", arabic: "ذَٰلِكَ مِنْ أَنbَاءِ الْغَيْbِ نُوحِيهِ إِلَيْكَ ۚ وَمَا كُنتَ لَدَيْهِمْ إِذْ يُلْقُونَ أَقْلَامَهُمْ أَيُّهُمْ يَكْfُلُ مَرْيَمَ وَمَا كُنتَ لَدَيْهِمْ إِذْ يَخْتَصِمُونَ", lao: "ນັ້ນຄືສ່ວນໜຶ່ງຂອງຂ່າວสารທີ່ซ่อนเร้นທີ່เราเปิดเผยแก่เจ้า. และเจ้าไม่ได้อยู่กับพวกเขาเมื่อพวกเขาโยนปากกาของพวกเขา [เพื่อเสี่ยงทาย] ว่าใครจะดูแลมัรยัม, และเจ้าไม่ได้อยู่กับพวกเขาเมื่อพวกเขาโต้เถียงกัน.", english: "That is from the news of the unseen which We reveal to you, [O Muhammad]. And you were not with them when they cast their pens as to which of them should be responsible for Mary. Nor were you with them when they disputed." },
  { number: "3:45", arabic: "إِذْ قَالَتِ الْمَلَائِكَةُ يَا مَرْيَمُ إِنَّ اللَّهَ يُbَشِّrُكِ بِكَلِمَةٍ مِّنْهُ اسْمُهُ الْمَسِيحُ عِيسَى ابْنُ مَرْيَمَ وَjِيهًا فِي الدُّنْيَا وَالْآخِرَةِ وَمِنَ الْمُقَرَّbِينَ", lao: "ເມື່ອทูตสวรรค์กล่าวว่า: 'ໂອ້ มัรยัม, ແທ້ຈິງອັນລໍทรงแจ้งข่าวดีแก่เจ้าด้วยคำจากพระองค์, ຊື່ຂອງລາວຄືพระเมสสิยาห์อีซา, ລູກຊາຍຂອງมัรยัม, ເປັນຜູ້ທີ່ມີเกียรติในโลกนี้และโลกหน้า, และเป็นหนึ่งในผู้ที่ใกล้ชิด [กับอัลลอฮ์].'", english: "[And mention] when the angels said, 'O Mary, indeed Allah gives you good tidings of a word from Him, whose name will be the Messiah, Jesus, the son of Mary - distinguished in this world and the Hereafter and among those brought near [to Allah].'" },
  { number: "3:46", arabic: "وَيُكَلِّمُ النَّاسَ فِي الْمَهْدِ وَكَهْلًا وَمِنَ الصَّالِحِينَ", lao: "'ລາວจะพูดกับผู้คนໃນเปลและในวัยผู้ใหญ่, ແລະລາວຈະເປັນໜຶ່ງໃນผู้ที่ชอบธรรม.'", english: "'He will speak to the people in the cradle and in maturity and will be of the righteous.'" },
  { number: "3:47", arabic: "قَالَتْ رَبِّ أَنَّىٰ يَكُونُ لِي وَلَدٌ وَلَمْ يَمْسَسْنِي بَشَرٌ ۖ قَالَ كَذَٰلِكِ اللَّهُ يَخْلُقُ مَا يَشَاءُ ۚ إِذَا قَضَىٰ أَمْرًا فَإِنَّمَا يَقُولُ لَهُ كُن فَيَكُونُ", lao: "นางกล่าวว่า: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງຂ้า, ຂ้าจะมีลูกได้อย่างไรในเมื่อไม่มีชายใดแตะต้องข้า?' [ทูตสวรรค์] ກ່າວວ່າ: 'เช่นนั้นแหละ, อัลลอฮ์ทรงสร้างสิ่งที่พระองค์ทรงประสงค์. ເມື່ອพระองค์ทรงกำหนดสิ่งใด, พระองค์เพียงกล่าวแก่มันว่า: 'จงเป็น' และมันก็เป็น.'", english: "She said, 'My Lord, how will I have a child when no man has touched me?' [The angel] said, 'Such is Allah ; He creates what He wills. When He decrees a matter, He only says to it, 'Be,' and it is.'" },
  { number: "3:48", arabic: "وَيُعَلِّمُهُ الْكِتَابَ وَالْحِكْمَةَ وَالتَّوْrَاةَ وَالْإِnjِيلَ", lao: "'ແລະພຣະອົງจะสอนລາวคัมภีร์และปัญญา, และเตารอตและอินญีล.'", english: "'And He will teach him writing and wisdom and the Torah and the Gospel'" },
  { number: "3:49", arabic: "وَرَسُولًا إِلَىٰ بَنِي إِسْرَائِيلَ أَنِّي قَدْ jِئْتُكُم بِآيَةٍ مِّن rَّbِّكُمْ ۖ أَنِّي أَخْلُقُ لَكُم مِّنَ الطِّينِ كَهَيْئَةِ الطَّيْرِ فَأَنfُخُ فِيهِ فَيَكُونُ طَيْرًا بِإِذْنِ اللَّهِ ۖ وَأُbْرِئُ الْأَكْمَهَ وَالْأَبْرَصَ وَأُحْيِي الْمَوْتَىٰ بِإِذْنِ اللَّهِ ۖ وَأُنَبِّئُكُم بِمَا تَأْكُلُونَ وَمَا تَدَّخِرُونَ فِي بُيُوتِكُمْ ۚ إِنَّ فِي ذَٰلِكَ لَآيَةً لَّكُمْ إِن كُنتُم mُّؤْمِنِينَ", lao: "'ແລະ [ເຮັດให้ລາวเป็น] ศาสดาแก่ลูกหลานของอิสราเอล, [โดยกล่าวว่า]: 'แท้จริงข้าได้นำສັນຍານจากพระเจ้าของพวกเจ้ามาให้พวกเจ้า. ข้าจะสร้างให้พวกเจ้าจากดินເໝືອນຮູບນົກ, ແລ້ວຂ้าจะเป่าลมเข้าไปในมัน, ແລ້ວมันก็จะกลายเป็นนกด้วยการอนุมัติของอัลลอฮ์. ແລະข้าจะรักษาຄົນຕາບອດแต่กำเนิดและຄົນโรคเรื้อน, ແລະข้าจะทำให้ຄົນຕາຍมีຊີວິດຄືນมาด้วยการอนุมัติของอัลลอฮ์. ແລະข้าจะบอกพวกเจ้าถึงสิ่งที่พวกเจ้ากินและสิ่งที่พวกเจ้าเก็บไว้ในบ้าน. ແທ້ຈິງในນັ້ນมีສັນຍານสำหรับพวกเจ้า, ຫາກพวกเจ้าເປັນผู้ศรัทธา.'", english: "'And [make him] a messenger to the Children of Israel, [who will say], 'Indeed I have come to you with a sign from your Lord in that I design for you from clay [that which is] like the form of a bird, then I breathe into it and it becomes a bird by permission of Allah. And I cure the blind and the leper, and I give life to the dead - by permission of Allah. And I inform you of what you eat and what you store in your houses. Indeed in that is a sign for you, if you are believers.'" },
  { number: "3:50", arabic: "وَمُصَدِّqًا لِّمَا بَيْنَ يَدَيَّ مِنَ التَّوْrَاةِ وَلِأُحِلَّ لَكُم بَعْضَ الَّذِي حُرِّمَ عَلَيْكُمْ ۚ وَjِئْتُكُم بِآيَةٍ مِّن rَّbِّكُمْ فَاتَّقُوا اللَّهَ وَأَطِيعُونِ", lao: "'ແລະ [ຂ้ามา] ເພື່ອຢືນຢັນสิ่งที่อยู่ກ່ອນหน้าข้าคือเตารอต, และເພື່ອอนุญาตให้พวกเจ้าບາງสิ่งที่เคยถูกห้าม. ແລະຂ้าได้นำສັນຍານจากพระเจ้าของพวกเจ้ามาให้พวกเจ้า, ດັ່ງນັ້ນจົ່ງຢำເກງอัลลอฮ์และเชื่อฟังข้า.'", english: "'And [I have come] confirming what was before me of the Torah and to make lawful for you some of what was forbidden to you. And I have come to you with a sign from your Lord, so fear Allah and obey me.'" }
];

export default function SurahAalImranView({ goBack }: SurahAalImranViewProps) {
  const [searchQuery, setSearchQuery] = useState('');

  const filteredVerses = verses.filter(verse =>
    verse.number.includes(searchQuery) ||
    verse.lao.toLowerCase().includes(searchQuery.toLowerCase()) ||
    verse.english.toLowerCase().includes(searchQuery.toLowerCase()) ||
    verse.arabic.includes(searchQuery)
  );

  return (
    <div className="flex flex-col">
      <ViewHeader title="ສູຣໍ ອາລ ອິມຣອນ" onBack={goBack} />
      <div className="p-4 sticky top-0 bg-background z-10">
        <Input
          type="text"
          placeholder="ຄົ້ນຫາອາຍັດ..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full"
        />
      </div>
      <main className="p-4 pt-0">
        {filteredVerses.length > 0 ? (
          filteredVerses.map(v => <VerseCard key={v.number} {...v} />)
        ) : (
          <p className="text-center text-muted-foreground">ບໍ່ພົບອາຍັດທີ່ທ່ານຄົ້ນຫາ.</p>
        )}
        <SummaryCard title="ສະຫຼຸບ">
          ອາຍັດເຫຼົ່ານີ້ຢືນຢັນເຖິງຄວາມເປັນເອກະພາບຂອງອັນລໍ, ການປະທານຄຳພີຕ່າງໆ, ແລະ ໄດ້ກ່າວເຖິງການໂຕ້ຖຽງຂອງຜູ້ປະຕິເສດ. ມັນຍັງເລົ່າເລື່ອງການເກີດທີ່ມະຫັດສະຈັນຂອງນາງມາຣີຍຳ ແລະ ການເລີ່ມຕົ້ນພາລະກິດຂອງສາດສະດາອີຊາ.
        </SummaryCard>
      </main>
    </div>
  );
}
