'use client';
import ViewHeader from '@/components/shared/ViewHeader';
import VerseCard from '@/components/shared/VerseCard';
import SummaryCard from '@/components/shared/SummaryCard';

interface SurahAlBaqarahViewProps {
  goBack: () => void;
}

const verses = [
  { number: "2:1", arabic: "الم", lao: "ອາລີຟ, ລາມ, ມີມ.", english: "Alif, Lam, Meem." },
  { number: "2:2", arabic: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ هُدًى لِّلْمُتَّقِينَ", lao: "ຄໍາພີນີ້ (ກຸຣອານ), ບໍ່ມີຄວາມສົງໄສໃດໆໃນມັນ, ເປັນການຊີ້ແນະແກ່ບັນດາຜູ້ທີ່ມີຄວາມຍຳເກງ.", english: "This is the Book about which there is no doubt, a guidance for those conscious of Allah -" },
  { number: "2:3", arabic: "الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ", lao: "ບັນດາຜູ້ທີ່ເຊື່ອໃນສິ່ງທີ່ລັບເລິກ, ແລະດຳລົງການລະໝາດ, ແລະຈາກສິ່ງທີ່ເຮົາໄດ້ປະທານໃຫ້ພວກເຂົາ ພວກເຂົາກໍບໍລິຈາກ.", english: "Who believe in the unseen, establish prayer, and spend out of what We have provided for them," },
  { number: "2:4", arabic: "وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنزِلَ إِلَيْكَ وَمَا أُنزِلَ مِن قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوقِنُونَ", lao: "ແລະບັນດາຜູ້ທີ່ເຊື່ອໃນສິ່ງທີ່ຖືກເປີດເຜີຍລົງມາຫາເຈົ້າ, ແລະສິ່ງທີ່ຖືກເປີດເຜີຍລົງມາກ່ອນເຈົ້າ, ແລະພວກເຂົາກໍມີຄວາມເຊື່ອໝັ້ນຢ່າງເຕັມທີ່ໃນໂລກຫນ້າ.", english: "And who believe in what has been revealed to you, [O Muhammad], and what was revealed before you, and of the Hereafter they are certain [in faith]." },
  { number: "2:5", arabic: "أُولَٰئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ", lao: "ພວກເຂົານັ້ນຢູ່ເທິງເສັ້ນທາງທີ່ຖືກຕ້ອງຈາກພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຂົາ, ແລະພວກເຂົານັ້ນຄືບັນດາຜູ້ທີ່ໄດ້ຮັບຄວາມສຳເລັດ.", english: "Those are upon [right] guidance from their Lord, and it is those who are the successful." },
  { number: "2:6", arabic: "إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ", lao: "ແທ້ຈິງບັນດາຜູ້ທີ່ປະຕິເສດຄວາມເຊື່ອ, ບໍ່ວ່າເຈົ້າຈະຕັກເຕືອນພວກເຂົາຫຼືບໍ່ຕັກເຕືອນພວກເຂົາກໍຕາມ, ພວກເຂົາຈະບໍ່ເຊື່ອ.", english: "Indeed, those who disbelieve - it is all the same for them whether you warn them or do not warn them - they will not believe." },
  { number: "2:7", arabic: "خَتَمَ اللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ وَعَلَىٰ أَبْصَارِهِمْ غِشَاوَةٌ وَلَهُمْ عَذَابٌ عَظِيمٌ", lao: "ອັລລໍຮ໌ໄດ້ຊົງປະທັບຕາໄວ້ເທິງຫົວໃຈຂອງພວກເຂົາ ແລະເທິງການໄດ້ຍິນຂອງພວກເຂົາ, ແລະເທິງສາຍຕາຂອງພວກເຂົາມີຜ້າປິດໄວ້; ແລະສຳລັບພວກເຂົາຈະໄດ້ຮັບການທໍລະມານຢ່າງໃຫຍ່ຫຼວງ.", english: "Allah has set a seal upon their hearts and upon their hearing, and over their vision is a veil. And for them is a great punishment." },
  { number: "2:8", arabic: "وَمِنَ النَّاسِ مَن يَقُولُ آمَنَّا بِاللَّهِ وَبِالْيَوْمِ الْآخِرِ وَمَا هُم بِمُؤْمِنِينَ", lao: "ແລະໃນບັນດາມະນຸດ ມີຜູ້ທີ່ກ່າວວ່າ “ພວກເຮົາເຊື່ອໃນອັລລໍຮ໌ ແລະໃນວັນສຸດທ້າຍ” ແຕ່ພວກເຂົາບໍ່ແມ່ນຜູ້ທີ່ເຊື່ອ.", english: "And of the people are some who say, 'We believe in Allah and the Last Day,' but they are not believers." },
  { number: "2:9", arabic: "يُخَادِعُونَ اللَّهَ وَالَّذِينَ آمَنُوا وَمَا يَخْدَعُونَ إِلَّا أَنفُسَهُمْ وَمَا يَشْعُرُونَ", lao: "ພວກເຂົາຫຼອກລວງອັລລໍຮ໌ ແລະບັນດາຜູ້ທີ່ເຊື່ອ, ແຕ່ພວກເຂົາບໍ່ໄດ້ຫຼອກລວງໃຜນອກຈາກຕົວເອງເທົ່ານັ້ນ, ແລະພວກເຂົາກໍບໍ່ຮູ້ສຶກຕົວ.", english: "They [think to] deceive Allah and those who believe, but they deceive not except themselves and perceive [it] not." },
  { number: "2:10", arabic: "فِي قُلُوبِهِم مَّرَضٌ فَزَادَهُمُ اللَّهُ مَرَضًا وَلَهُمْ عَذَابٌ أَلِيمٌ بِمَا كَانُوا يَكْذِبُونَ", lao: "ໃນຫົວໃຈຂອງພວກເຂົາມີພະຍາດ, ແລ້ວອັລລໍຮ໌ກໍຊົງເພີ່ມພະຍາດໃຫ້ພວກເຂົາ, ແລະພວກເຂົາຈະໄດ້ຮັບການທໍລະມານຢ່າງເຈັບປວດເນື່ອງຈາກສິ່ງທີ່ພວກເຂົາເຄີຍຕົວະ.", english: "In their hearts is disease, so Allah has increased their disease; and for them is a painful punishment because they [habitually] used to lie." },
  { number: "2:11", arabic: "وَإِذَا قِيلَ لَهُمْ لَا تُفْسِدُوا فِي الْأَرْضِ قَالُوا إِنَّمَا نَحْنُ مُصْلِحُونَ", lao: "ແລະເມື່ອຖືກກ່າວແກ່ພວກເຂົາວ່າ: 'ຈົ່ງຢ່າສ້າງຄວາມເສຍຫາຍໃນແຜ່ນດິນ', ພວກເຂົາກ່າວວ່າ: 'ພວກເຮົາເປັນພຽງຜູ້ປັບປຸງແກ້ໄຂເທົ່ານັ້ນ'.", english: "And when it is said to them, 'Do not cause corruption on the earth,' they say, 'We are but reformers.'" },
  { number: "2:12", arabic: "أَلَا إِنَّهُمْ هُمُ الْمُفْسِدُونَ وَلَٰكِن لَّا يَشْعُرُونَ", lao: "ຈົ່ງຮູ້ໄວ້ວ່າ, ແທ້ຈິງແລ້ວ ພວກເຂົາຄືຜູ້ທີ່ສ້າງຄວາມເສຍຫາຍ, ແຕ່ພວກເຂົາບໍ່ຮູ້ສຶກຕົວ.", english: "Unquestionably, it is they who are the corrupters, but they perceive [it] not." },
  { number: "2:13", arabic: "وَإِذَا قِيلَ لَهُمْ آمِنُوا كَمَا آمَنَ النَّاسُ قَالُوا أَنُؤْمِنُ كَمَا آمَنَ السُّفَهَاءُ ۗ أَلَا إِنَّهُمْ هُمُ السُّفَهَاءُ وَلَٰكِن لَّا يَعْلَمُونَ", lao: "ແລະເມື່ອຖືກກ່າວແກ່ພວກເຂົາວ່າ: 'ຈົ່ງເຊື່ອເໝືອນດັ່ງທີ່ຄົນທັງຫຼາຍໄດ້ເຊື່ອ', ພວກເຂົາກ່າວວ່າ: 'ພວກເຮົາຈະເຊື່ອເໝືອນດັ່ງທີ່ຄົນໂງ່ໄດ້ເຊື່ອບໍ?' ຈົ່ງຮູ້ໄວ້ວ່າ, ແທ້ຈິງແລ້ວ ພວກເຂົາຄືຄົນໂງ່, ແຕ່ພວກເຂົາບໍ່ຮູ້.", english: "And when it is said to them, 'Believe as the people have believed,' they say, 'Should we believe as the foolish have believed?' Unquestionably, it is they who are the foolish, but they know it not." },
  { number: "2:14", arabic: "وَإِذَا لَقُوا الَّذِينَ آمَنُوا قَالُوا آمَنَّا وَإِذَا خَلَوْا إِلَىٰ شَيَاطِينِهِمْ قَالُوا إِنَّا مَعَكُمْ إِنَّمَا نَحْنُ مُسْتَهْزِئُونَ", lao: "ແລະເມື່ອພວກເຂົາພົບກັບບັນດາຜູ້ທີ່ເຊື່ອ, ພວກເຂົາກ່າວວ່າ: 'ພວກເຮົາເຊື່ອແລ້ວ'. ແຕ່ເມື່ອພວກເຂົາຢູ່ກັບພວກຜີມານຂອງພວກເຂົາ, ພວກເຂົາກ່າວວ່າ: 'ແທ້ຈິງ ພວກເຮົາຢູ່ກັບພວກເຈົ້າ, ພວກເຮົາເປັນພຽງຜູ້ທີ່ເຍາະເຍີ້ຍເທົ່ານັ້ນ'.", english: "And when they meet those who believe, they say, 'We believe'; but when they are alone with their evil ones, they say, 'Indeed, we are with you; we were only mockers.'" },
  { number: "2:15", arabic: "اللَّهُ يَسْتَهْزِئُ بِهِمْ وَيَمُدُّهُمْ فِي طُغْيَانِهِمْ يَعْمَهُونَ", lao: "ອັລລໍຮ໌ຈະຊົງເຍາະເຍີ້ຍພວກເຂົາ ແລະຈະຊົງປ່ອຍໃຫ້ພວກເຂົາຢູ່ໃນການລະເມີດຂອງພວກເຂົາຢ່າງບໍ່ມີຈຸດໝາຍ.", english: "Allah mocks them and prolongs them in their transgression [while] they wander blindly." },
  { number: "2:16", arabic: "أُولَٰئِكَ الَّذِينَ اشْتَرَوُا الضَّلَالَةَ بِالْهُدَىٰ فَمَا رَبِحَت تِّجَارَتُهُمْ وَمَا كَانُوا مُهْتَدِينَ", lao: "ພວກເຂົາຄືຜູ້ທີ່ໄດ້ຊື້ການຫຼົງທາງດ້ວຍການຊີ້ແນະ, ດັ່ງນັ້ນການຄ້າຂອງພວກເຂົາຈຶ່ງບໍ່ໄດ້ກຳໄລ ແລະ ພວກເຂົາບໍ່ໄດ້ເປັນຜູ້ທີ່ຖືກຊີ້ແນະ.", english: "Those are the ones who have purchased error [in exchange] for guidance, so their transaction has brought no profit, nor were they guided." },
  { number: "2:17", arabic: "مَثَلُهُمْ كَمَثَلِ الَّذِي اسْتَوْقَدَ نَارًا فَلَمَّا أَضَاءَتْ مَا حَوْلَهُ ذَهَبَ اللَّهُ بِنُورِهِمْ وَتَرَكَهُمْ فِي ظُلُمَاتٍ لَّا يُبْصِرُونَ", lao: "ຕົວຢ່າງຂອງພວກເຂົາຄືກັບຜູ້ທີ່ໄດ້ຈູດໄຟ, ເມື່ອໄຟໄດ້ສ່ອງແສງສິ່ງທີ່ຢູ່ອ້ອມຮອບລາວ, ອັລລໍຮ໌ກໍໄດ້ເອົາແສງສະຫວ່າງຂອງພວກເຂົາໄປ ແລະ ປ່ອຍພວກເຂົາໄວ້ໃນຄວາມມືດ, ພວກເຂົາບໍ່ສາມາດເຫັນໄດ້.", english: "Their example is that of one who kindled a fire, but when it illuminated what was around him, Allah took away their light and left them in darkness [so] they could not see." },
  { number: "2:18", arabic: "صُمٌّ بُكْمٌ عُمْيٌ فَهُمْ لَا يَرْجِعُونَ", lao: "ຫູໜວກ, ເປັນໃບ້, ຕາບອດ, ດັ່ງນັ້ນພວກເຂົາຈະບໍ່ກັບມາ.", english: "Deaf, dumb and blind - so they will not return [to the right path]." },
  { number: "2:19", arabic: "أَوْ كَصَيِّبٍ مِّنَ السَّمَاءِ فِيهِ ظُلُمَاتٌ وَرَعْدٌ وَبَرْقٌ يَجْعَلُونَ أَصَابِعَهُمْ فِي آذَانِهِم مِّنَ الصَّوَاعِقِ حَذَرَ الْمَوْتِ ۚ وَاللَّهُ مُحِيطٌ بِالْكَافِرِينَ", lao: "ຫຼືຄືກັບຝົນທີ່ຕົກລົງມາຈາກຟ້າ, ໃນນັ້ນມີຄວາມມືດ, ສຽງຟ້າຮ້ອງ, ແລະຟ້າແມບ. ພວກເຂົາເອົານິ້ວມືອັດຫູຂອງພວກເຂົາຈາກສຽງຟ້າຜ່າ ເພາະຢ້ານຄວາມຕາຍ. ແລະອັລລໍຮ໌ຊົງລ້ອມຜູ້ປະຕິເສດຄວາມເຊື່ອໄວ້.", english: "Or [it is] like a rainstorm from the sky within which is darkness, thunder and lightning. They put their fingers in their ears against the thunderclaps in dread of death. But Allah is encompassing of the disbelievers." },
  { number: "2.20", arabic: "يَكَادُ الْبَرْقُ يَخْطَفُ أَبْصَارَهُمْ ۖ كُلَّمَا أَضَاءَ لَهُم مَّشَوْا فِيهِ وَإِذَا أَظْلَمَ عَلَيْهِمْ قَامُوا ۚ وَلَوْ شَاءَ اللَّهُ لَذَهَبَ بِسَمْعِهِمْ وَأَبْصَارِهِمْ ۚ إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", lao: "ຟ້າແມບເກືອບຈະເອົາສາຍຕາຂອງພວກເຂົາໄປ. ທຸກຄັ້ງທີ່ມັນສ່ອງແສງໃຫ້ພວກເຂົາ, ພວກເຂົາກໍຍ່າງໄປໃນແສງນັ້ນ; ແລະເມື່ອມັນມືດລົງ, ພວກເຂົາກໍຢຸດ. ແລະຖ້າອັລລໍຮ໌ຊົງປະສົງ, ພຣະອົງຈະເອົາການໄດ້ຍິນແລະສາຍຕາຂອງພວກເຂົາໄປ. ແທ້ຈິງ, ອັລລໍຮ໌ຊົງມີອຳນາດເໜືອທຸກສິ່ງ.", english: "The lightning almost snatches away their sight. Every time it lights [the way] for them, they walk therein; but when darkness comes over them, they stand [still]. And if Allah had willed, He could have taken away their hearing and their sight. Indeed, Allah is over all things competent." },
  { number: "2.21", arabic: "يَا أَيُّهَا النَّاسُ اعْبُدُوا رَبَّكُمُ الَّذِي خَلَقَكُمْ وَالَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ", lao: "ໂອ້ ມະນຸດເອີຍ, ຈົ່ງນະມັດສະການພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຈົ້າ, ຜູ້ທີ່ໄດ້ສ້າງພວກເຈົ້າ ແລະຜູ້ທີ່ຢູ່ກ່ອນໜ້າພວກເຈົ້າ, ເພື່ອວ່າພວກເຈົ້າຈະໄດ້ມີຄວາມຢຳເກງ.", english: "O mankind, worship your Lord, who created you and those before you, that you may become righteous -" },
  { number: "2.22", arabic: "الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً وَأَنزَلَ مِنَ السَّمَاءِ مَاءً فَأَخْرَجَ بِهِ مِنَ الثَّمَرَاتِ رِزْقًا لَّكُمْ ۖ فَلَا تَجْعَلُوا لِلَّهِ أَندَادًا وَأَنتُمْ تَعْلَمُونَ", lao: "ຜູ້ທີ່ໄດ້ເຮັດໃຫ້ແຜ່ນດິນເປັນທີ່ນອນສຳລັບພວກເຈົ້າ, ແລະຟ້າເປັນຫຼັງຄາ, ແລະໄດ້ສົ່ງນ້ຳລົງມາຈາກຟ້າ, ແລ້ວໄດ້ເອົານ້ຳນັ້ນອອກມາເປັນໝາກໄມ້ເພື່ອເປັນອາຫານສຳລັບພວກເຈົ້າ. ດັ່ງນັ້ນ, ຢ່າຕັ້ງສິ່ງໃດເປັນຄູ່ແຂ່ງກັບອັລລໍຮ໌, ທັງທີ່ພວກເຈົ້າຮູ້.", english: "[He] who made for you the earth a bed [spread out] and the sky a ceiling and sent down from the sky, rain and brought forth thereby fruits as provision for you. So do not attribute to Allah equals while you know [that there is nothing similar to Him]." },
  { number: "2.23", arabic: "وَإِن كُنتُمْ فِي رَيْبٍ مِّمَّا نَزَّلْنَا عَلَىٰ عَبْدِنَا فَأْتُوا بِسُورَةٍ مِّن مِّثْلِهِ وَادْعُوا شُهَدَاءَكُم مِّن دُونِ اللَّهِ إِن كُنتُمْ صَادِقِينَ", lao: "ແລະຖ້າພວກເຈົ້າສົງໄສໃນສິ່ງທີ່ເຮົາໄດ້ເປີດເຜີຍລົງມາໃຫ້ແກ່ຂ້າທາດຂອງເຮົາ, ກໍຈົ່ງນຳມາຊັກບົດໜຶ່ງທີ່ເໝືອນກັບມັນ, ແລະຈົ່ງເອີ້ນພະຍານຂອງພວກເຈົ້ານອກຈາກອັລລໍຮ໌, ຖ້າພວກເຈົ້າເປັນຜູ້ທີ່ສັດຈິງ.", english: "And if you are in doubt about what We have sent down upon Our Servant [Muhammad], then produce a surah the like thereof and call upon your witnesses other than Allah, if you should be truthful." },
  { number: "2.24", arabic: "فَإِن لَّمْ تَفْعَلُوا وَلَن تَفْعَلُوا فَاتَّقُوا النَّارَ الَّتِي وَقُودُهَا النَّاسُ وَالْحِجَارَةُ ۖ أُعِدَّتْ لِلْكَافِرِينَ", lao: "ແຕ່ຖ້າພວກເຈົ້າບໍ່ສາມາດເຮັດໄດ້, ແລະພວກເຈົ້າຈະບໍ່ສາມາດເຮັດໄດ້ຢ່າງແນ່ນອນ, ກໍຈົ່ງຢ້ານກົວໄຟນະລົກ, ຊຶ່ງເຊື້ອໄຟຂອງມັນຄືມະນຸດແລະຫີນ, ທີ່ຖືກກະກຽມໄວ້ສຳລັບຜູ້ປະຕິເສດຄວາມເຊື່ອ.", english: "But if you do not - and you will never be able to - then fear the Fire, whose fuel is men and stones, prepared for the disbelievers." },
  { number: "2.25", arabic: "وَبَشِّرِ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أَنَّ لَهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ ۖ كُلَّمَا رُزِقُوا مِنْهَا مِن ثَمَرَةٍ رِّزْقًا ۙ قَالُوا هَٰذَا الَّذِي رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا بِهِ مُتَشَابِهًا ۖ وَلَهُمْ فِيهَا أَزْوَاجٌ مُّطَهَّرَةٌ ۖ وَهُمْ فِيهَا خَالِدُونَ", lao: "ແລະຈົ່ງແຈ້ງຂ່າວດີແກ່ບັນດາຜູ້ທີ່ເຊື່ອແລະເຮັດຄວາມດີວ່າ ສຳລັບພວກເຂົາຈະມີສວນສະຫວັນ, ຊຶ່ງມີແມ່ນ້ຳໄຫຼຜ່ານຢູ່ເບື້ອງລຸ່ມ. ທຸກຄັ້ງທີ່ພວກເຂົາໄດ້ຮັບໝາກໄມ້ຈາກສວນສະຫວັນເປັນອາຫານ, ພວກເຂົາຈະກ່າວວ່າ: 'ນີ້ຄືສິ່ງທີ່ພວກເຮົາເຄີຍໄດ້ຮັບມາກ່ອນ'. ແລະພວກເຂົາຈະໄດ້ຮັບມັນໃນລັກສະນະທີ່ຄ້າຍຄືກັນ. ແລະໃນນັ້ນພວກເຂົາຈະມີຄູ່ຄອງທີ່ບໍລິສຸດ, ແລະພວກເຂົາຈະຢູ່ໃນນັ້ນຕະຫຼອດໄປ.", english: "And give good tidings to those who believe and do righteous deeds that they will have gardens [in Paradise] beneath which rivers flow. Whenever they are provided with a provision of fruit therefrom, they will say, 'This is what we were provided with before.' And it will be given to them in likeness. And they will have therein purified spouses, and they will abide therein eternally." },
  { number: "2.26", arabic: "۞ إِنَّ اللَّهَ لَا يَسْتَحْيِي أَن يَضْرِبَ مَثَلًا مَّا بَعُوضَةً فَمَا فَوْقَهَا ۚ فَأَمَّا الَّذِينَ آمَنُوا فَيَعْلَمُونَ أَنَّهُ الْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا الَّذِينَ كَفَرُوا فَيَقُولُونَ مَاذَا أَرَادَ اللَّهُ بِهَٰذَا مَثَلًا ۘ يُضِلُّ بِهِ كَثِيرًا وَيَهْدِي بِهِ كَثِيرًا ۚ وَمَا يُضِلُّ بِهِ إِلَّا الْفَاسِقِينَ", lao: "ແທ້ຈິງ, ອັລລໍຮ໌ບໍ່ຊົງລະອາຍທີ່ຈະຍົກຕົວຢ່າງໃດໆ, ແມ້ຈະເປັນຍຸງ ຫຼືສິ່ງທີ່ເໜືອມັນ. ສ່ວນຜູ້ທີ່ເຊື່ອ, ພວກເຂົາຮູ້ວ່າມັນເປັນຄວາມຈິງຈາກພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຂົາ. ແຕ່ສ່ວນຜູ້ທີ່ປະຕິເສດ, ພວກເຂົາກ່າວວ່າ: 'ອັລລໍຮ໌ປະສົງສິ່ງໃດດ້ວຍຕົວຢ່າງນີ້?' ພຣະອົງຊົງເຮັດໃຫ້ຫຼາຍຄົນຫຼົງທາງດ້ວຍມັນ ແລະຊົງຊີ້ແນະຫຼາຍຄົນດ້ວຍມັນ. ແລະພຣະອົງບໍ່ໄດ້ເຮັດໃຫ້ຜູ້ໃດຫຼົງທາງດ້ວຍມັນນອກຈາກຜູ້ທີ່ລະເມີດ.", english: "Indeed, Allah is not timid to present an example - that of a mosquito or what is smaller than it. And those who believe know that it is the truth from their Lord. But as for those who disbelieve, they say, 'What did Allah intend by this as an example?' He misleads many thereby and guides many thereby. And He misleads not thereby except the defiantly disobedient," },
  { number: "2.27", arabic: "الَّذِينَ يَنقُضُونَ عَهْدَ اللَّهِ مِن بَعْدِ مِيثَاقِهِ وَيَقْطَعُونَ مَا أَمَرَ اللَّهُ بِهِ أَن يُوصَلَ وَيُفْسِدُونَ فِي الْأَرْضِ ۚ أُولَٰئِكَ هُمُ الْخَاسِرُونَ", lao: "ຜູ້ທີ່ລະເມີດສັນຍາຂອງອັລລໍຮ໌ຫຼັງຈາກທີ່ໄດ້ຢືນຢັນມັນ, ແລະຕັດສິ່ງທີ່ອັລລໍຮ໌ໄດ້ສັ່ງໃຫ້ເຊື່ອມຕໍ່, ແລະສ້າງຄວາມເສຍຫາຍໃນແຜ່ນດິນ. ພວກເຂົາຄືຜູ້ທີ່ຂາດທຶນ.", english: "Who break the covenant of Allah after contracting it and sever that which Allah has ordered to be joined and cause corruption on earth. It is those who are the losers." },
  { number: "2.28", arabic: "كَيْفَ تَكْفُرُونَ بِاللَّهِ وَكُنتُمْ أَمْوَاتًا فَأَحْيَاكُمْ ۖ ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَ", lao: "ພວກເຈົ້າຈະປະຕິເສດອັລລໍຮ໌ໄດ້ແນວໃດ, ທັງທີ່ພວກເຈົ້າເຄີຍຕາຍ ແລ້ວພຣະອົງໄດ້ໃຫ້ພວກເຈົ້າມີຊີວິດ? ຫຼັງຈາກນັ້ນ, ພຣະອົງຈະໃຫ້ພວກເຈົ້າຕາຍ, ແລ້ວຈະໃຫ້ພວກເຈົ້າມີຊີວິດອີກ, ແລ້ວພວກເຈົ້າຈະຖືກນຳກັບໄປຫາພຣະອົງ.", english: "How can you disbelieve in Allah when you were lifeless and He brought you to life; then He will cause you to die, then He will bring you [back] to life, and then to Him you will be returned." },
  { number: "2.29", arabic: "هُوَ الَّذِي خَلَقَ لَكُم مَّا فِي الْأَرْضِ جَمِيعًا ثُمَّ اسْتَوَىٰ إِلَى السَّمَاءِ فَسَوَّاهُنَّ سَبْعَ سَمَاوَاتٍ ۚ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ", lao: "ພຣະອົງຄືຜູ້ທີ່ໄດ້ສ້າງທຸກສິ່ງໃນແຜ່ນດິນໄວ້ສຳລັບພວກເຈົ້າ, ຫຼັງຈາກນັ້ນພຣະອົງໄດ້ຫັນໄປຫາທ້ອງຟ້າ ແລະໄດ້ເຮັດໃຫ້ມັນສົມບູນເປັນເຈັດຊັ້ນຟ້າ. ແລະພຣະອົງຊົງຮູ້ທຸກສິ່ງ.", english: "It is He who created for you all of that which is on the earth. Then He directed Himself to the heaven, [His being above all creation], and made them seven heavens, and He is Knowing of all things." },
  { number: "2.30", arabic: "وَإِذْ قَالَ رَبُّكَ لِلْمَلَائِكَةِ إِنِّي جَاعِلٌ فِي الْأَرْضِ خَلِيفَةً ۖ قَالُوا أَتَجْعَلُ فِيهَا مَن يُفْسِدُ فِيهَا وَيَسْفِكُ الدِّمَاءَ وَنَحْنُ نُسَبِّحُ بِحَمْدِكَ وَنُقَدِّسُ لَكَ ۖ قَالَ إِنِّي أَعْلَمُ مَا لَا تَعْلَمُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເວລາທີ່ພຣະຜູ້ເປັນເຈົ້າຂອງເຈົ້າໄດ້ກ່າວແກ່ທູດສະຫວັນວ່າ: 'ແທ້ຈິງ, ຂ້ອຍຈະຕັ້ງຜູ້ຕາງໜ້າໄວ້ໃນແຜ່ນດິນ.' ພວກເຂົາກ່າວວ່າ: 'ພຣະອົງຈະຕັ້ງຜູ້ທີ່ຈະສ້າງຄວາມເສຍຫາຍແລະເຮັດໃຫ້ເລືອດໄຫຼໃນນັ້ນບໍ, ທັງທີ່ພວກເຮົາສັນລະເສີນພຣະອົງແລະຍ້ອງຍໍຄວາມບໍລິສຸດຂອງພຣະອົງ?' ພຣະອົງກ່າວວ່າ: 'ແທ້ຈິງ, ຂ້ອຍຮູ້ໃນສິ່ງທີ່ພວກເຈົ້າບໍ່ຮູ້.'", english: "And [mention, O Muhammad], when your Lord said to the angels, 'Indeed, I will make upon the earth a successive authority.' They said, 'Will You place upon it one who causes corruption therein and sheds blood, while we declare Your praise and sanctify You?' Allah said, 'Indeed, I know that which you do not know.'" },
  { number: "2:31", arabic: "وَعَلَّمَ آدَمَ الْأَسْمَاءَ كُلَّهَا ثُمَّ عَرَضَهُمْ عَلَى الْمَلَائِكَةِ فَقَالَ أَنبِئُونِي بِأَسْمَاءِ هَٰؤُلَاءِ إِن كُنتُمْ صَادِقِينَ", lao: "ແລະພຣະອົງໄດ້ສອນຊື່ທັງໝົດໃຫ້ແກ່ອາດັມ, ຫຼັງຈາກນັ້ນພຣະອົງໄດ້ສະແດງພວກເຂົາຕໍ່ໜ້າທູດສະຫວັນ ແລະກ່າວວ່າ: 'ຈົ່ງບອກຊື່ຂອງສິ່ງເຫຼົ່ານີ້ໃຫ້ຂ້ອຍຮູ້, ຖ້າພວກເຈົ້າເປັນຜູ້ທີ່ສັດຈິງ.'", english: "And He taught Adam the names - all of them. Then He showed them to the angels and said, 'Inform Me of the names of these, if you are truthful.'" },
  { number: "2:32", arabic: "قَالُوا سُبْحَانَكَ لَا عِلْمَ لَنَا إِلَّا مَا عَلَّمْتَنَا ۖ إِنَّكَ أَنتَ الْعَلِيمُ الْحَكِيمُ", lao: "ພວກເຂົາກ່າວວ່າ: 'ມະຫາບໍລິສຸດແດ່ພຣະອົງ! ພວກເຮົາບໍ່ມີຄວາມຮູ້ນອກຈາກສິ່ງທີ່ພຣະອົງໄດ້ສອນພວກເຮົາ. ແທ້ຈິງ, ພຣະອົງຄືຜູ້ຊົງຮອບຮູ້, ຜູ້ຊົງມີປັນຍາ.'", english: "They said, 'Exalted are You; we have no knowledge except what You have taught us. Indeed, it is You who is the Knowing, the Wise.'" },
  { number: "2:33", arabic: "قَالَ يَا آدَمُ أَنبِئْهُم بِأَسْمَائِهِمْ ۖ فَلَمَّا أَنبَأَهُم بِأَسْمَائِهِمْ قَالَ أَلَمْ أَقُل لَّكُمْ إِنِّي أَعْلَمُ غَيْبَ السَّمَاوَاتِ وَالْأَرْضِ وَأَعْلَمُ مَا تُبْدُونَ وَمَا كُنتُمْ تَكْتُمُونَ", lao: "ພຣະອົງກ່າວວ່າ: 'ໂອ້ ອາດັມ, ຈົ່ງບອກຊື່ຂອງພວກເຂົາໃຫ້ພວກເຂົາຮູ້.' ເມື່ອລາວໄດ້ບອກຊື່ຂອງພວກເຂົາ, ພຣະອົງກ່າວວ່າ: 'ຂ້ອຍບໍ່ໄດ້ບອກພວກເຈົ້າບໍວ່າ ແທ້ຈິງຂ້ອຍຮູ້ຄວາມລັບຂອງຊັ້ນຟ້າແລະແຜ່ນດິນ, ແລະຂ້ອຍຮູ້ສິ່ງທີ່ພວກເຈົ້າເປີດເຜີຍແລະສິ່ງທີ່ພວກເຈົ້າປິດບັງ?'", english: "He said, 'O Adam, inform them of their names.' And when he had informed them of their names, He said, 'Did I not tell you that I know the unseen [aspects] of the heavens and the earth? And I know what you reveal and what you have concealed.'" },
  { number: "2:34", arabic: "وَإِذْ قُلْنَا لِلْمَلَائِكَةِ اسْجُدُوا لِآدَمَ فَسَجَدُوا إِلَّا إِبْلِيسَ أَبَىٰ وَاسْتَكْبَرَ وَكَانَ مِنَ الْكَافِرِينَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອເຮົາໄດ້ກ່າວແກ່ທູດສະຫວັນວ່າ: 'ຈົ່ງກົ້ມຂາບຕໍ່ອາດັມ.' ພວກເຂົາກໍກົ້ມຂາບຍົກເວັ້ນອິບລີສ. ລາວປະຕິເສດແລະອວດດີ, ແລະລາວຢູ່ໃນກຸ່ມຜູ້ປະຕິເສດ.", english: "And [mention] when We said to the angels, 'Prostrate before Adam'; so they prostrated, except for Iblees. He refused and was arrogant and became of the disbelievers." },
  { number: "2:35", arabic: "وَقُلْنَا يَا آدَمُ اسْكُنْ أَنتَ وَزَوْجُكَ الْجَنَّةَ وَكُلَا مِنْهَا رَغَدًا حَيْثُ شِئْتُمَا وَلَا تَقْرَبَا هَٰذِهِ الشَّجَرَةَ فَتَكُونَا مِنَ الظَّالِمِينَ", lao: "ແລະເຮົາໄດ້ກ່າວວ່າ: 'ໂອ້ ອາດັມ, ຈົ່ງອາໄສຢູ່ໃນສວນສະຫວັນທັງເຈົ້າແລະຄູ່ຄອງຂອງເຈົ້າ, ແລະຈົ່ງກິນຈາກມັນຢ່າງອຸດົມສົມບູນຕາມທີ່ເຈົ້າຕ້ອງການ, ແຕ່ຢ່າເຂົ້າໃກ້ຕົ້ນໄມ້ນີ້, ຖ້າບໍ່ດັ່ງນັ້ນພວກເຈົ້າຈະກາຍເປັນຜູ້ທີ່ບໍ່ຍຸດຕິທຳ.'", english: "And We said, 'O Adam, dwell, you and your wife, in Paradise and eat therefrom in [ease and] abundance from wherever you will. But do not approach this tree, lest you be among the wrongdoers.'" },
  { number: "2:36", arabic: "فَأَزَلَّهُمَا الشَّيْطَانُ عَنْهَا فَأَخْرَجَهُمَا مِمَّا كَانَا فِيهِ ۖ وَقُلْنَا اهْبِطُوا بَعْضُكُمْ لِبَعْضٍ عَدُوٌّ ۖ وَلَكُمْ فِي الْأَرْضِ مُسْتَقَرٌّ وَمَتَاعٌ إِلَىٰ حِينٍ", lao: "ແຕ່ຊັຍຕອນໄດ້ເຮັດໃຫ້ພວກເຂົາຫຼົງຜິດຈາກມັນ ແລະໄດ້ຂັບໄລ່ພວກເຂົາອອກຈາກສິ່ງທີ່ພວກເຂົາເຄີຍຢູ່. ແລະເຮົາໄດ້ກ່າວວ່າ: 'ຈົ່ງລົງໄປ, ບາງຄົນໃນພວກເຈົ້າເປັນສັດຕູຕໍ່ກັນ. ແລະສຳລັບພວກເຈົ້າຈະມີທີ່ພັກອາໄສໃນແຜ່ນດິນແລະຄວາມສຸກຊົ່ວຄາວ.'", english: "But Satan caused them to slip out of it and removed them from that [condition] in which they had been. And We said, 'Go down, [all of you], as enemies to one another, and you will have upon the earth a place of settlement and provision for a time.'" },
  { number: "2:37", arabic: "فَتَلَقَّىٰ آدَمُ مِن رَّبِّهِ كَلِمَاتٍ فَتَابَ عَلَيْهِ ۚ إِنَّهُ هُوَ التَّوَّابُ الرَّحِيمُ", lao: "ຫຼັງຈາກນັ້ນ, ອາດັມໄດ້ຮັບຄຳສອນຈາກພຣະຜູ້ເປັນເຈົ້າຂອງລາວ, ແລ້ວພຣະອົງໄດ້ອະໄພໃຫ້ລາວ. ແທ້ຈິງ, ພຣະອົງຄືຜູ້ຊົງອະໄພ, ຜູ້ຊົງເມດຕາສະເໝີ.", english: "Then Adam received from his Lord [some] words, and He accepted his repentance. Indeed, it is He who is the Accepting of repentance, the Merciful." },
  { number: "2:38", arabic: "قُلْنَا اهْبِطُوا مِنْهَا جَمِيعًا ۖ فَإِمَّا يَأْتِيَنَّكُم مِّنِّي هُدًى فَمَن تَبِعَ هُدَايَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ", lao: "ເຮົາໄດ້ກ່າວວ່າ: 'ຈົ່ງລົງໄປຈາກທີ່ນີ້ທັງໝົດ. ຖ້າມີການຊີ້ແນະຈາກຂ້ອຍມາຫາພວກເຈົ້າ, ຜູ້ໃດທີ່ຕາມການຊີ້ແນະຂອງຂ້ອຍ, ຈະບໍ່ມີຄວາມຢ້ານກົວໃດໆຕໍ່ພວກເຂົາ ແລະພວກເຂົາຈະບໍ່ໂສກເສົ້າ.'", english: "We said, 'Go down from it, all of you. And when guidance comes to you from Me, whoever follows My guidance - there will be no fear concerning them, nor will they grieve.'" },
  { number: "2:39", arabic: "وَالَّذِينَ كَفَرُوا وَكَذَّبُوا بِآيَاتِنَا أُولَٰئِكَ أَصْحَابُ النَّارِ ۖ هُمْ فِيهَا خَالِدُونَ", lao: "ແລະຜູ້ທີ່ປະຕິເສດແລະຕົວະຕໍ່ອາຍະຕ່າງໆຂອງເຮົາ, ພວກເຂົາຄືຊາວນາລົກ; ພວກເຂົາຈະຢູ່ໃນນັ້ນຕະຫຼອດໄປ.", english: "And those who disbelieve and deny Our signs - those are the companions of the Fire; they will abide therein eternally." },
  { number: "2:40", arabic: "يَا بَنِي إِسْرَائِيلَ اذْكُرُوا نِعْمَتِيَ الَّتِي أَنْعَمْتُ عَلَيْكُمْ وَأَوْفُوا بِعَهْدِي أُوفِ بِعَهْدِكُمْ وَإِيَّايَ فَارْهَبُونِ", lao: "ໂອ້ ລູກຫຼານຂອງອິດສະຣາເອວ, ຈົ່ງລະນຶກເຖິງຄວາມໂປດປານຂອງຂ້ອຍທີ່ຂ້ອຍໄດ້ໃຫ້ແກ່ພວກເຈົ້າ, ແລະຈົ່ງຮັກສາສັນຍາຂອງຂ້ອຍ, ຂ້ອຍກໍຈະຮັກສາສັນຍາຂອງພວກເຈົ້າ. ແລະຈົ່ງຢຳເກງຂ້ອຍພຽງຜູ້ດຽວ.", english: "O Children of Israel, remember My favor which I have bestowed upon you and fulfill My covenant [upon you] that I will fulfill your covenant [from Me], and be afraid of [only] Me." },
  { number: "2:41", arabic: "وَآمِنُوا بِمَا أَنزَلْتُ مُصَدِّقًا لِّمَا مَعَكُمْ وَلَا تَكُونُوا أَوَّلَ كَافِرٍ بِهِ ۖ وَلَا تَشْتَرُوا بِآيَاتِي ثَمَنًا قَلِيلًا وَإِيَّايَ فَاتَّقُونِ", lao: "ແລະຈົ່ງເຊື່ອໃນສິ່ງທີ່ຂ້ອຍໄດ້ເປີດເຜີຍລົງມາ, ເຊິ່ງຢືນຢັນສິ່ງທີ່ພວກເຈົ້າມີຢູ່, ແລະຢ່າເປັນຜູ້ທຳອິດທີ່ປະຕິເສດມັນ. ແລະຢ່າແລກປ່ຽນອາຍະຕ່າງໆຂອງຂ້ອຍດ້ວຍລາຄາທີ່ຕໍ່າຕ້ອຍ, ແລະຈົ່ງຢຳເກງຂ້ອຍພຽງຜູ້ດຽວ.", english: "And believe in what I have sent down confirming that which is [already] with you, and be not the first to disbelieve in it. And do not exchange My signs for a small price, and fear [only] Me." },
  { number: "2:42", arabic: "وَلَا تَلْبِسُوا الْحَقَّ بِالْبَاطِلِ وَتَكْتُمُوا الْحَقَّ وَأَنتُمْ تَعْلَمُونَ", lao: "ແລະຢ່າປົນຄວາມຈິງກັບຄວາມຕົວະ, ແລະຢ່າປິດບັງຄວາມຈິງທັງທີ່ພວກເຈົ້າຮູ້.", english: "And do not mix the truth with falsehood or conceal the truth while you know [it]." },
  { number: "2:43", arabic: "وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ وَارْكَعُوا مَعَ الرَّاكِعِينَ", lao: "ແລະຈົ່ງດຳລົງການລະໝາດ, ແລະຈົ່ງຈ່າຍຊາກາດ, ແລະຈົ່ງກົ້ມຂາບພ້ອມກັບຜູ້ທີ່ກົ້ມຂາບ.", english: "And establish prayer and give zakah and bow with those who bow [in worship and obedience]." },
  { number: "2:44", arabic: "أَتَأْمُرُونَ النَّاسَ بِالْبِرِّ وَتَنسَوْنَ أَنفُسَكُمْ وَأَنتُمْ تَتْلُونَ الْكِتَابَ ۚ أَفَلَا تَعْقِلُونَ", lao: "ພວກເຈົ້າສັ່ງໃຫ້ຄົນອື່ນເຮັດຄວາມດີແລ້ວລືມຕົວເອງບໍ, ທັງທີ່ພວກເຈົ້າອ່ານຄຳພີ? ພວກເຈົ້າບໍ່ຄິດບໍ?", english: "Do you order righteousness of the people and forget yourselves while you recite the Scripture? Then will you not reason?" },
  { number: "2:45", arabic: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى الْخَاشِعِينَ", lao: "ແລະຈົ່ງຂໍຄວາມຊ່ວຍເຫຼືອດ້ວຍຄວາມອົດທົນແລະການລະໝາດ. ແລະແທ້ຈິງ, ມັນເປັນສິ່ງທີ່ຍາກລຳບາກຍົກເວັ້ນສຳລັບผู้ທີ່ຖ່ອມຕົນ.", english: "And seek help through patience and prayer, and indeed, it is difficult except for the humbly submissive [to Allah]" },
  { number: "2:46", arabic: "الَّذِينَ يَظُنُّونَ أَنَّهُم مُّلَاقُو رَبِّهِمْ وَأَنَّهُمْ إِلَيْهِ رَاجِعُونَ", lao: "ຜູ້ທີ່ແນ່ໃຈວ່າພວກເຂົາຈະໄດ້ພົບກັບພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຂົາ ແລະພວກເຂົາຈະກັບໄປຫາພຣະອົງ.", english: "Who are certain that they will meet their Lord and that they will return to Him." },
  { number: "2:47", arabic: "يَا بَنِي إِسْرَائِيلَ اذْكُرُوا نِعْمَتِيَ الَّتِي أَنْعَمْتُ عَلَيْكُمْ وَأَنِّي فَضَّلْتُكُمْ عَلَى الْعَالَمِينَ", lao: "ໂອ້ ລູກຫຼານຂອງອິດສະຣາເອວ, ຈົ່ງລະນຶກເຖິງຄວາມໂປດປານຂອງຂ້ອຍທີ່ຂ້ອຍໄດ້ໃຫ້ແກ່ພວກເຈົ້າ ແລະວ່າຂ້ອຍໄດ້ຍົກຍ້ອງພວກເຈົ້າເໜືອຄົນທັງຫຼາຍ.", english: "O Children of Israel, remember My favor that I have bestowed upon you and that I preferred you over the worlds." },
  { number: "2:48", arabic: "وَاتَّقُوا يَوْمًا لَّا تَجْزِي نَفْسٌ عَن نَّفْسٍ شَيْئًا وَلَا يُقْبَلُ مِنْهَا شَفَاعَةٌ وَلَا يُؤْخَذُ مِنْهَا عَدْلٌ وَلَا هُمْ يُنصَرُونَ", lao: "ແລະຈົ່ງຢຳເກງວັນທີ່ບໍ່ມີໃຜສາມາດຊ່ວຍເຫຼືອໃຜໄດ້, ແລະບໍ່ມີການໄກ່ເກ່ຍໃດໆຈະຖືກຮັບຈາກລາວ, ແລະບໍ່ມີຄ່າໄຖ່ໃດໆຈະຖືກເອົາຈາກລາວ, ແລະພວກເຂົາຈະບໍ່ໄດ້ຮັບການຊ່ວຍເຫຼືອ.", english: "And fear a Day when no soul will suffice for another soul at all, nor will intercession be accepted from it, nor will compensation be taken from it, nor will they be aided." },
  { number: "2:49", arabic: "وَإِذْ نَجَّيْنَاكُم مِّنْ آلِ فِرْعَوْنَ يَسُومُونَكُمْ سُوءَ الْعَذَابِ يُذَبِّحُونَ أَبْنَاءَكُمْ وَيَسْتَحْيُونَ نِسَاءَكُمْ ۚ وَفِي ذَٰلِكُم بَلَاءٌ مِّن رَّبِّكُمْ عَظِيمٌ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອເຮົາໄດ້ຊ່ວຍພວກເຈົ້າໃຫ້ພົ້ນຈາກພັກພວກຂອງຟາໂຣ, ຜູ້ທີ່ໄດ້ທໍລະມານພວກເຈົ້າຢ່າງໂຫດຮ້າຍ, ຂ້າລູກຊາຍຂອງພວກເຈົ້າແລະປະໄວ້ລູກສາວຂອງພວກເຈົ້າ. ແລະໃນນັ້ນມີການທົດສອບອັນໃຫຍ່ຫຼວງຈາກພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຈົ້າ.", english: "And [recall] when We saved your forefathers from the people of Pharaoh, who afflicted you with the worst torment, slaughtering your [newborn] sons and keeping your females alive. And in that was a great trial from your Lord." },
  { number: "2:50", arabic: "وَإِذْ فَرَقْنَا بِكُمُ الْبَحْرَ فَأَنجَيْنَاكُمْ وَأَغْرَقْنَا آلَ فِرْعَوْنَ وَأَنتُمْ تَنظُرُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອເຮົາໄດ້ແຍກທະເລໃຫ້ພວກເຈົ້າ, ແລ້ວໄດ້ຊ່ວຍພວກເຈົ້າໃຫ້ພົ້ນແລະໄດ້ຈົມພັກພວກຂອງຟາໂຣໃນຂະນະທີ່ພວກເຈົ້າເບິ່ງຢູ່.", english: "And [recall] when We parted the sea for you and saved you and drowned the people of Pharaoh while you were looking on." },
  { number: "2:51", arabic: "وَإِذْ وَاعَدْنَا مُوسَىٰ أَرْبَعِينَ لَيْلَةً ثُمَّ اتَّخَذْتُمُ الْعِجْلَ مِن بَعْدِهِ وَأَنتُمْ ظَالِمُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອເຮົາໄດ້ສັນຍາກັບມູຊາເປັນເວລາສີ່ສິບຄືນ, ແລ້ວພວກເຈົ້າໄດ້ເອົາລູກງົວມາເປັນພະເຈົ້າຫຼັງຈາກລາວ, ແລະພວກເຈົ້າກໍເປັນຜູ້ທີ່ບໍ່ຍຸດຕິທຳ.", english: "And [recall] when We made an appointment with Moses for forty nights. Then you took [for worship] the calf after him, while you were wrongdoers." },
  { number: "2:52", arabic: "ثُمَّ عَفَوْنَا عَنكُم مِّن بَعْدِ ذَٰلِكَ لَعَلَّكُمْ تَشْكُرُونَ", lao: "ຫຼັງຈາກນັ້ນ, ເຮົາໄດ້ອະໄພໃຫ້ພວກເຈົ້າ, ເພື່ອວ່າພວກເຈົ້າຈະໄດ້ຂອບໃຈ.", english: "Then We forgave you after that so perhaps you would be grateful." },
  { number: "2:53", arabic: "وَإِذْ آتَيْنَا مُوسَى الْكِتَابَ وَالْفُرْقَانَ لَعَلَّكُمْ تَهْتَدُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອເຮົາໄດ້ໃຫ້ຄຳພີແລະສິ່ງທີ່ຈຳແນກແກ່ມູຊາ, ເພື່ອວ່າພວກເຈົ້າຈະໄດ້ຮັບການຊີ້ແນະ.", english: "And [recall] when We gave Moses the Scripture and the criterion that perhaps you would be guided." },
  { number: "2:54", arabic: "وَإِذْ قَالَ مُوسَىٰ لِقَوْمِهِ يَا قَوْمِ إِنَّكُمْ ظَلَمْتُمْ أَنفُسَكُم بِاتِّخَاذِكُمُ الْعِجْلَ فَتُوبُوا إِلَىٰ بَارِئِكُمْ فَاقْتُلُوا أَنفُسَكُمْ ذَٰلِكُمْ خَيْرٌ لَّكُمْ عِندَ بَارِئِكُمْ فَتَابَ عَلَيْكُمْ ۚ إِنَّهُ هُوَ التَّوَّابُ الرَّحِيمُ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອມູຊາໄດ້ກ່າວແກ່ປະຊາຊົນຂອງລາວວ່າ: 'ໂອ້ ປະຊາຊົນຂອງຂ້ອຍ, ແທ້ຈິງພວກເຈົ້າໄດ້ທຳຮ້າຍຕົວເອງໂດຍການເອົາລູກງົວມາເປັນພະເຈົ້າ. ດັ່ງນັ້ນ, ຈົ່ງກັບໃຈຕໍ່ພຣະຜູ້ສ້າງຂອງພວກເຈົ້າແລະຈົ່ງຂ້າຕົວເອງ. ນັ້ນເປັນສິ່ງທີ່ດີກວ່າສຳລັບພວກເຈົ້າຕໍ່ໜ້າພຣະຜູ້ສ້າງຂອງພວກເຈົ້າ.' ແລ້ວພຣະອົງໄດ້ອະໄພໃຫ້ພວກເຈົ້າ. ແທ້ຈິງ, ພຣະອົງຄືຜູ້ຊົງອະໄພ, ຜູ້ຊົງເມດຕາ.", english: "And [recall] when Moses said to his people, 'O my people, indeed you have wronged yourselves by your taking of the calf [for worship]. So repent to your Creator and kill yourselves. That is best for you in the sight of your Creator.' Then He accepted your repentance; indeed, He is the Accepting of repentance, the Merciful." },
  { number: "2:55", arabic: "وَإِذْ قُلْتُمْ يَا مُوسَىٰ لَن نُّؤْمِنَ لَكَ حَتَّىٰ نَرَى اللَّهَ جَهْرَةً فَأَخَذَتْكُمُ الصَّاعِقَةُ وَأَنتُمْ تَنظُرُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອພວກເຈົ້າໄດ້ກ່າວວ່າ: 'ໂອ້ ມູຊາ, ພວກເຮົາຈະບໍ່ເຊື່ອເຈົ້າຈົນກວ່າພວກເຮົາຈະເຫັນອັລລໍຮ໌ຢ່າງເປີດເຜີຍ.' ແລ້ວສຽງຟ້າຜ່າໄດ້ເອົາພວກເຈົ້າໄປໃນຂະນະທີ່ພວກເຈົ້າເບິ່ງຢູ່.", english: "And [recall] when you said, 'O Moses, we will never believe you until we see Allah outright'; so the thunderbolt took you while you were looking on." },
  { number: "2:56", arabic: "ثُمَّ بَعَثْنَاكُم مِّن بَعْدِ مَوْتِكُمْ لَعَلَّكُمْ تَشْكُرُونَ", lao: "ຫຼັງຈາກນັ້ນ, ເຮົາໄດ້ປຸກພວກເຈົ້າຂຶ້ນມາຫຼັງຈາກຄວາມຕາຍຂອງພວກເຈົ້າ, ເພື່ອວ່າພວກເຈົ້າຈະໄດ້ຂອບໃຈ.", english: "Then We revived you after your death that perhaps you would be grateful." },
  { number: "2:57", arabic: "وَظَلَّلْنَا عَلَيْكُمُ الْغَمَامَ وَأَنزَلْنَا عَلَيْكُمُ الْمَنَّ وَالسَّلْوَىٰ ۖ كُلُوا مِن طَيِّبَاتِ مَا رَزَقْنَاكُمْ ۖ وَمَا ظَلَمُونَا وَلَٰكِن كَانُوا أَنفُسَهُمْ يَظْلِمُونَ", lao: "ແລະເຮົາໄດ້ເຮັດໃຫ້ເມກເປັນຮົ່ມເງົາໃຫ້ພວກເຈົ້າ ແລະໄດ້ສົ່ງມັນນາແລະນົກກະທາລົງມາໃຫ້ພວກເຈົ້າ. 'ຈົ່ງກິນຈາກສິ່ງທີ່ດີທີ່ເຮົາໄດ້ໃຫ້ແກ່ພວກເຈົ້າ.' ແລະພວກເຂົາບໍ່ໄດ້ທຳຮ້າຍເຮົາ, ແຕ່ພວກເຂົາທຳຮ້າຍຕົວເອງ.", english: "And We shaded you with clouds and sent down to you manna and quails, [saying], 'Eat from the good things with which We have provided you.' And they wronged Us not - but they were [only] wronging themselves." },
  { number: "2:58", arabic: "وَإِذْ قُلْنَا ادْخُلُوا هَٰذِهِ الْقَرْيَةَ فَكُلُوا مِنْهَا حَيْثُ شِئْتُمْ رَغَدًا وَادْخُلُوا الْبَابَ سُجَّدًا وَقُولُوا حِطَّةٌ نَّغْفِرْ لَكُمْ خَطَايَاكُمْ ۚ وَسَنَزِيدُ الْمُحْسِنِينَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອເຮົາໄດ້ກ່າວວ່າ: 'ຈົ່ງເຂົ້າໄປໃນເມືອງນີ້ແລະກິນຈາກມັນຢ່າງອຸດົມສົມບູນຕາມທີ່ເຈົ້າຕ້ອງການ, ແລະຈົ່ງເຂົ້າປະຕູດ້ວຍການກົ້ມຂາບແລະກ່າວວ່າ 'ຮິດຕໍ', ເຮົາຈະອະໄພໃຫ້ຄວາມຜິດຂອງພວກເຈົ້າ. ແລະເຮົາຈະເພີ່ມໃຫ້ແກ່ผู้ທີ່ເຮັດຄວາມດີ.'", english: "And [recall] when We said, 'Enter this city and eat from it wherever you will in [ease and] abundance, and enter the gate bowing humbly and say, 'Relieve us of our burdens.' We will [then] forgive your sins for you, and We will increase the doers of good.'" },
  { number: "2:59", arabic: "فَبَدَّلَ الَّذِينَ ظَلَمُوا قَوْلًا غَيْرَ الَّذِي قِيلَ لَهُمْ فَأَنزَلْنَا عَلَى الَّذِينَ ظَلَمُوا رِجْزًا مِّنَ السَّمَاءِ بِمَا كَانُوا يَفْسُقُونَ", lao: "ແຕ່ຜູ້ທີ່ບໍ່ຍຸດຕິທຳໄດ້ປ່ຽນຄຳເວົ້າທີ່ຖືກບອກໃຫ້ພວກເຂົາ. ດັ່ງນັ້ນ, ເຮົາໄດ້ສົ່ງການລົງໂທດຈາກທ້ອງຟ້າລົງມາໃສ່ຜູ້ທີ່ບໍ່ຍຸດຕິທຳເນື່ອງຈາກການລະເມີດຂອງພວກເຂົາ.", english: "But those who wronged changed [the words] to a statement other than that which had been said to them, so We sent down upon those who wronged a punishment from the sky because they were defiantly disobeying." },
  { number: "2:60", arabic: "وَإِذِ اسْتَسْقَىٰ مُوسَىٰ لِقَوْمِهِ فَقُلْنَا اضْرِب بِّعَصَاكَ الْحَجَرَ ۖ فَانفَجَرَتْ مِنْهُ اثْنَتَا عَشْرَةَ عَيْنًا ۖ قَدْ عَلِمَ كُلُّ أُنَاسٍ مَّشْرَبَهُمْ ۖ كُلُوا وَاشْرَبُوا مِن رِّزْقِ اللَّهِ وَلَا تَعْثَوْا فِي الْأَرْضِ مُفْسِدِينَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອມູຊາໄດ້ຂໍນ້ຳໃຫ້ປະຊາຊົນຂອງລາວ, ແລ້ວເຮົາໄດ້ກ່າວວ່າ: 'ຈົ່ງຕີຫີນດ້ວຍໄມ້ເທົ້າຂອງເຈົ້າ.' ແລ້ວສິບສອງຕານ້ຳໄດ້ໄຫຼອອກມາຈາກມັນ. ແຕ່ລະເຜົ່າໄດ້ຮູ້ບ່ອນດື່ມຂອງຕົນ. 'ຈົ່ງກິນແລະດື່ມຈາກສິ່ງທີ່ອັລລໍຮ໌ໄດ້ໃຫ້, ແລະຢ່າສ້າງຄວາມເສຍຫາຍໃນແຜ່ນດິນ.'", english: "And [recall] when Moses prayed for water for his people, so We said, 'Strike with your staff the stone.' And there gushed forth from it twelve springs, and every people knew its watering place. 'Eat and drink from the provision of Allah, and do not commit abuse on the earth, spreading corruption.'" },
  { number: "2:61", arabic: "وَإِذْ قُلْتُمْ يَا مُوسَىٰ لَن نَّصْبِرَ عَلَىٰ طَعَامٍ وَاحِدٍ فَادْعُ لَنَا رَبَّكَ يُخْرِجْ لَنَا مِمَّا تُنبِتُ الْأَرْضُ مِن بَقْلِهَا وَقِثَّائِهَا وَفُومِهَا وَعَدَسِهَا وَبَصَلِهَا ۖ قَالَ أَتَسْتَبْدِلُونَ الَّذِي هُوَ أَدْنَىٰ بِالَّذِي هُوَ خَيْرٌ ۚ اهْبِطُوا مِصْرًا فَإِنَّ لَكُم مَّا سَأَلْتُمْ ۗ وَضُرِبَتْ عَلَيْهِمُ الذِّلَّةُ وَالْمَسْكَنَةُ وَبَاءُوا بِغَضَبٍ مِّنَ اللَّهِ ۗ ذَٰلِكَ بِأَنَّهُمْ كَانُوا يَكْفُرُونَ بِآيَاتِ اللَّهِ وَيَقْتُلُونَ النَّبِيِّينَ بِغَيْرِ الْحَقِّ ۗ ذَٰلِكَ بِمَا عَصَوا وَّكَانُوا يَعْتَدُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອພວກເຈົ້າກ່າວວ່າ: 'ໂອ້ ມູຊາ, ພວກເຮົາບໍ່ສາມາດອົດທົນກັບອາຫານຊະນິດດຽວໄດ້. ດັ່ງນັ້ນ, ຈົ່ງຂໍພຣະຜູ້ເປັນເຈົ້າຂອງເຈົ້າໃຫ້ເອົາສິ່ງທີ່ແຜ່ນດິນປູກອອກມາໃຫ້ພວກເຮົາ, ເຊັ່ນ: ຜັກ, ໝາກແຕງ, ກະທຽມ, ຖົ່ວ, ແລະຫົວຫອມ.' ລາວໄດ້ກ່າວວ່າ: 'ພວກເຈົ້າຈະແລກປ່ຽນສິ່ງທີ່ດີກວ່າດ້ວຍສິ່ງທີ່ຕໍ່າກວ່າບໍ? ຈົ່ງລົງໄປໃນເມືອງໃດກໍໄດ້, ແລະພວກເຈົ້າຈະໄດ້ສິ່ງທີ່ພວກເຈົ້າຂໍ.' ແລະຄວາມອັບອາຍແລະຄວາມທຸກຍາກໄດ້ຖືກກຳນົດໃຫ້ພວກເຂົາ, ແລະພວກເຂົາໄດ້ຮັບຄວາມໂກດແຄ້ນຈາກອັລລໍຮ໌. ນັ້ນເປັນເພາະວ່າພວກເຂົາປະຕິເສດອາຍະຕ່າງໆຂອງອັລລໍຮ໌ແລະຂ້າສາດສະດາโดยບໍ່ຍຸດຕິທຳ. ນັ້ນເປັນເພາະວ່າພວກເຂົາບໍ່ເຊື່ອຟັງແລະລະເມີດ.", english: "And [recall] when you said, 'O Moses, we can never endure one [kind of] food. So call upon your Lord to bring forth for us from the earth its green herbs and its cucumbers and its garlic and its lentils and its onions.' [Moses] said, 'Would you exchange what is better for what is less? Go into [any] settlement and indeed, you will have what you have asked.' And they were covered with humiliation and poverty and returned with anger from Allah [upon them]. That was because they [repeatedly] disbelieved in the signs of Allah and killed the prophets without right. That was because they disobeyed and were [habitually] transgressing." },
  { number: "2:62", arabic: "إِنَّ الَّذِينَ آمَنُوا وَالَّذِينَ هَادُوا وَالنَّصَارَىٰ وَالصَّابِئِينَ مَنْ آمَنَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ وَعَمِلَ صَالِحًا فَلَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ", lao: "ແທ້ຈິງ, ຜູ້ທີ່ເຊື່ອ, ແລະຜູ້ທີ່ເປັນຊາວຢິວ, ແລະຊາວຄຣິດ, ແລະຊາວຊາບີອິນ, ຜູ້ໃດທີ່ເຊື່ອໃນອັລລໍຮ໌ແລະວັນສຸດທ້າຍແລະເຮັດຄວາມດີ, ພວກເຂົາຈະໄດ້ຮັບລາງວັນຈາກພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຂົາ, ແລະຈະບໍ່ມີຄວາມຢ້ານກົວໃດໆຕໍ່ພວກເຂົາ ແລະພວກເຂົາຈະບໍ່ໂສກເສົ້າ.", english: "Indeed, those who believed and those who were Jews or Christians or Sabeans [before Prophet Muhammad] - those [among them] who believed in Allah and the Last Day and did righteousness - will have their reward with their Lord, and no fear will there be concerning them, nor will they grieve." },
  { number: "2:63", arabic: "وَإِذْ أَخَذْنَا مِيثَاقَكُمْ وَرَفَعْنَا فَوْقَكُمُ الطُّورَ خُذُوا مَا آتَيْنَاكُم بِقُوَّةٍ وَاذْكُرُوا مَا فِيهِ لَعَلَّكُمْ تَتَّقُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອເຮົາໄດ້ເອົາສັນຍາຈາກພວກເຈົ້າແລະຍົກພູເຂົາຂຶ້ນເໜືອພວກເຈົ້າ, [ໂດຍກ່າວວ່າ]: 'ຈົ່ງຍຶດໝັ້ນໃນສິ່ງທີ່ເຮົາໄດ້ໃຫ້ແກ່ພວກເຈົ້າຢ່າງເຂັ້ມແຂງແລະຈົ່ງລະນຶກເຖິງສິ່ງທີ່ຢູ່ໃນນັ້ນ, ເພື່ອວ່າພວກເຈົ້າຈະໄດ້ມີຄວາມຢຳເກງ.'", english: "And [recall] when We took your covenant, [O Children of Israel, to abide by the Torah] and We raised over you the mount, [saying], 'Take what We have given you with determination and remember what is in it that perhaps you may become righteous.'" },
  { number: "2:64", arabic: "ثُمَّ تَوَلَّيْتُم مِّن بَعْدِ ذَٰلِكَ ۖ فَلَوْلَا فَضْلُ اللَّهِ عَلَيْكُمْ وَرَحْمَتُهُ لَكُنتُم مِّنَ الْخَاسِرِينَ", lao: "ຫຼັງຈາກນັ້ນ, ພວກເຈົ້າໄດ້ຫັນໜີ. ແລະຖ້າບໍ່ແມ່ນຄວາມໂປດປານແລະຄວາມເມດຕາຂອງອັລລໍຮ໌ຕໍ່ພວກເຈົ້າ, ພວກເຈົ້າກໍຈະກາຍເປັນผู้ທີ່ຂາດທຶນ.", english: "Then you turned away after that. And if not for the favor of Allah upon you and His mercy, you would have been among the losers." },
  { number: "2:65", arabic: "وَلَقَدْ عَلِمْتُمُ الَّذِينَ اعْتَدَوْا مِنكُمْ فِي السَّبْتِ فَقُلْنَا لَهُمْ كُونُوا قِرَدَةً خَاسِئِينَ", lao: "ແລະແນ່ນອນ, ພວກເຈົ້າຮູ້ຈັກຜູ້ທີ່ລະເມີດໃນວັນສະບາໂຕໃນກຸ່ມຂອງພວກເຈົ້າ, ແລ້ວເຮົາໄດ້ກ່າວແກ່ພວກເຂົາວ່າ: 'ຈົ່ງເປັນລີງที่ຖືກຂັບໄລ่.'", english: "And you had already known about those who transgressed among you concerning the sabbath, and We said to them, 'Be apes, despised.'" },
  { number: "2:66", arabic: "فَجَعَلْنَاهَا نَكَالًا لِّمَا بَيْنَ يَدَيْهَا وَمَا خَلْفَهَا وَمَوْعِظَةً لِّلْمُتَّقِينَ", lao: "ແລ້ວເຮົາໄດ້ເຮັດໃຫ້มันເປັນຕົວຢ່າງສຳລັບຄົນໃນຍຸກນັ້ນແລະຄົນລຸ້ນຫຼັງ, ແລະເປັນຄຳຕັກເຕືອນສຳລັບผู้ທີ່ຢຳເກງ.", english: "And We made it a deterrent punishment for those who were present and those who succeeded [them] and a lesson for those who fear Allah." },
  { number: "2:67", arabic: "وَإِذْ قَالَ مُوسَىٰ لِقَوْمِهِ إِنَّ اللَّهَ يَأْمُرُكُمْ أَن تَذْبَحُوا بَقَرَةً ۖ قَالُوا أَتَتَّخِذُنَا هُزُوًا ۖ قَالَ أَعُوذُ بِاللَّهِ أَنْ أَكُونَ مِنَ الْجَاهِلِينَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອມູຊາໄດ້ກ່າວແກ່ປະຊາຊົນຂອງລາວວ່າ: 'ແທ້ຈິງ, ອັລລໍຮ໌ສັ່ງໃຫ້ພວກເຈົ້າຂ້າງົວແມ່.' ພວກເຂົາກ່າວວ່າ: 'ເຈົ້າຈະເຍາະເຍີ້ຍພວກເຮົາບໍ?' ລາວໄດ້ກ່າວວ່າ: 'ຂ້ອຍຂໍຄວາມຄຸ້ມຄອງຈາກອັລລໍຮ໌ໃຫ້ພົ້ນຈາກການເປັນຄົນໂງ່.'", english: "And [recall] when Moses said to his people, 'Indeed, Allah commands you to slaughter a cow.' They said, 'Do you take us in ridicule?' He said, 'I seek refuge in Allah from being among the ignorant.'" },
  { number: "2:68", arabic: "قَالُوا ادْعُ لَنَا رَبَّكَ يُبَيِّن لَّنَا مَا هِيَ ۚ قَالَ إِنَّهُ يَقُولُ إِنَّهَا بَقَرَةٌ لَّا فَارِضٌ وَلَا بِكْرٌ عَوَانٌ بَيْنَ ذَٰلِكَ ۖ فَافْعَلُوا مَا تُؤْمَرُونَ", lao: "ພວກເຂົາກ່າວວ່າ: 'ຈົ່ງຂໍພຣະຜູ້ເປັນເຈົ້າຂອງເຈົ້າໃຫ້ອະທິບາຍໃຫ້ພວກເຮົາຮູ້ວ່າມັນເປັນແນວໃດ.' ລາວໄດ້ກ່າວວ່າ: 'ພຣະອົງກ່າວວ່າມັນເປັນງົວທີ່ບໍ່ແກ່ແລະບໍ່ອ່ອນ, ຢູ່ລະຫວ່າງກາງ. ດັ່ງນັ້ນ, ຈົ່ງເຮັດຕາມທີ່ພວກເຈົ້າຖືກສັ່ງ.'", english: "They said, 'Call upon your Lord to make clear to us what it is.' [Moses] said, '[Allah] says, 'It is a cow which is neither old nor virgin, but median between that,' so do what you are commanded.'" },
  { number: "2:69", arabic: "قَالُوا ادْعُ لَنَا رَبَّكَ يُبَيِّن لَّنَا مَا لَوْنُهَا ۚ قَالَ إِنَّهُ يَقُولُ إِنَّهَا بَقَرَةٌ صَفْرَاءُ فَاقِعٌ لَّوْنُهَا تَسُرُّ النَّاظِرِينَ", lao: "ພວກເຂົາກ່າວວ່າ: 'ຈົ່ງຂໍພຣະຜູ້ເປັນເຈົ້າຂອງເຈົ້າໃຫ້ອະທິບາຍໃຫ້ພວກເຮົາຮູ້ວ່າສີຂອງມັນເປັນແນວໃດ.' ລາວໄດ້ກ່າວວ່າ: 'ພຣະອົງກ່າວວ່າມັນເປັນງົວສີເຫຼືອງສົດໃສ, ສີຂອງມັນເຮັດໃຫ້ผู้ເບິ່ງມີຄວາມສຸກ.'", english: "They said, 'Call upon your Lord to show us what is its color.' He said, 'He says, 'It is a yellow cow, bright in color - pleasing to the observers.''" },
  { number: "2:70", arabic: "قَالُوا ادْعُ لَنَا رَبَّكَ يُبَيِّن لَّنَا مَا هِيَ إِنَّ الْبَقَرَ تَشَابَهَ عَلَيْنَا وَإِنَّا إِن شَاءَ اللَّهُ لَمُهْتَدُونَ", lao: "ພວກເຂົາກ່າວວ່າ: 'ຈົ່ງຂໍພຣະຜູ້ເປັນເຈົ້າຂອງເຈົ້າໃຫ້ອະທິບາຍໃຫ້ພວກເຮົາຮູ້ວ່າມັນເປັນແນວໃດ, ເພາະງົວເບິ່ງຄືກັນສຳລັບພວກເຮົາ. ແລະແທ້ຈິງ, ຖ້າອັລລໍຮ໌ປະສົງ, ພວກເຮົາຈະໄດ້ຮັບການຊີ້ແນະ.'", english: "They said, 'Call upon your Lord to make clear to us what it is. Indeed, [all] cows look alike to us. And indeed we, if Allah wills, will be guided.'" },
  { number: "2:71", arabic: "قَالَ إِنَّهُ يَقُولُ إِنَّهَا بَقَرَةٌ لَّا ذَلُولٌ تُثِيرُ الْأَرْضَ وَلَا تَسْقِي الْحَرْثَ مُسَلَّمَةٌ لَّا شِيَةَ فِيهَا ۚ قَالُوا الْآنَ جِئْتَ بِالْحَقِّ ۚ فَذَبَحُوهَا وَمَا كَادُوا يَفْعَلُونَ", lao: "ລາວໄດ້ກ່າວວ່າ: 'ພຣະອົງກ່າວວ່າມັນເປັນງົວທີ່ບໍ່ໄດ້ຖືກໃຊ້ໄຖນາແລະບໍ່ໄດ້ຖືກໃຊ້ຫົດນ້ຳໄຮ່ນາ, ສົມບູນແບບບໍ່ມີຕຳหนิ.' ພວກເຂົາກ່າວວ່າ: 'ຕອນນີ້ເຈົ້າໄດ້ນຳຄວາມຈິງມາແລ້ວ.' ແລ້ວພວກເຂົາກໍຂ້າມັນ, ແຕ່ເກືອບຈະບໍ່ໄດ້ເຮັດ.", english: "He said, 'He says, 'It is a cow neither trained to plow the earth nor to water the field, sound, lacking any blemish.' ' They said, 'Now you have come with the truth.' So they slaughtered it, but they could hardly do it." },
  { number: "2:72", arabic: "وَإِذْ قَتَلْتُمْ نَفْسًا فَادَّارَأْتُمْ فِيهَا ۖ وَاللَّهُ مُخْرِجٌ مَّا كُنتُمْ تَكْتُمُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອພວກເຈົ້າໄດ້ຂ້າຄົນຜູ້ໜຶ່ງແລ້ວຖຽງກັນກ່ຽວກັບມັນ, ແຕ່ອັລລໍຮ໌ຈະເປີດເຜີຍສິ່ງທີ່ພວກເຈົ້າປິດບັງ.", english: "And [recall] when you slew a man and disputed over it, but Allah was to bring out that which you were concealing." },
  { number: "2:73", arabic: "فَقُلْنَا اضْرِبُوهُ بِبَعْضِهَا ۚ كَذَٰلِكَ يُحْيِي اللَّهُ الْمَوْتَىٰ وَيُرِيكُمْ آيَاتِهِ لَعَلَّكُمْ تَعْقِلُونَ", lao: "ແລ້ວເຮົາໄດ້ກ່າວວ່າ: 'ຈົ່ງຕີລາວດ້ວຍສ່ວນໜຶ່ງຂອງມັນ.' ເຊັ່ນນັ້ນແຫຼະ ອັລລໍຮ໌ຈະເຮັດໃຫ້ຄົນຕາຍມີຊີວິດຂຶ້ນມາແລະສະແດງອາຍະຕ່າງໆຂອງພຣະອົງໃຫ້ພວກເຈົ້າເຫັນ, ເພື່ອວ່າພວກເຈົ້າຈະໄດ້ຄິດ.", english: "So, We said, 'Strike the slain man with part of it.' Thus does Allah bring the dead to life, and He shows you His signs that you might reason." },
  { number: "2:74", arabic: "ثُمَّ قَسَتْ قُلُوبُكُم مِّن بَعْدِ ذَٰلِكَ فَهِيَ كَالْحِجَارَةِ أَوْ أَشَدُّ قَسْوَةً ۚ وَإِنَّ مِنَ الْحِجَارَةِ لَمَا يَتَفَجَّرُ مِنْهُ الْأَنْهَارُ ۚ وَإِنَّ مِنْهَا لَمَا يَشَّقَّقُ فَيَخْرُجُ مِنْهُ الْمَاءُ ۚ وَإِنَّ مِنْهَا لَمَا يَهْبِطُ مِنْ خَشْيَةِ اللَّهِ ۗ وَمَا اللَّهُ بِغَافِلٍ عَمَّا تَعْمَلُونَ", lao: "ຫຼັງຈາກນັ້ນ, ຫົວໃຈຂອງພວກເຈົ້າກໍແຂງກະດ້າງ, ເໝືອນຫີນຫຼືແຂງກວ່າ. ແລະແທ້ຈິງ, ໃນບັນດາຫີນມີບາງກ້ອນທີ່ແມ່ນ້ຳໄຫຼອອກມາ. ແລະມີບາງກ້ອນທີ່ແຕກອອກແລ້ວນ້ຳກໍໄຫຼອອກມາ. ແລະມີບາງກ້ອນທີ່ຕົກລົງມາເພາະຢ້ານອັລລໍຮ໌. ແລະອັລລໍຮ໌ບໍ່ໄດ້ລະເລີຍສິ່ງທີ່ພວກເຈົ້າເຮັດ.", english: "Then your hearts became hardened after that, being like stones or even harder. For indeed, there are stones from which rivers gush forth, and there are some of them that split open and water comes out, and there are some of them that fall down for fear of Allah. And Allah is not unaware of what you do." },
  { number: "2:75", arabic: "أَفَتَطْمَعُونَ أَن يُؤْمِنُوا لَكُمْ وَقَدْ كَانَ فَرِوقٌ مِّنْهُمْ يَسْمَعُونَ كَلَامَ اللَّهِ ثُمَّ يُحَرِّفُونَهُ مِن بَعْدِ مَا عَقَلُوهُ وَهُمْ يَعْلَمُونَ", lao: "ພວກເຈົ້າຫວັງວ່າພວກເຂົາຈະເຊື່ອໃນພວກເຈົ້າບໍ, ທັງທີ່ກຸ່ມໜຶ່ງໃນພວກເຂົາເຄີຍໄດ້ຍິນຄຳເວົ້າຂອງອັລລໍຮ໌ແລ້ວບິດເບືອນມັນຫຼັງຈາກທີ່ໄດ້ເຂົ້າໃຈมัน, ທັງที่ພວກເຂົາຮູ້?", english: "Do you covet [the hope, O believers], that they would believe for you while a party of them used to hear the words of Allah and then distort the Torah after they had understood it while they were knowing?" },
  { number: "2:76", arabic: "وَإِذَا لَقُوا الَّذِينَ آمَنُوا قَالُوا آمَنَّا وَإِذَا خَلَا بَعْضُهُمْ إِلَىٰ بَعْضٍ قَالُوا أَتُحَدِّثُونَهُم بِمَا فَتَحَ اللَّهُ عَلَيْكُمْ لِيُحَاجُّوكُم بِهِ عِندَ رَبِّكُمْ ۚ أَفَلَا تَعْقِلُونَ", lao: "ແລະເມື່ອພວກເຂົາພົບກັບຜູ້ທີ່ເຊື່ອ, ພວກເຂົາກ່າວວ່າ: 'ພວກເຮົາເຊື່ອແລ້ວ.' ແຕ່ເມື່ອພວກເຂົາຢູ່ຕາມລຳພັງ, ພວກເຂົາກ່າວວ່າ: 'ພວກເຈົ້າຈະບອກພວກເຂົາໃນສິ່ງທີ່ອັລລໍຮ໌ໄດ້ເປີດເຜີຍໃຫ້ພວກເຈົ້າຮູ້ບໍ, ເພື່ອພວກເຂົາຈະໄດ້ໃຊ້ເປັນຫຼັກຖານຕໍ່ຕ້ານພວກເຈົ້າຕໍ່ໜ້າພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຈົ້າ? ພວກເຈົ້າບໍ່ຄິດບໍ?'", english: "And when they meet those who believe, they say, 'We have believed'; but when they are alone with one another, they say, 'Do you talk to them about what Allah has revealed to you so they can argue with you about it before your Lord?' Then will you not reason?" },
  { number: "2:77", arabic: "أَوَلَا يَعْلَمُونَ أَنَّ اللَّهَ يَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ", lao: "ພວກເຂົາບໍ່ຮູ້ບໍວ່າອັລລໍຮ໌ຮູ້ສິ່ງที่พวกเขาປິດບັງແລະສິ່ງที่พวกเขาເປີດເຜີຍ?", english: "But do they not know that Allah knows what they conceal and what they declare?" },
  { number: "2.78", arabic: "وَمِنْهُمْ أُمِّيُّونَ لَا يَعْلَمُونَ الْكِتَابَ إِلَّا أَمَانِيَّ وَإِنْ هُمْ إِلَّا يَظُنُّونَ", lao: "ແລະໃນກຸ່ມຂອງພວກເຂົາມີຜູ້ທີ່ບໍ່ຮູ້ໜັງສື, ພວກເຂົາບໍ່ຮູ້ຄຳພີຍົກເວັ້ນຄວາມປາດຖະຫນາ, ແລະພວກເຂົາເປັນພຽງການຄາດເດົາ.", english: "And among them are unlettered ones who do not know the Scripture except in wishful thinking, but they are only assuming." },
  { number: "2:79", arabic: "فَوَيْلٌ لِّلَّذِينَ يَكْتُبُونَ الْكِتَابَ بِأَيْدِيهِمْ ثُمَّ يَقُولُونَ هَٰذَا مِنْ عِندِ اللَّهِ لِيَشْتَرُوا بِهِ ثَمَنًا قَلِيلًا ۖ فَوَيْلٌ لَّهُم مِّمَّا كَتَبَتْ أَيْدِيهِمْ وَوَيْلٌ لَّهُم مِّمَّا يَكْسِبُونَ", lao: "ດັ່ງນັ້ນ, ຄວາມວິບັດຈະເກີດແກ່ຜູ້ที่ຂຽນຄຳພີດ້ວຍມືຂອງພວກເຂົາເອງແລ້ວກ່າວວ່າ: 'ນີ້ມາຈາກອັລລໍຮ໌' ເພື່ອແລກປ່ຽນมันດ້ວຍລາຄາທີ່ຕໍ່າຕ້ອຍ. ດັ່ງນັ້ນ, ຄວາມວິບັດຈະເກີດແກ່ພວກເຂົາຈາກສິ່ງที่ມືຂອງພວກເຂົາໄດ້ຂຽນ, ແລະຄວາມວິບັດຈະເກີດແກ່ພວກເຂົາຈາກສິ່ງที่พวกເຂົາໄດ້ຮັບ.", english: "So woe to those who write the 'scripture' with their own hands, then say, 'This is from Allah,' in order to exchange it for a small price. Woe to them for what their hands have written and woe to them for what they earn." },
  { number: "2:80", arabic: "وَقَالُوا لَن تَمَسَّنَا النَّارُ إِلَّا أَيَّامًا مَّعْدُودَةً ۚ قُلْ أَتَّخَذْتُمْ عِندَ اللَّهِ عَهْدًا فَلَن يُخْلِفَ اللَّهُ عَهْدَهُ ۖ أَمْ تَقُولُونَ عَلَى اللَّهِ مَا لَا تَعْلَمُونَ", lao: "ແລະພວກເຂົາກ່າວວ່າ: 'ໄຟນະລົກຈະບໍ່ແຕະຕ້ອງພວກເຮົາເວັ້ນແຕ່ສອງສາມວັນ.' ຈົ່ງກ່າວວ່າ: 'ພວກເຈົ້າໄດ້ຮັບສັນຍາຈາກອັລລໍຮ໌ບໍ? ດັ່ງນັ້ນ, ອັລລໍຮ໌ຈະບໍ່ລະເມີດສັນຍາຂອງພຣະອົງ. ຫຼືພວກເຈົ້າເວົ້າກ່ຽວກັບອັລລໍຮ໌ในສິ່ງທີ່ພວກເຈົ້າບໍ່ຮູ້?'", english: "And they say, 'Never will the Fire touch us, except for a few days.' Say, 'Have you taken a covenant from Allah? For Allah will never break His covenant. Or do you say about Allah that which you do not know?'" }
];

export default function SurahAlBaqarahView({ goBack }: SurahAlBaqarahViewProps) {
  return (
    <div className="flex flex-col">
      <ViewHeader title="ສູຣໍ ອັລບາກໍຣໍ" onBack={goBack} />
      <main className="p-4">
        {verses.map(v => <VerseCard key={v.number} {...v} />)}
        <SummaryCard title="ສະຫຼຸບ">
          ອາຍັດເຫຼົ່ານີ້ອະທິບາຍເຖິງກຸ່ມຄົນຕ່າງໆ: ຜູ້ສັດທາ, ຜູ້ປະຕິເສດ, ແລະ ຜູ້ໜ້າຊື່ໃຈຄົດ. ມັນໄດ້ທ້າທາຍຜູ້ທີ່ສົງໄສໃນຄຳພີກຸຣອານ, ໄດ້ສັນຍາລາງວັນແກ່ผู้ທີ່ເຊື່ອ, ແລະໄດ້ຢືນຢັນເຖິງອຳນາດຂອງອັນລໍຫ໌ໃນການສ້າງຈັກກະວານ ແລະ ມະນຸດ.
        </SummaryCard>
      </main>
    </div>
  );
}
