'use client';
import React, { useState } from 'react';
import ViewHeader from '@/components/shared/ViewHeader';
import VerseCard from '@/components/shared/VerseCard';
import SummaryCard from '@/components/shared/SummaryCard';
import { Input } from '@/components/ui/input';

interface SurahAalImranViewProps {
  goBack: () => void;
}

const verses = [
  { number: "3:1", arabic: "الم", lao: "ອາລີຟ ລາມ ມີມ.", english: "Alif, Lam, Meem." },
  { number: "3:2", arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ", lao: "ອັນລໍ, ບໍ່ມີພຣະເຈົ້າອື່ນໃດນອກຈາກພຣະອົງ, ຜູ້ຊົງມີຊີວິດ, ຜູ້ຊົງດຳລົງຢູ່ສະເໝີ.", english: "Allah - there is no deity except Him, the Ever-Living, the Self-Sustaining." },
  { number: "3:3", arabic: "نَزَّلَ عَلَيْكَ الْكِتَابَ بِالْحَقِّ مُصَدِّقًا لِّمَا بَيْنَ يَدَيْهِ وَأَنزَلَ التَّوْرَاةَ وَالْإِنجِيلَ", lao: "ພຣະອົງໄດ້ຊົງປະທານຄຳພີລົງມາໃຫ້ເຈົ້າດ້ວຍຄວາມຈິງ, ເພື່ອຢັ້ງຢືນສິ່ງທີ່ຢູ່ກ່ອນໜ້ານັ້ນ. ແລະ ພຣະອົງໄດ້ຊົງປະທານຄຳພີເຕົາຣອດ ແລະ ຄຳພີອິນຈີລລົງມາ.", english: "He has sent down upon you, [O Muhammad], the Book in truth, confirming what was before it. And He revealed the Torah and the Gospel." },
  { number: "3:4", arabic: "مِن قَبْلُ هُدًى لِّلنَّاسِ وَأَنزَلَ الْفُرْقَانَ ۗ إِنَّ الَّذِينَ كَفَرُوا بِآيَاتِ اللَّهِ لَهُمْ عَذَابٌ شَدِيدٌ ۗ وَاللَّهُ عَزِيزٌ ذُو انتِقَامٍ", lao: "ກ່ອນໜ້ານີ້ ເພື່ອເປັນທາງນຳແກ່ມະນຸດຊາດ, ແລະ ພຣະອົງໄດ້ຊົງປະທານອັລ-ຟຸຣກອນ (ສິ່ງທີ່ຈຳແນກ) ລົງມາ. ແທ້ຈິງ, ບັນດາຜູ້ທີ່ປະຕິເສດສັນຍານຂອງອັນລໍ, ພວກເຂົາຈະໄດ້ຮັບການລົງໂທດຢ່າງໜັກໜ່ວງ. ແລະ ອັນລໍເປັນຜູ້ຊົງອຳນາດ, ເຈົ້າແຫ່ງການຕອບແທນ.", english: "Before, as guidance for the people. And He revealed the Qur'an. Indeed, those who disbelieve in the verses of Allah will have a severe punishment, and Allah is exalted in Might, the Owner of Retribution." },
  { number: "3.5", arabic: "إِنَّ اللَّهَ لَا يَخْفَىٰ عَلَيْهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ", lao: "ແທ້ຈິງ, ບໍ່ມີສິ່ງໃດໃນແຜ່ນດິນ ແລະ ໃນຊັ້ນຟ້າທີ່ຈະซ่อนเร้นຈາກອັນລໍໄດ້.", english: "Indeed, from Allah nothing is hidden in the earth nor in the heaven." },
  { number: "3:6", arabic: "هُوَ الَّذِي يُصَوِّرُكُمْ فِي الْأَرْحَامِ كَيْفَ يَشَاءُ ۚ لَا إِلَٰهَ إِلَّا هُوَ الْعَzِيزُ الْحَكِيمُ", lao: "ພຣະອົງຄືຜູ້ທີ່ສ້າງຮູບຮ່າງຂອງພວກເຈົ້າໃນມົດລູກຕາມທີ່ພຣະອົງຊົງປະສົງ. ບໍ່ມີພຣະເຈົ້າອື່ນໃດນອກຈາກພຣະອົງ, ຜູ້ຊົງອຳນາດ, ຜູ້ຊົງມີປັນຍາ.", english: "It is He who forms you in the wombs however He wills. There is no deity except Him, the Exalted in Might, the Wise." },
  { number: "3:7", arabic: "هُوَ الَّذِي أَنزَلَ عَلَيْكَ الْكِتَابَ مِنْهُ آيَاتٌ مُّحْكَمَاتٌ هُنَّ أُمُّ الْكِتَابِ وَأُخَرُ مُتَشَابِهَاتٌ ۖ فَأَمَّا الَّذِينَ فِي قُلُوبِهِمْ زَيْغٌ فَيَتَّبِعُونَ مَا تَشَابَهَ مِنْهُ ابْتِغَاءَ الْفِتْنَةِ وَابْتِغَاءَ تَأْوِيلِهِ ۗ وَمَا يَعْلَمُ تَأْوِيلَهُ إِلَّا اللَّهُ ۗ وَالرَّاسِخُونَ فِي الْعِلْمِ يَقُولُونَ آمَنَّا بِهِ كُلٌّ مِّنْ عِندِ رَبِّنَا ۗ وَمَا يَذَّكَّرُ إِلَّا أُولُو الْأَلْبَابِ", lao: "ພຣະອົງຄືຜູ້ທີ່ໄດ້ຊົງປະທານຄຳພີລົງມາໃຫ້ເຈົ້າ. ໃນນັ້ນມີອາຍະຕ່າງໆທີ່ຊັດเจน, ເຊິ່ງເປັນແມ່ບົດຂອງຄຳພີ, ແລະ ມີອາຍະຕ່າງໆທີ່ບໍ່ຊັດเจน. ສ່ວນຜູ້ທີ່ໃນໃຈຂອງພວກເຂົາມີຄວາມບິດເບືອນ, ພວກເຂົາຈະຕິດຕາມສິ່ງທີ່ບໍ່ຊັດเจน, ເພື່ອສະແຫວງຫາຄວາມວຸ້ນວາຍ ແລະ ສະແຫວງຫາການຕີຄວາມໝາຍຂອງມັນ. ແລະ ບໍ່ມີຜູ້ໃດຮູ້ການຕີຄວາມໝາຍຂອງມັນນອກຈາກອັນລໍ. ແລະ ຜູ້ທີ່ໝັ້ນຄົງໃນຄວາມຮູ້ຈະກ່າວວ່າ: 'ພວກເຮົາເຊື່ອໃນມັນ, ທັງໝົດມາຈາກພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ.' ແລະ ບໍ່ມີຜູ້ໃດທີ່ຈະລະນຶກນອກຈາກຜູ້ທີ່ມີປັນຍາ.", english: "It is He who has sent down to you, [O Muhammad], the Book; in it are verses [that are] precise - they are the foundation of the Book - and others unspecific. As for those in whose hearts is deviation [from truth], they will follow that of it which is unspecific, seeking discord and seeking an interpretation [suitable to them]. And no one knows its [true] interpretation except Allah. But those firm in knowledge say, 'We believe in it. All [of it] is from our Lord.' And no one will be reminded except those of understanding." },
  { number: "3:8", arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ الْوَهَّابُ", lao: "ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ, ຂໍຢ່າເຮັດໃຫ້ໃຈຂອງພວກເຮົາບິດເບືອນຫຼັງຈາກທີ່ພຣະອົງໄດ້ຊົງນຳພາພວກເຮົາ, ແລະ ຂໍໃຫ້ປະທານຄວາມເມດຕາຈາກພຣະອົງໃຫ້ແກ່ພວກເຮົາ. ແທ້ຈິງ, ພຣະອົງຄືຜູ້ຊົງປະທານ.", english: "'Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.'" },
  { number: "3:9", arabic: "رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ ۚ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ", lao: "ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ, ແທ້ຈິງພຣະອົງຈະຊົງຮວບຮວມມະນຸດຊາດໃນວັນທີ່ບໍ່ມີຄວາມສົງໄສ. ແທ້ຈິງ, ອັນລໍບໍ່ຊົງຜິດສັນຍາ.", english: "'Our Lord, surely You will gather the people for a Day about which there is no doubt. Indeed, Allah does not fail in His promise.'" },
  { number: "3:10", arabic: "إِنَّ الَّذِينَ كَفَرُوا لَن تُغْنِيَ عَنْهُمْ أَمْوَالُهُمْ وَلَا أَوْلَادُهُم مِّنَ اللَّهِ شَيْئًا ۖ وَأُولَٰئِكَ هُمْ وَقُودُ النَّارِ", lao: "ແທ້ຈິງ, ບັນດາຜູ້ທີ່ປະຕິເສດ, ຊັບສິນຂອງພວກເຂົາ ແລະ ລູກຫຼານຂອງພວກເຂົາຈະບໍ່ສາມາດຊ່ວຍພວກເຂົາຈາກອັນລໍໄດ້ເລີຍ. ແລະ ພວກເຂົາຄືເຊື້ອໄຟຂອງນະລົກ.", english: "Indeed, those who disbelieve - never will their wealth or their children avail them against Allah at all. And it is they who are fuel for the Fire." },
  { number: "3:11", arabic: "كَدَأْبِ آلِ فِرْعَوْنَ وَالَّذِينَ مِن قَبْلِهِمْ ۚ كَذَّبُوا بِآيَاتِنَا فَأَخَذَهُمُ اللَّهُ بِذُنُوبِهِمْ ۗ وَاللَّهُ شَدِيدُ الْعِقَابِ", lao: "ເໝືອນດັ່ງສະພາບຂອງພรรคພວກຟີຣະໂອນ ແລະ ບັນດາຜູ້ທີ່ຢູ່ກ່ອນໜ້າພວກເຂົາ. ພວກເຂົາໄດ້ປະຕິເສດສັນຍານຂອງພວກເຮົາ, ດັ່ງນັ້ນອັນລໍຈຶ່ງໄດ້ລົງໂທດພວກເຂົາຍ້ອນບາບຂອງພວກເຂົາ. ແລະ ອັນລໍເປັນຜູ້ຊົງລົງໂທດຢ່າງໜັກໜ່ວງ.", english: "Like the behavior of the people of Pharaoh and those before them. They denied Our signs, so Allah seized them for their sins. And Allah is severe in penalty." },
  { number: "3:12", arabic: "قُل لِّلَّذِينَ كَفَرُوا سَتُغْلَبُونَ وَتُحْشَرُونَ إِلَىٰ جَهَنَّمَ ۚ وَبِئْسَ الْمِهَادُ", lao: "ຈົ່ງກ່າວແກ່ບັນດາຜູ້ທີ່ປະຕິເສດວ່າ: 'ພວກເຈົ້າຈະຖືກເອົາຊະນະ ແລະ ຈະຖືກຮວບຮວມໄປສູ່ນະລົກ, ແລະ ມັນເປັນທີ່พำนักທີ່ຊົ່ວຊ້າ.'", english: "Say to those who disbelieve, 'You will be overcome and gathered together to Hell, and wretched is the resting place.'" },
  { number: "3:13", arabic: "قَدْ كَانَ لَكُمْ آيَةٌ فِي فِئَتَيْنِ الْتَقَتَا ۖ فِئَةٌ تُقَاتِلُ فِي سَبِيلِ اللَّهِ وَأُخْرَىٰ كَافِرَةٌ يَرَوْنَهُم مِّثْلَيْهِمْ رَأْيَ الْعَيْنِ ۚ وَاللَّهُ يُؤَيِّدُ بِنَصْرِهِ مَن يَشَاءُ ۗ إِنَّ فِي ذَٰلِكَ لَعِبْرَةً لِّأُولِي الْأَبْصَارِ", lao: "ແນ່ນອນ, ມີສັນຍານໜຶ່ງສຳລັບພວກເຈົ້າໃນສອງກຸ່ມທີ່ໄດ້ພົບກັນ: ກຸ່ມໜຶ່ງຕໍ່ສູ້ໃນທາງຂອງອັນລໍ ແລະ ອີກກຸ່ມໜຶ່ງເປັນผู้ปฏิเสธ, ພວກເຂົາເຫັນອີກฝ่ายໜຶ່ງເປັນສອງເທົ່າດ້ວຍຕາຂອງຕົນ. ແລະ ອັນລໍຊົງສະໜັບສະໜູນผู้ที่พระองค์ทรงประสงค์ด้วยความช่วยเหลือของพระองค์. ແທ້ຈິງໃນນັ້ນມີບົດຮຽນສຳລັບຜູ້ທີ່ມີສາຍຕາ.", english: "Already there has been for you a sign in the two armies which met - one fighting in the cause of Allah and another of disbelievers. They saw them [to be] twice their [own] number by [their] eyesight. But Allah supports with His victory whom He wills. Indeed in that is a lesson for those of vision." },
  { number: "3:14", arabic: "زُيِّنَ لِلنَّاسِ حُبُّ الشَّهَوَاتِ مِنَ النِّسَاءِ وَالْبَنِينَ وَالْقَنَاطِيرِ الْمُقَنطَرَةِ مِنَ الذَّهَبِ وَالْفِضَّةِ وَالْخَيْلِ الْمُسَوَّمَةِ وَالْأَنْعَامِ وَالْحَرْثِ ۗ ذَٰلِكَ مَتَاعُ الْحَيَاةِ الدُّنْيَا ۖ وَاللَّهُ عِندَهُ حُسْنُ الْمَآبِ", lao: "ຄວາມຮັກໃນສິ່ງທີ່ປາຖະໜາໄດ້ຖືກປະດັບປະດາให้สวยงามແກ່ມະນຸດ - ຈາກผู้หญิง, ລູກຊາຍ, ຊັບສິນທີ່ສະສົມໄວ້ - ຄຳ, ເງິນ, ມ້າທີ່ຖືກเลี้ยงดูอย่างดี, ສັດລ້ຽງ, ແລະที่ดิน. ນັ້ນຄືຄວາມສຸກຂອງຊີວິດນີ້, ແຕ່ກັບອັນລໍຄືທີ່กลับທີ່ດີທີ່ສຸດ.", english: "Beautified for people is the love of that which they desire - of women and sons, heaped-up sums of gold and silver, fine branded horses, and cattle and tilled land. That is the enjoyment of worldly life, but Allah has with Him the best return." },
  { number: "3:15", arabic: "قُلْ أَؤُنَبِّئُكُم بِخَيْرٍ مِّن ذَٰلِكُمْ ۚ لِلَّذِينَ اتَّقَوْا عِندَ رَبِّهِمْ جَنَّاتٌ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ خَالِدِينَ فِيهَا وَأَزْوَاجٌ مُّطَهَّرَةٌ وَرِضْوَانٌ مِّنَ اللَّهِ ۗ وَاللَّهُ بَصِيرٌ بِالْعِبَادِ", lao: "ຈົ່ງກ່າວວ່າ: 'ຂ້ອຍจะบอกพวกเจ้าถึงสิ่งที่ดีกว่าນັ້ນບໍ?' ສຳລັບຜູ້ທີ່ຢຳເກງ, ກັບພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຂົາຄືสวนสวรรค์ที่มีแม่น้ำไหลผ่าน, ພວກເຂົາຈະอยู่ในนั้นตลอดไป, ແລະมีคู่ครองที่บริสุทธิ์, และความพอใจจากอัลลอฮ์. ແລະອັນລໍทรงเห็นบ่าวของพระองค์.", english: "Say, 'Shall I inform you of [something] better than that? For those who fear Allah will be gardens in the presence of their Lord beneath which rivers flow, wherein they will abide forever, and purified spouses and approval from Allah. And Allah is Seeing of [His] servants -'" },
  { number: "3:16", arabic: "الَّذِينَ يَقُولُونَ رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ", lao: "ຜູ້ທີ່ກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ, ແທ້ຈິງພວກເຮົາເຊື່ອแล้ว, ດັ່ງນັ້ນຂໍให้อภัยบาปของเราและปกป้องเราจากการลงโทษของไฟนรก.'", english: "Those who say, 'Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire,' -" },
  { number: "3:17", arabic: "الصَّابِرِينَ وَالصَّادِقِينَ وَالْقَانِتِينَ وَالْمُنفِقِينَ وَالْمُسْتَغْfِرِينَ بِالْأَسْحَارِ", lao: "ຜູ້ທີ່อดทน, ຜູ້ที่สัตย์จริง, ຜູ້ที่เชื่อฟัง, ຜູ້ที่บริจาค, และผู้ที่ขออภัยในยามเช้าตรู่.", english: "The patient, the true, the obedient, the spending [in the way of Allah], and those who seek forgiveness before dawn." },
  { number: "3:18", arabic: "شَهِدَ اللَّهُ أَنَّهُ لَا إِلَٰهَ إِلَّا هُوَ وَالْمَلَائِكَةُ وَأُولُو الْعِلْمِ قَائِمًا بِالْقِسْطِ ۚ لَا إِلَٰهَ إِلَّا هُوَ الْعَzِيزُ الْحَكِيمُ", lao: "ອັນລໍทรงเป็นพยานว่าไม่มีพระเจ้าอื่นใดนอกจากพระองค์, และทูตสวรรค์และผู้ที่มีความรู้ก็เป็นพยาน. [พระองค์ทรง] รักษาความยุติธรรม. ບໍ່ມີພຣະເຈົ້າອື່ນໃດນອກຈາກພຣະອົງ, ຜູ້ຊົງອຳນາດ, ຜູ້ຊົງມີປັນຍາ.", english: "Allah witnesses that there is no deity except Him, and [so do] the angels and those of knowledge - [that He is] maintaining [creation] in justice. There is no deity except Him, the Exalted in Might, the Wise." },
  { number: "3:19", arabic: "إِنَّ الدِّينَ عِندَ اللَّهِ الْإِسْلَامُ ۗ وَمَا اخْتَلَفَ الَّذِينَ أُوتُوا الْكِتَابَ إِلَّا مِن بَعْدِ مَا جَاءَهُمُ الْعِلْمُ بَغْيًا بَيْنَهُمْ ۗ وَمَن يَكْfُرْ بِآيَاتِ اللَّهِ فَإِنَّ اللَّهَ سَرِيعُ الْحِسَابِ", lao: "ແທ້ຈິງ, ສາສະໜາที่ອັນລໍทรงยอมรับຄືອິສລາມ. ແລະຜູ້ที่ได้รับคัมภีร์ບໍ່ได้ขัดแย้งกันนอกจากหลังจากที่ความรู้ได้มาถึงพวกเขาแล้ว, ດ້ວຍความอิจฉาระหว่างกัน. ແລະຜູ້ໃດທີ່ປະຕິເສດສັນຍານຂອງອັນລໍ, ແທ້ຈິງອັນລໍทรงรวดเร็วในการคิดบัญชี.", english: "Indeed, the religion in the sight of Allah is Islam. And those who were given the Scripture did not differ except after knowledge had come to them - out of jealous animosity between themselves. And whoever disbelieves in the verses of Allah, then indeed, Allah is swift in account." },
  { number: "3:20", arabic: "فَإِنْ حَاجُّوكَ فَقُلْ أَsْلَمْتُ وَجْهِيَ لِلَّهِ وَمَنِ اتَّبَعَنِ ۗ وَقُل لِّلَّذِينَ أُوتُوا الْكِتَابَ وَالْأُمِّيِّينَ أَأَسْلَمْتُمْ ۚ فَإِنْ أَsْلَمُوا فَقَدِ اهْتَدَوا ۖ وَّإِن تَوَلَّوْا فَإِنَّمَا عَلَيْكَ الْبَلَاغُ ۗ وَاللَّهُ بَصِيرٌ بِالْعِبَادِ", lao: "ແລະຖ້າພວກເຂົາຖຽງກັບເຈົ້າ, ຈົ່ງກ່າວວ່າ: 'ຂ້ອຍໄດ້ຍອມຈຳນົນຕໍ່ອັນລໍ, ແລະຜູ້ທີ່ຕິດຕາມຂ້ອຍກໍເຊັ່ນກັນ.' ແລະຈົ່ງກ່າວແກ່ຜູ້ที่ได้รับคัมภีร์และผู้ที่ไม่รู้หนังสือว่า: 'ພວກເຈົ້າໄດ້ຍອມຈຳນົນແລ້ວບໍ?' ແລະຖ້າພວກເຂົາຍອມຈຳນົນ, ພວກເຂົາກໍໄດ້ຮັບການຊີ້ແນະ. ແຕ່ຖ້າພວກເຂົາຫັນໜີ, ໜ້າທີ່ຂອງເຈົ້າຄືການປະກາດ. ແລະອັນລໍทรงเห็นบ่าวของพระองค์.", english: "So if they argue with you, say, 'I have submitted myself to Allah [in Islam], and [so have] those who follow me.' And say to those who were given the Scripture and [to] the unlearned, 'Have you submitted yourselves?' And if they submit, then they are rightly guided; but if they turn away - then upon you is only the [duty of] notification. And Allah is Seeing of [His] servants." },
  { number: "3:21", arabic: "إِنَّ الَّذِينَ يَكْفُرُونَ بِآيَاتِ اللَّهِ وَيَقْتُلُونَ النَّبِيِّينَ بِغَيْرِ حَقٍّ وَيَقْتُلُونَ الَّذِينَ يَأْمُرُونَ بِالْقِسْطِ مِنَ النَّاسِ فَبَشِّرْهُم بِعَذَابٍ أَلِيمٍ", lao: "ແທ້ຈິງ, ບັນດາຜູ້ທີ່ປະຕິເສດສັນຍານຂອງອັນລໍ ແລະ ຂ້າສາດສະດາໂດຍບໍ່ມີສິດ, ແລະ ຂ້າຜູ້ທີ່ສັ່ງສອນຄວາມຍຸດຕິທຳໃນหมู่ມະນຸດ, ຈົ່ງແຈ້ງຂ່າວການລົງໂທດທີ່ເຈັບປວດແກ່ພວກເຂົາ.", english: "Indeed, those who disbelieve in the signs of Allah and kill the prophets without right and kill those who order justice from among the people - give them tidings of a painful punishment." },
  { number: "3:22", arabic: "أُولَٰئِكَ الَّذِينَ حَبِطَتْ أَعْمَالُهُمْ فِي الدُّنْيَا وَالْآخِرَةِ وَمَا لَهُم مِّن نَّاصِرِينَ", lao: "ພວກເຂົາຄືຜູ້ທີ່ການກະທຳຂອງພວກເຂົາสูญเปล่าในโลกนี้และโลกหน้า, และพวกเขาไม่มีผู้ช่วยเหลือ.", english: "Those are the ones whose deeds have become worthless in this world and the Hereafter, and for them there will be no helpers." },
  { number: "3:23", arabic: "أَلَمْ تَرَ إِلَى الَّذِينَ أُوتُوا نَصِيبًا مِّنَ الْكِتَابِ يُدْعَوْنَ إِلَىٰ كِتَابِ اللَّهِ لِيَحْكُمَ بَيْنَهُمْ ثُمَّ يَتَوَلَّىٰ فَرِيقٌ مِّنْهُمْ وَهُم مُّعْرِضُونَ", lao: "ເຈົ້າບໍ່ເຫັນບໍผู้ที่ได้รับส่วนหนึ่งของคัมภีร์? ພວກເຂົາຖືກເອີ້ນໃຫ້ມາສູ່ຄຳພີຂອງອັນລໍເພື່ອຕັດສິນລະຫວ່າງພວກເຂົາ, ແລ້ວກຸ່ມໜຶ່ງໃນພວກເຂົາກໍหันหลังกลับໃນຂະນະที่พวกเขากำลังຜິນຫຼັງ.", english: "Have you not considered those who were given a portion of the Scripture? They are invited to the Book of Allah that it should judge between them; then a party of them turns away while they are refusing." },
  { number: "3:24", arabic: "ذَٰلِكَ بِأَنَّهُمْ قَالُوا لَن تَمَسَّنَا النَّارُ إِلَّا أَيَّامًا مَّعْدُودَاتٍ ۖ وَغَرَّهُمْ فِي دِينِهِم مَّا كَانُوا يَfْتَرُونَ", lao: "ນັ້ນเป็นเพราะพวกเขากล่าวว่า: 'ไฟนรกจะไม่แตะต้องเรายกเว้นສອງສາມວັນ.' ແລະສິ່ງที่ພວກເຂົາเคยสร้างຂຶ້ນໄດ້ຫຼອກລວງພວກເຂົາในศาสนาของพวกเขา.", english: "That is because they say, 'Never will the Fire touch us except for a number of days.' And they were deluded in their religion by what they used to invent." },
  { number: "3:25", arabic: "فَكَيْfَ إِذَا جَمَعْنَاهُمْ لِيَوْmٍ لَّا رَيْbَ فِيهِ وَوُfِّيَتْ كُلُّ نَفْسٍ مَّا كَسَبَتْ وَهُمْ لَا يُظْلَمُونَ", lao: "ແລ້ວจะเป็นอย่างไรເມື່ອเราຮวบຮວມพวกเขาในວັນที่ไม่มีความสงสัย? ແລະທຸກຄົນຈະได้รับการตอบแทนอย่างเต็มที่สำหรับสิ่งที่ได้ทำ, ແລະພວກເຂົາจะไม่ถูกทำร้าย.", english: "So how will it be when We assemble them for a Day about which there is no doubt? And each soul will be compensated [in full for] what it has earned, and they will not be wronged." },
  { number: "3.26", arabic: "قُلِ اللَّهُمَّ مَالِكَ الْمُلْكِ تُؤْتِي الْمُلْكَ مَن تَشَاءُ وَتَنzِعُ الْمُلْكَ مِمَّn تَشَاءُ وَتُعِzُّ مَن تَشَاءُ وَتُذِلُّ مَن تَشَاءُ ۖ بِيَدِكَ الْخَيْرُ ۖ إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", lao: "ຈົ່ງກ່າວວ່າ: 'ໂອ້ ອັນລໍ, ເຈົ້າແຫ່ງອຳນາດ, ພຣະອົງทรงให้อำนาจแก่ผู้ที่พระองค์ทรงประสงค์และถอดถอนอำนาจจากผู้ที่พระองค์ทรงประสงค์, ແລະພຣະອົງทรงให้เกียรติผู้ที่พระองค์ทรงประสงค์และทรงทำให้อัปยศผู้ที่พระองค์ทรงประสงค์. ໃນພຣະຫັດຂອງພຣະອົງຄືຄວາມດີ. ແທ້ຈິງ, ພຣະອົງทรงมีอำนาจเหนือทุกสิ่ง.'", english: "Say, 'O Allah, Owner of Sovereignty, You give sovereignty to whom You will and You take sovereignty away from whom You will. You honor whom You will and You humiliate whom You will. In Your hand is [all] good. Indeed, You are over all things competent.'" },
  { number: "3.27", arabic: "تُولِjُ اللَّيْلَ فِي النَّهَarِ وَتُولِjُ النَّهَarَ فِي اللَّيْلِ ۖ وَتُخْرِjُ الْحَيَّ مِنَ الْمَيِّتِ وَتُخْرِjُ الْمَيِّتَ مِنَ الْحَيِّ ۖ وَتَرْzُقُ مَن تَشَاءُ بِغَيْرِ حِسَابٍ", lao: "ພຣະອົງทรงทำให้ກາງຄືນເຂົ້າไปໃນกลางวันແລະทรงทำให้กลางวันເຂົ້າไปໃນกลางคืน. ແລະພຣະອົງทรงนำສິ່ງທີ່ມີຊີວິດອອກຈາກສິ່ງທີ່ຕາຍແລະทรงนำສິ່ງທີ່ຕາຍອອກຈາກສິ່ງທີ່ມີຊີວິດ. ແລະພຣະອົງทรงให้ปัจจัยแก่ผู้ที่พระองค์ทรงประสงค์โดยไม่มีการคำนวณ.", english: "You cause the night to enter the day, and You cause the day to enter the night; and You bring the living out of the dead, and You bring the dead out of the living. And You give provision to whom You will without account." },
  { number: "3.28", arabic: "لَّا يَتَّخِذِ الْمُؤْمِنُونَ الْكَافِرِينَ أَوْلِيَاءَ مِن دُونِ الْمُؤْمِنِينَ ۖ وَمَن يَfْعَلْ ذَٰلِكَ فَلَيْsَ مِنَ اللَّهِ فِي شَيْءٍ إِلَّا أَن تَتَّقُوا مِنْهُمْ تُقَاةً ۗ وَيُحَذِّرُكُمُ اللَّهُ نَفْسَهُ ۗ وَإِلَى اللَّهِ الْمَصِيرُ", lao: "ຢ່າให้ผู้ศรัทธาเอาผู้ปฏิเสธมาเป็นพันธมิตรแทนผู้ศรัทธา. ແລະຜູ້ໃດທີ່ทำเช่นนั้นກໍບໍ່ມີอะไรจากอัลลอฮ์, ยกเว้นกรณีที่พวกเจ้าต้องระวังพวกเขา. ແລະອັນລໍทรงเตือนพวกเจ้าให้ระวังพระองค์. ແລະການກັບไปอยู่กับອັນລໍ.", english: "Let not believers take disbelievers as allies rather than believers. And whoever [of you] does that has nothing with Allah, except when taking precaution against them in prudence. And Allah warns you of Himself, and to Allah is the [final] destination." },
  { number: "3.29", arabic: "قُلْ إِن تُخْfُوا مَا فِي صُدُورِكُمْ أَوْ تُbْدُوهُ يَعْلَمْهُ اللَّهُ ۗ وَيَعْلَمُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ وَاللَّهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", lao: "ຈົ່ງກ່າວວ່າ: 'ຖ້າพวกเจ้าปกปิดสิ่งที่อยู่ในใจหรือเปิดเผยมัน, อัลลอฮ์ทรงรู้. ແລະພຣະອົງทรงรู้สิ่งที่อยู่ในชั้นฟ้าและสิ่งที่อยู่ในแผ่นดิน. ແລະອັນລໍทรงมีอำนาจเหนือทุกสิ่ง.'", english: "Say, 'Whether you conceal what is in your breasts or reveal it, Allah knows it. And He knows that which is in the heavens and that which is on the earth. And Allah is over all things competent.'" },
  { number: "3.30", arabic: "يَوْمَ تَjِدُ كُلُّ نَفْسٍ مَّا عَمِلَتْ مِنْ خَيْرٍ مُّحْضَرًا وَمَا عَمِلَتْ مِن sūءٍ تَوَدُّ لَوْ أَنَّ بَيْنَهَا وَبَيْنَهُ أَمَدًا bَعِيدًا ۗ وَيُحَذِّrُكُمُ اللَّهُ نَفْسَهُ ۗ وَاللَّهُ رَءُوفٌ بِالْعِبَادِ", lao: "ວັນທີ່ທຸກຄົນຈະພົບການກະທຳດີທີ່ໄດ້ทำไว้ปรากฏอยู่, และการกระทำชั่วที่ได้ทำไว้, ລາວจะปรารถนาให้มีระยะทางห่างไกลระหว่างລາวกับมัน. ແລະອັນລໍทรงเตือนพวกเจ้าให้ระวังพระองค์. ແລະອັນລໍทรงเมตตาต่อบ่าว.", english: "On the Day when every soul will be confronted with all the good it has done and all the evil it has done, it will wish that there were a great distance between it and its evil. And Allah warns you of Himself, and Allah is Kind to [His] servants." },
  { number: "3:31", arabic: "قُلْ إِن كُنتُمْ تُحِبُّونَ اللَّهَ فَاتَّbِعُونِي يُحْبِبْكُمُ اللَّهُ وَيَغْfِرْ لَكُمْ ذُنُوبَكُمْ ۗ وَاللَّهُ غَفُورٌ رَّحِيمٌ", lao: "ຈົ່ງກ່າວວ່າ: 'ຖ້າพวกเจ้ารักอัลลอฮ์, ກໍຈົ່ງตามข้า, อัลลอฮ์จะทรงรักพวกเจ้าและอภัยบาปให้พวกเจ้า.' ແລະອັນລໍทรงอภัย, ทรงเมตตา.", english: "Say, [O Muhammad], 'If you should love Allah, then follow me, [so] Allah will love you and forgive you your sins. And Allah is Forgiving and Merciful.'" },
  { number: "3.32", arabic: "قُلْ أَطِيعُوا اللَّهَ وَالرَّsُولَ ۖ فَإِن تَوَلَّوْا فَإِنَّ اللَّهَ لَا يُحِبُّ الْكَافِرِينَ", lao: "ຈົ່ງກ່າວວ່າ: 'ຈົ່ງເຊື່ອຟັງອັນລໍແລະศาสดา.' ແຕ່ຖ້າພວກເຂົາຫັນໜີ, ແທ້ຈິງອັນລໍບໍ່ทรงรักผู้ปฏิเสธ.", english: "Say, 'Obey Allah and the Messenger.' But if they turn away - then indeed, Allah does not love the disbelievers." },
  { number: "3:33", arabic: "إِنَّ اللَّهَ اصْطَفَىٰ آدَمَ وَنُوحًا وَآلَ إِبْرَاهِيمَ وَآلَ عِمْرَانَ عَلَى الْعَالَمِينَ", lao: "ແທ້ຈິງ, ອັນລໍໄດ້ຊົງເລືອກອາດັມ, ນູຫ໌, ຄອບຄົວຂອງອີບຣາຮີມ, ແລະ ຄອບຄົວຂອງອີມຣອນເໜືອໂລກ.", english: "Indeed, Allah chose Adam and Noah and the family of Abraham and the family of 'Imran over the worlds -" },
  { number: "3.34", arabic: "ذُرِّيَّةً بَعْضُهَا مِن بَعْضٍ ۗ وَاللَّهُ سَمِيعٌ عَلِيمٌ", lao: "ລູກຫຼານ, ບາງຄົນມາຈາກຄົນອື່ນ. ແລະອັນລໍทรงได้ยิน, ทรงรอบรู้.", english: "Descendants, some of them from others. And Allah is Hearing and Knowing." },
  { number: "3:35", arabic: "إِذْ قَالَتِ امْرَأَتُ عِمْرَانَ رَبِّ إِنِّي نَذَرْتُ لَكَ مَا فِي بَطْنِي مُحَرَّrًا فَتَقَبَّلْ مِنِّي ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ", lao: "ເມື່ອภรรยาຂອງອີມຣອນກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງข้า, ແທ້ຈິງข้าໄດ້ສັນຍາว่าจะอุทิศสิ่งที่อยู่ในท้องของข้าให้แก่ພຣະອົງ, ດັ່ງນັ້ນขอให้ทรงรับจากข้า. ແທ້ຈິງ, ພຣະອົງทรงได้ยิน, ทรงรอบรู้.'", english: "[Mention] when the wife of 'Imran said, 'My Lord, indeed I have pledged to You what is in my womb, consecrated [for Your service], so accept this from me. Indeed, You are the Hearing, the Knowing.'" },
  { number: "3:36", arabic: "فَلَمَّا وَضَعَتْهَا قَالَتْ رَبِّ إِنِّي وَضَعْتُهَا أُنثَىٰ وَاللَّهُ أَعْلَمُ بِمَا وَضَعَتْ وَلَيْsَ الذَّكَرُ كَالْأُنثَىٰ ۖ وَإِنِّي سَمَّيْتُهَا مَرْيَمَ وَإِنِّي أُعِيذُهَا بِكَ وَذُرِّيَّتَهَا مِنَ الشَّيْطَانِ الرَّjِيمِ", lao: "ແລະເມື່อนางคลอดบุตร, นางกล่าวว่า: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າของข้า, ແທ້ຈິງข้าคลอดเป็นผู้หญิง.' ແລະອັນລໍทรงรู้ดีกว่าว่านางคลอดอะไร. และชายไม่เหมือนหญิง. 'ແລະແທ້ຈິງข้าได้ตั้งชื่อนางว่ามัรยัม, ແລະข้าขอความคุ้มครองจากພຣະອົງให้นางและลูกหลานของนางพ้นจากชัยฏอนที่ถูกสาปแช่ง.'", english: "But when she delivered her, she said, 'My Lord, I have delivered a female.' And Allah was most knowing of what she delivered, 'And the male is not like the female. And I have named her Mary, and I seek refuge for her in You and [for] her descendants from Satan, the expelled [from the mercy of Allah].'" },
  { number: "3:37", arabic: "فَتَقَبَّلَهَا رَبُّهَا بِقَبُولٍ حَسَنٍ وَأَنbَتَهَا نَبَاتًا حَسَنًا وَكَfَّلَهَا zَكَرِيَّا ۖ كُلَّمَا دَخَلَ عَلَيْهَا zَكَرِيَّا الْمِحْرَابَ وَjَدَ عِندَهَا رِzْقًا ۖ قَالَ يَا مَرْيَمُ أَنَّىٰ لَكِ هَٰذَا ۖ قَالَتْ هُوَ مِنْ عِندِ اللَّهِ ۖ إِنَّ اللَّهَ يَرْzُقُ مَن يَشَاءُ بِغَيْرِ حِسَابٍ", lao: "ດັ່ງນັ້ນ, ພຣະຜູ້ເປັນເຈົ້າຂອງນາງຈຶ່ງໄດ້ຮັບນາງด้วยการยอมรับที่ดีและเลี้ยงดูนางอย่างดี, ແລະໄດ້มอบให้นางอยู่ในความดูแลของซะกะรียา. ທຸກຄັ້ງທີ່ซะกะรียาเข้านางในห้องอธิษฐาน, ລາວພົບอาหารอยู่กับนาง. ລາວກ່າວວ່າ: 'ໂອ້ มัรยัม, ສິ່ງນີ້ມາจากไหน?' นางกล่าวว่า: 'ມັນມາຈາກອັນລໍ. ແທ້ຈິງອັນລໍทรงให้ปัจจัยแก่ผู้ที่พระองค์ทรงประสงค์โดยไม่มีการคำนวณ.'", english: "So her Lord accepted her with good acceptance and caused her to grow in a good manner and put her in the care of Zechariah. Every time Zechariah entered upon her in the prayer chamber, he found with her provision. He said, 'O Mary, from where is this [coming] to you?' She said, 'It is from Allah. Indeed, Allah provides for whom He wills without account.'" },
  { number: "3:38", arabic: "هُنَالِكَ dَعَا zَكَرِيَّا رَبَّهُ ۖ قَالَ رَبِّ هَبْ لِي مِن لَّdُنكَ ذُرِّيَّةً طَيِّbَةً ۖ إِنَّكَ sَمِيعُ الدُّعَاءِ", lao: "ທີ່ນັ້ນ, ซะกะรียาได้วิงวอนต่อพระเจ้าของเขา. ລາວກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງຂ้า, ຂໍให้ประทานลูกหลานที่ดีแก่ข้าจากພຣະອົງ. ແທ້ຈິງ, ພຣະອົງทรงได้ยินคำวิงวอน.'", english: "At that, Zechariah called upon his Lord, saying, 'My Lord, grant me from Yourself a good offspring. Indeed, You are the Hearer of supplication.'" },
  { number: "3:39", arabic: "فَنَاdَتْهُ الْمَلَائِكَةُ وَهُوَ قَائِمٌ يُصَلِّي فِي الْمِحْرَابِ أَنَّ اللَّهَ يُbَشِّrُكَ بِيَحْيَىٰ مُصَدِّqًا بِكَلِمَةٍ مِّنَ اللَّهِ وَsَيِّdًا وَحَصُورًا وَنَبِيًّا mِّنَ الصَّالِحِينَ", lao: "แล้วทูตสวรรค์ได้เรียกเขาในขณะที่เขากำลังยืนอธิษฐานในห้องอธิษฐานว่า: 'ແທ້ຈິງອັນລໍทรงแจ้งข่าวดีแก่ท่านเกี่ยวกับยะห์ยา, ผู้ที่จะมายืนยันคำจากอัลลอฮ์, เป็นผู้นำ, ผู้ทรงพรต, และเป็นศาสดาจากผู้ที่ชอบธรรม.'", english: "So the angels called him while he was standing in prayer in the chamber, 'Indeed, Allah gives you good tidings of John, confirming a word from Allah and [who will be] honorable, abstaining [from women], and a prophet from among the righteous.'" },
  { number: "3:40", arabic: "قَالَ رَبِّ أَنَّىٰ يَكُونُ لِي غُلَامٌ وَقَدْ بَلَغَنِيَ الْكِبَرُ وَامْرَأَتِي عَاقِرٌ ۖ قَالَ كَذَٰلِكَ اللَّهُ يَfْعَلُ مَا يَشَاءُ", lao: "ລາວກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງຂ้า, ຂ້າจะมีลูกชายได้อย่างไรในเมื่อความแก่ได้มาถึงข้าแล้วและภรรยาของข้าก็เป็นหมัน?' [ทูตสวรรค์] ກ່າວວ່າ: 'เช่นนั้นแหละ, อัลลอฮ์ทรงทำในสิ่งที่พระองค์ทรงประสงค์.'", english: "He said, 'My Lord, how will I have a boy when I have reached old age and my wife is barren?' The angel said, 'Such is Allah ; He does what He wills.'" },
  { number: "3:41", arabic: "قَالَ رَبِّ اجْعَل لِّي آيَةً ۖ قَالَ آيَتُكَ أَلَّا تُكَلِّمَ النَّاسَ ثَلَاثَةَ أَيَّامٍ إِلَّا رَمْzًا ۗ وَاذْكُر رَّbَّكَ كَثِيرًا وَsَبِّحْ بِالْعَشِيِّ وَالْإِبْكَarِ", lao: "ລາວກ່າວວ່າ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງຂ้า, ຂໍให้ทรงกำหนดສັນຍານให้แก่ข้า.' [ทูตสวรรค์] ກ່າວວ່າ: 'ສັນຍານของท่านคือท่านจะไม่สามารถพูดกับผู้คนได้เป็นเวลาສາມວັນยกเว้นการใช้ท่าทาง. ແລະຈົ່ງລະນຶກເຖິງພຣະຜູ້ເປັນເຈົ້າຂອງท่านให้มากๆ และสรรเสริญพระองค์ในยามเย็นและยามเช้า.'", english: "He said, 'My Lord, make for me a sign.' He said, 'Your sign is that you will not speak to the people for three days except by gesture. And remember your Lord much and exalt [Him with praise] in the evening and the morning.'" },
  { number: "3:42", arabic: "وَإِذْ قَالَتِ الْمَلَائِكَةُ يَا مَرْيَمُ إِنَّ اللَّهَ اصْطَفَاكِ وَطَهَّrَكِ وَاصْطَفَاكِ عَلَىٰ نِسَاءِ الْعَالَمِينَ", lao: "ແລະເມື່ອทูตสวรรค์กล่าวว่า: 'ໂອ້ มัรยัม, ແທ້ຈິງອັນລໍໄດ້ทรงเลือกเจ้าແລະชำระล้างเจ้าແລະเลือกเจ้าເໜືອผู้หญิงທັງหลายในโลก.'", english: "And [mention] when the angels said, 'O Mary, indeed Allah has chosen you and purified you and chosen you above the women of the worlds.'" },
  { number: "3:43", arabic: "يَا مَرْيَمُ اقْنُتِي لِرَبِّكِ وَاسْjُdِي وَarْكَعِي مَعَ الرَّاكِعِينَ", lao: "'ໂອ້ มัรยัม, ຈົ່ງเชื่อฟังພຣະຜູ້ເປັນເຈົ້າຂອງเจ้าและกราบไหว้และโค้งคำนับพร้อมกับผู้ที่โค้งคำนับ.'", english: "'O Mary, be devoutly obedient to your Lord and prostrate and bow with those who bow [in prayer].'" },
  { number: "3:44", arabic: "ذَٰلِكَ مِنْ أَنbَاءِ الْغَيْbِ نُوحِيهِ إِلَيْكَ ۚ وَمَا كُنتَ لَدَيْهِمْ إِذْ يُلْقُونَ أَقْلَامَهُمْ أَيُّهُمْ يَكْfُلُ مَرْيَمَ وَمَا كُنتَ لَدَيْهِمْ إِذْ يَخْتَصِمُونَ", lao: "ນັ້ນຄືສ່ວນໜຶ່ງຂອງຂ່າວสารທີ່ซ่อนเร้นທີ່เราเปิดเผยแก่เจ้า. ແລະเจ้าไม่ได้อยู่กับพวกเขาเมื่อพวกเขาโยนปากกาของพวกเขา [เพื่อเสี่ยงทาย] ว่าใครจะดูแลมัรยัม, และเจ้าไม่ได้อยู่กับพวกเขาเมื่อพวกเขาโต้เถียงกัน.", english: "That is from the news of the unseen which We reveal to you, [O Muhammad]. And you were not with them when they cast their pens as to which of them should be responsible for Mary. Nor were you with them when they disputed." },
  { number: "3:45", arabic: "إِذْ قَالَتِ الْمَلَائِكَةُ يَا مَرْيَمُ إِنَّ اللَّهَ يُbَشِّrُكِ بِكَلِمَةٍ مِّنْهُ اسْمُهُ الْمَسِيحُ عِيسَى ابْنُ مَرْيَمَ وَjِيهًا فِي الدُّنْيَا وَالْآخِرَةِ وَمِنَ الْمُقَرَّbِينَ", lao: "ເມື່ອทูตสวรรค์กล่าวว่า: 'ໂອ້ มัรยัม, ແທ້ຈິງອັນລໍทรงแจ้งข่าวดีแก่เจ้าด้วยคำจากพระองค์, ຊື່ຂອງລາວຄືพระเมสสิยาห์อีซา, ລູກຊາຍຂອງมัรยัม, ເປັນຜູ້ທີ່ມີเกียรติในโลกนี้และโลกหน้า, และเป็นหนึ่งในผู้ที่ใกล้ชิด [กับอัลลอฮ์].'", english: "[And mention] when the angels said, 'O Mary, indeed Allah gives you good tidings of a word from Him, whose name will be the Messiah, Jesus, the son of Mary - distinguished in this world and the Hereafter and among those brought near [to Allah].'" },
  { number: "3:46", arabic: "وَيُكَلِّمُ النَّاسَ فِي الْمَهْدِ وَكَهْلًا وَمِنَ الصَّالِحِينَ", lao: "'ລາວจะพูดกับผู้คนໃນเปลและในวัยผู้ใหญ่, ແລະລາວຈະເປັນໜຶ່ງໃນผู้ที่ชอบธรรม.'", english: "'He will speak to the people in the cradle and in maturity and will be of the righteous.'" },
  { number: "3:47", arabic: "قَالَتْ رَبِّ أَنَّىٰ يَكُونُ لِي وَلَدٌ وَلَمْ يَمْسَسْنِي بَشَرٌ ۖ قَالَ كَذَٰلِكِ اللَّهُ يَخْلُقُ مَا يَشَاءُ ۚ إِذَا قَضَىٰ أَمْرًا فَإِنَّمَا يَقُولُ لَهُ كُن فَيَكُونُ", lao: "นางกล่าวว่า: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງຂ้า, ຂ้าจะมีลูกได้อย่างไรในเมื่อไม่มีชายใดแตะต้องข้า?' [ทูตสวรรค์] ກ່າວວ່າ: 'เช่นนั้นแหละ, อัลลอฮ์ทรงสร้างสิ่งที่พระองค์ทรงประสงค์. ເມື່ອพระองค์ทรงกำหนดสิ่งใด, พระองค์เพียงกล่าวแก่มันว่า: 'จงเป็น' และมันก็เป็น.'", english: "She said, 'My Lord, how will I have a child when no man has touched me?' [The angel] said, 'Such is Allah ; He creates what He wills. When He decrees a matter, He only says to it, 'Be,' and it is.'" },
  { number: "3:48", arabic: "وَيُعَلِّمُهُ الْكِتَابَ وَالْحِكْمَةَ وَالتَّوْrَاةَ وَالْإِnjِيلَ", lao: "'ແລະພຣະອົງจะสอนລາวคัมภีร์และปัญญา, ແລະเตารอตและอินญีล.'", english: "'And He will teach him writing and wisdom and the Torah and the Gospel'" },
  { number: "3:49", arabic: "وَرَسُولًا إِلَىٰ بَنِي إِسْرَائِيلَ أَنِّي قَدْ jِئْتُكُم بِآيَةٍ مِّن rَّbِّكُمْ ۖ أَنِّي أَخْلُقُ لَكُم مِّنَ الطِّينِ كَهَيْئَةِ الطَّيْرِ فَأَنfُخُ فِيهِ فَيَكُونُ طَيْرًا بِإِذْنِ اللَّهِ ۖ وَأُbْرِئُ الْأَكْمَهَ وَالْأَبْرَصَ وَأُحْيِي الْمَوْتَىٰ بِإِذْنِ اللَّهِ ۖ وَأُنَبِّئُكُم بِمَا تَأْكُلُونَ وَمَا تَدَّخِرُونَ فِي بُيُوتِكُمْ ۚ إِنَّ فِي ذَٰلِكَ لَآيَةً لَّكُمْ إِن كُنتُم mُّؤْمِنِينَ", lao: "'ແລະ [ເຮັດให้ລາวเป็น] ศาสดาแก่ลูกหลานของอิสราเอล, [โดยกล่าวว่า]: 'แท้จริงข้าได้นำສັນຍານจากพระเจ้าของพวกเจ้ามาให้พวกเจ้า. ข้าจะสร้างให้พวกเจ้าจากดินເໝືອນຮູບນົກ, ແລ້ວຂ้าจะเป่าลมเข้าไปในมัน, ແລ້ວมันก็จะกลายเป็นนกด้วยการอนุมัติของอัลลอฮ์. ແລະข้าจะรักษาຄົນຕາບອດแต่กำเนิดและຄົນโรคเรื้อน, ແລະข้าจะทำให้ຄົນຕາຍมีຊີວິດຄືນมาด้วยการอนุมัติของอัลลอฮ์. ແລະข้าจะบอกพวกเจ้าถึงสิ่งที่พวกเจ้ากินและสิ่งที่พวกเจ้าเก็บไว้ในบ้าน. ແທ້ຈິງในນັ້ນมีສັນຍານสำหรับพวกเจ้า, ຫາກพวกเจ้าເປັນผู้ศรัทธา.'", english: "'And [make him] a messenger to the Children of Israel, [who will say], 'Indeed I have come to you with a sign from your Lord in that I design for you from clay [that which is] like the form of a bird, then I breathe into it and it becomes a bird by permission of Allah. And I cure the blind and the leper, and I give life to the dead - by permission of Allah. And I inform you of what you eat and what you store in your houses. Indeed in that is a sign for you, if you are believers.'" },
  { number: "3:50", arabic: "وَمُصَدِّqًا لِّمَا بَيْنَ يَدَيَّ مِنَ التَّوْrَاةِ وَلِأُحِلَّ لَكُم بَعْضَ الَّذِي حُرِّمَ عَلَيْكُمْ ۚ وَjِئْتُكُم بِآيَةٍ مِّن rَّbِّكُمْ فَاتَّقُوا اللَّهَ وَأَطِيعُونِ", lao: "'ແລະ [ຂ້າมา] ເພື່ອຢືນຢັນสิ่งที่อยู่ກ່ອນหน้าข้าคือเตารอต, และເພື່ອอนุญาตให้พวกเจ้าບາງสิ่งที่เคยถูกห้าม. ແລະຂ้าได้นำສັນຍານจากพระเจ้าของพวกเจ้ามาให้พวกเจ้า, ດັ່ງນັ້ນจົ່ງຢำເກງอัลลอฮ์และเชื่อฟังข้า.'", english: "'And [I have come] confirming what was before me of the Torah and to make lawful for you some of what was forbidden to you. And I have come to you with a sign from your Lord, so fear Allah and obey me.'" },
  { number: "3:51", arabic: "إِنَّ اللَّهَ رَبِّي وَرَبُّكُمْ فَاعْبُدُوهُ ۗ هَٰذَا صِرَاطٌ مُّsْتَقِيمٌ", lao: "'ແທ້ຈິງ, ອັນລໍຫ໌ຄືພຣະຜູ້ເປັນເຈົ້າຂອງຂ้าແລະພຣະຜູ້ເປັນເຈົ້າຂອງພວກเจ้า, ດັ່ງນັ້ນຈົ່ງນະມັດສະການພຣະອົງ. ນີ້ຄືເສັ້ນທາງທີ່ຊື່ກົງ.'", english: "'Indeed, Allah is my Lord and your Lord, so worship Him. That is the straight path.'" },
  { number: "3:52", arabic: "فَلَمَّا أَحَسَّ عِيسَىٰ مِنْهُمُ الْكُfْرَ قَالَ مَنْ أَنصَarِي إِلَى اللَّهِ ۖ قَالَ الْحَوَarِيُّونَ نَحْنُ أَنصَarُ اللَّهِ آمَنَّا بِاللَّهِ وَاشْهَدْ بِأَنَّا مُsْلِمُونَ", lao: "ເມື່ອອີຊາຮູ້ສຶກເຖິງການປະຕິເສດຈາກພວກເຂົາ, ລາວໄດ້ກ່າວວ່າ: 'ໃຜຈະເປັນຜູ້ຊ່ວຍເຫຼືອຂ้าไปสู่อัลลอฮ์?' ອັກຄະສາວົກກ່າວວ່າ: 'ພວກເຮົາຄືຜູ້ຊ່ວຍເຫຼືອของอัลลอฮ์. ພວກເຮົາເຊື່ອໃນอัลลอฮ์, และจงเป็นพยานว่าเราเป็นมุสลิม.'", english: "But when Jesus felt [persistence in] disbelief from them, he said, 'Who are my supporters for Allah ?' The disciples said, 'We are supporters of Allah. We have believed in Allah and testify that we are Muslims [submitting to Him].'" },
  { number: "3:53", arabic: "رَبَّنَا آمَنَّا بِمَا أَنزَلْتَ وَاتَّbَعْنَا الرَّsُولَ فَاكْتُbْنَا مَعَ الشَّاهِدِينَ", lao: "'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ, ພວກເຮົາເຊື່ອໃນສິ່ງທີ່ພຣະອົງໄດ້ทรงเปิดเผยແລະພວກເຮົາໄດ້ຕິດຕາມศาสดา, ດັ່ງນັ້ນຂໍໃຫ້บันทึกเราไว้กับผู้ที่เป็นพยาน.'", english: "'Our Lord, we have believed in what You revealed and have followed the messenger, so register us among the witnesses.'" },
  { number: "3:54", arabic: "وَمَكَرُوا وَمَكَرَ اللَّهُ ۖ وَاللَّهُ خَيْرُ الْمَاكِرِينَ", lao: "ແລະພວກເຂົາໄດ້ວາງແຜນ, ແລະອັນລໍຫ໌ກໍໄດ້ວາງແຜນ. ແລະອັນລໍຫ໌ເປັນผู้วางแผนที่ดีที่สุด.", english: "And the disbelievers planned, but Allah planned. And Allah is the best of planners." },
  { number: "3:55", arabic: "إِذْ قَالَ اللَّهُ يَا عِيسَىٰ إِنِّي مُتَوَfِّيكَ وَrَافِعُكَ إِلَيَّ وَمُطَهِّrُكَ مِنَ الَّذِينَ كَفَرُوا وَjَاعِلُ الَّذِينَ اتَّbَعُوكَ فَوْقَ الَّذِينَ كَفَرُوا إِلَىٰ يَوْmِ الْقِيَامَةِ ۖ ثُمَّ إِلَيَّ مَرْjِعُكُمْ فَأَحْكُمُ بَيْنَكُمْ فِيمَا كُنتُمْ فِيهِ تَخْتَلِfُونَ", lao: "ເມື່ອອັນລໍຫ໌ກ່າວວ່າ: 'ໂອ້ ອີຊາ, ແທ້ຈິງຂ้าจะทำให้เจ้าตายและยกเจ้าขึ้นมาหาຂ้าແລະชำระล้างเจ้าจากผู้ที่ปฏิเสธແລະເຮັດໃຫ້ผู้ที่ติดตามเจ้าอยู่เหนือผู้ที่ปฏิเสธຈົນເຖິງວັນກິຍາມະ. ຫຼັງຈາກນັ້ນ, ພວກเจ้าจะกลับมาหาข้า, ແລະข้าจะตัดสินລະຫວ່າງพวกเจ้าในสิ่งที่พวกเจ้าเคยขัดแย้งกัน.'", english: "[Mention] when Allah said, 'O Jesus, indeed I will take you and raise you to Myself and purify you from those who disbelieve and make those who follow you [in submission to Allah alone] superior to those who disbelieve until the Day of Resurrection. Then to Me is your return, and I will judge between you concerning that in which you used to differ." },
  { number: "3:56", arabic: "فَأَمَّا الَّذِينَ كَفَرُوا فَأُعَذِّbُهُمْ عَذَابًا شَدِيدًا فِي الدُّنْيَا وَالْآخِرَةِ وَمَا لَهُم mِّن nَّاصِرِينَ", lao: "'ສ່ວນຜູ້ທີ່ປະຕິເສດ, ຂ้าจะลงโทษพวกเขาอย่างรุนแรงในโลกนี้และโลกหน้า, และพวกเขาจะไม่มีผู้ช่วยเหลือ.'", english: "'And as for those who disbeliev, I will punish them with a severe punishment in this world and the Hereafter, and they will have no helpers.'" },
  { number: "3:57", arabic: "وَأَمَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ فَيُوَfِّيهِمْ أُjُورَهُمْ ۗ وَاللَّهُ لَا يُحِبُّ الظَّالِمِينَ", lao: "'ແລະສ່ວນຜູ້ທີ່ເຊື່ອและເຮັດຄວາມດີ, ພຣະອົງจะให้รางวัลแก่พวกเขาอย่างเต็มที่. ແລະອັນລໍຫ໌ບໍ່ทรงรักผู้ที่ไม่ยุติธรรม.'", english: "'But as for those who believed and did righteous deeds, He will give them in full their rewards, and Allah does not like the wrongdoers.'" },
  { number: "3:58", arabic: "ذَٰلِكَ نَتْلُوهُ عَلَيْكَ مِنَ الْآيَاتِ وَالذِّكْرِ الْحَكِيمِ", lao: "ນັ້ນຄືສິ່ງที่เราอ่านให้เจ้าฟังจากอายะต่างๆ และคำเตือนที่เต็มไปด้วยปัญญา.", english: "This is what We recite to you, [O Muhammad], of the verses and the wise reminder." },
  { number: "3:59", arabic: "إِنَّ مَثَلَ عِيسَىٰ عِندَ اللَّهِ كَمَthَلِ آدَمَ ۖ خَلَقَهُ مِن تُرَابٍ ثُمَّ قَالَ لَهُ كُن فَيَكُونُ", lao: "ແທ້ຈິງ, ຕົວຢ່າງຂອງອີຊາในสายตาของอัลลอฮ์ຄືกับຕົວຢ່າງของอาดัม. ພຣະອົງทรงสร้างเขาจากดิน, ຫຼັງຈາກນັ້ນກ່າວແກ່ລາวว่า: 'จงเป็น' และเขาก็เป็น.", english: "Indeed, the example of Jesus to Allah is like that of Adam. He created Him from dust; then He said to him, 'Be,' and he was." },
  { number: "3:60", arabic: "الْحَقُّ مِن rَّbِّكَ فَلَا تَكُن mِّنَ الْمُمْتَرِينَ", lao: "ความจริงมาจากพระเจ้าของเจ้า, ດັ່ງນັ້ນอย่าเป็นผู้ที่สงสัย.", english: "The truth is from your Lord, so do not be among the doubters." },
  { number: "3:61", arabic: "فَمَنْ حَajَّكَ فِيهِ مِن بَعْدِ مَا jَاءَكَ مِنَ الْعِلْمِ فَقُلْ تَعَالَوْا نَدْعُ أَبْنَاءَنَا وَأَبْنَاءَكُمْ وَنِسَاءَنَا وَنِسَاءَكُمْ وَأَنfُsَنَا وَأَنfُsَكُمْ ثُمَّ نَبْتَهِلْ فَنَjْعَل لَّعْنَتَ اللَّهِ عَلَى الْكَاذِبِينَ", lao: "ດັ່ງນັ້ນຜູ້ໃດที่โต้เถียงกับเจ้าเกี่ยวกับเรื่องนี้หลังจากที่ความรู้ได้มาถึงเจ้าแล้ว, ຈົ່ງກ່າວວ່າ: 'ຈົ່ງມາ, เรามาเรียกลูกชายของเราและลูกชายของพวกเจ้า, ผู้หญิงของเราและผู้หญิงของพวกเจ้า, ตัวเราและตัวพวกเจ้า, ຫຼັງຈາກນັ້ນเรามาวิงวอนและขอให้คำสาปแช่งของอัลลอฮ์อยู่กับผู้ที่โกหก.'", english: "Then whoever argues with you about it after [this] knowledge has come to you - say, 'Come, let us call our sons and your sons, our women and your women, ourselves and yourselves, then supplicate earnestly [together] and invoke the curse of Allah upon the liars [among us].'" },
  { number: "3:62", arabic: "إِنَّ هَٰذَا لَهُوَ الْقَصَصُ الْحَقُّ ۚ وَمَا مِنْ إِلَٰهٍ إِلَّا اللَّهُ ۚ وَإِنَّ اللَّهَ لَهُوَ الْعَzِيزُ الْحَكِيمُ", lao: "ແທ້ຈິງ, ນີ້ຄືเรื่องราวที่แท้จริง. ແລະບໍ່มีพระเจ้าอื่นใดนอกจากอัลลอฮ์. และแท้จริง, อัลลอฮ์คือผู้ทรงอำนาจ, ผู้ทรงมีปัญญา.", english: "Indeed, this is the true narration. And there is no deity except Allah. And indeed, Allah is the Exalted in Might, the Wise." },
  { number: "3:63", arabic: "فَإِن تَوَلَّوْا فَإِنَّ اللَّهَ عَلِيمٌ بِالْمُfْسِدِينَ", lao: "ແຕ່ຖ້າພວກເຂົາຫັນໜີ, ແທ້ຈິງອັນລໍຫ໌ทรงรอบรู้เกี่ยวกับผู้ที่สร้างความเสียหาย.", english: "But if they turn away, then indeed - Allah is Knowing of the corrupters." },
  { number: "3:64", arabic: "قُلْ يَا أَهْلَ الْكِتَابِ تَعَالَوْا إِلَىٰ كَلِمَةٍ سَوَاءٍ بَيْنَنَا وَبَيْنَكُمْ أَلَّا نَعْبُdَ إِلَّا اللَّهَ وَلَا نُشْرِكَ بِهِ شَيْئًا وَلَا يَتَّخِذَ بَعْضُنَا بَعْضًا أَرْbَابًا mِّن دُونِ اللَّهِ ۚ فَإِن تَوَلَّوْا فَقُولُوا اشْهَدُوا بِأَنَّا مُsْلِمُونَ", lao: "ຈົ່ງກ່າວວ່າ: 'ໂອ້ ชาวคัมภีร์, ຈົ່ງມາສູ່ຄຳເວົ້າที่ยุติธรรมระหว่างเราและพวกเจ้า - ວ່າเราจะไม่บูชาสิ่งใดนอกจากอัลลอฮ์, ແລະจะไม่ตั้งภาคีใดๆ กับพระองค์, ແລະจะไม่เอาใครมาเป็นเจ้านอกจากอัลลอฮ์.' ແຕ່ຖ້າພວກເຂົາຫັນໜີ, ຈົ່ງກ່າວວ່າ: 'จงเป็นพยานว่าเราเป็นมุสลิม.'", english: "Say, 'O People of the Scripture, come to a word that is equitable between us and you - that we will not worship except Allah and not associate anything with Him and not take one another as lords instead of Allah.' But if they turn away, then say, 'Bear witness that we are Muslims [submitting to Him].'" },
  { number: "3:65", arabic: "يَا أَهْلَ الْكِتَابِ لِمَ تُحَajُّونَ فِي إِبْرَاهِيمَ وَمَا أُNzِلَتِ التَّوْrَاةُ وَالْإِnjِيلُ إِلَّا مِن بَعْدِهِ ۚ أَfَلَا تَعْقِلُونَ", lao: "ໂອ້ ชาวคัมภีร์, ເປັນຫຍັງພວກເຈົ້າຈຶ່ງຖຽງກັນກ່ຽວກັບອັບຣາຮາມ, ທັງທີ່เตารอตและอินญีลไม่ได้ถูกເປີດເຜີຍລົງมาจนกระทั่งหลังจากเขา? ພວກເຈົ້າບໍ່ຄິດບໍ?", english: "O People of the Scripture, why do you argue about Abraham while the Torah and the Gospel were not revealed until after him? Then will you not reason?" },
  { number: "3:66", arabic: "هَا أَنتُمْ هَٰؤُلَاءِ حَajَjْتُمْ فِيمَا لَكُم بِهِ عِلْمٌ فَلِمَ تُحَajُّونَ فِيمَا لَيْsَ لَكُم بِهِ عِلْمٌ ۚ وَاللَّهُ يَعْلَمُ وَأَنتُمْ لَا تَعْلَمُونَ", lao: "ເບິ່ງແມ, ພວກເຈົ້າຄືຜູ້ທີ່ໄດ້ຖຽງກັນໃນສິ່ງທີ່ພວກເຈົ້າມີຄວາມຮູ້, ແລ້ວເປັນຫຍັງພວກເຈົ້າຈຶ່ງຖຽງກັນໃນສິ່ງທີ່ພວກເຈົ້າບໍ່ມີຄວາມຮູ້? ແລະອັນລໍຫ໌ทรงรู้, ແຕ່ພວກເຈົ້າບໍ່ຮູ້.", english: "Here you are - those who have argued about that of which you have [some] knowledge, but why do you argue about that of which you have no knowledge? And Allah knows, while you know not." },
  { number: "3:67", arabic: "مَا كَانَ إِبْرَاهِيمُ يَهُودِيًّا وَلَا نَصْرَانِيًّا وَلَٰكِن كَانَ حَنِيفًا mُّsْلِمًا وَمَا كَانَ مِنَ الْمُشْرِكِينَ", lao: "ອັບຣາຮາມບໍ່ແມ່ນຊາວຢິວຫຼືຊາວຄຣິດ, ແຕ່ລາວเป็นผู้ที่ยึดมั่นในความจริง, ເປັນมุสลิม. ແລະລາວບໍ່ໄດ້อยู่ในກຸ່ມผู้ที่ตั้งภาคี.", english: "Abraham was neither a Jew nor a Christian, but he was one inclining toward truth, a Muslim [submitting to Allah]. And he was not of the polytheists." },
  { number: "3:68", arabic: "إِنَّ أَوْلَى النَّاسِ بِإِبْرَاهِيمَ لَلَّذِينَ اتَّbَعُوهُ وَهَٰذَا النَّbِيُّ وَالَّذِينَ آمَنُوا ۗ وَاللَّهُ وَلِيُّ الْمُؤْمِنِينَ", lao: "ແທ້ຈິງ, ຜູ້ທີ່ໃກ້ຊິດກັບອັບຣາຮາມທີ່ສຸດຄືຜູ້ທີ່ຕິດຕາມລາວ, และศาสดานี้และผู้ที่ศรัทธา. ແລະອັນລໍຫ໌เป็นผู้พิทักษ์ของผู้ศรัทธา.", english: "Indeed, the most worthy of Abraham among the people are those who followed him [in submission to Allah] and this prophet, and those who believe [in his message]. And Allah is the ally of the believers." },
  { number: "3:69", arabic: "وَدَّت طَّائِfَةٌ mِّنْ أَهْلِ الْكِتَابِ لَوْ يُضِلُّونَكُمْ وَمَا يُضِلُّونَ إِلَّا أَنfُsَهُمْ وَمَا يَشْعُرُونَ", lao: "ກຸ່ມໜຶ່ງຂອງชาวคัมภีร์ปรารถนาที่จะทำให้พวกเจ้าหลงทาง. ແຕ່ພວກເຂົາບໍ່ได้ทำให้ใครหลงทางยกเว้นตัวเอง, ແລະພວກເຂົາບໍ່ຮູ້ສຶກຕົວ.", english: "A faction of the People of the Scripture wish they could lead you astray. But they do not lead astray except themselves, and they perceive [it] not." },
  { number: "3:70", arabic: "يَا أَهْلَ الْكِتَابِ لِمَ تَكْfُرُونَ بِآيَاتِ اللَّهِ وَأَنتُمْ تَشْهَدُونَ", lao: "ໂອ້ ชาวคัมภีร์, ເປັນຫຍັງພວກເຈົ້າຈຶ່ງปฏิเสธສັນຍານของอัลลอฮ์ທັງที่พวกเจ้าเป็นพยาน?", english: "O People of the Scripture, why do you disbelieve in the verses of Allah while you witness [to their truth]?" },
  { number: "3:71", arabic: "يَا أَهْلَ الْكِتَابِ لِمَ تَلْبِسُونَ الْحَقَّ بِالْبَاطِلِ وَتَكْتُمُونَ الْحَقَّ وَأَنتُمْ تَعْلَمُونَ", lao: "ໂອ້ ชาวคัมภีร์, ເປັນຫຍັງພວກເຈົ້າຈຶ່ງປົນຄວາມຈິງກັບຄວາມຕົວະແລະປິດບັງຄວາມຈິງທັງທີ່ພວກເຈົ້າຮູ້?", english: "O People of the Scripture, why do you mix the truth with falsehood and conceal the truth while you know [it]?" },
  { number: "3:72", arabic: "وَقَالَت طَّائِfَةٌ mِّنْ أَهْلِ الْكِتَابِ آمِنُوا بِالَّذِي أُNzِلَ عَلَى الَّذِينَ آمَنُوا وَjْهَ النَّهَarِ وَاكْfُرُوا آخِرَهُ لَعَلَّهُمْ يَرْjِعُونَ", lao: "ແລະກຸ່ມໜຶ່ງຂອງชาวคัมภีร์ກ່າວວ່າ: 'ຈົ່ງເຊື່ອໃນສິ່ງທີ່ถูกເປີດເຜີຍລົງมาให้ผู้ที่ศรัทธาในຕອນເຊົ້າແລະปฏิเสธໃນຕອນແລງ, ເພື່ອພວກເຂົາຈະได้กลับไป.'", english: "And a faction of the People of the Scripture say [to each other], 'Believe in that which was revealed to the believers at the beginning of the day and reject it at its end that perhaps they will abandon their religion,'" },
  { number: "3:73", arabic: "وَلَا تُؤْمِنُوا إِلَّا لِمَن تَبِعَ دِينَكُمْ قُلْ إِنَّ الْهُدَىٰ هُدَى اللَّهِ أَن يُؤْتَىٰ أَحَدٌ mِّثْلَ مَا أُوتِيتُمْ أَوْ يُحَajُّوكُمْ عِندَ رَبِّكُمْ ۗ قُلْ إِنَّ الْfَضْلَ بِيَدِ اللَّهِ يُؤْتِيهِ مَن يَشَاءُ ۗ وَاللَّهُ وَاسِعٌ عَلِيمٌ", lao: "'ແລະຢ່າເຊື່ອໃຜຍົກເວັ້ນຜູ້ທີ່ຕິດຕາມศาสนาของพวกเจ้า.' ຈົ່ງກ່າວວ່າ: 'ແທ້ຈິງ, ທາງນຳທີ່ແທ້ຈິງຄືທາງນຳຂອງອັນລໍຫ໌.' [ຢ່າເຊື່ອ] ວ່າຜູ້ໃດຈະໄດ້รับเหมือนกับที่พวกเจ้าได้รับหรือວ່າພວກເຂົາจะโต้เถียงกับพวกเจ้าต่อหน้าพระเจ้าของพวกเจ้า. ຈົ່ງກ່າວວ່າ: 'ແທ້ຈິງ, ຄວາມโปรดปรานอยู่ในพระหัตถ์ของอัลลอฮ์; ພຣະອົງทรงให้แก่ผู้ที่พระองค์ทรงประสงค์. และอัลลอฮ์ทรงกว้างใหญ่, ทรงรอบรู้.'", english: "'And do not trust except those who follow your religion.' Say, 'Indeed, the [true] guidance is the guidance of Allah. [Do you fear] that someone should be given [knowledge] like you were given or that they should argue with you before your Lord?' Say, 'Indeed, [all] bounty is in the hand of Allah - He grants it to whom He wills. And Allah is all-Encompassing and Knowing.'" },
  { number: "3:74", arabic: "يَخْتَصُّ بِرَحْمَتِهِ مَن يَشَاءُ ۗ وَاللَّهُ ذُو الْfَضْلِ الْعَظِيمِ", lao: "ພຣະອົງทรงเลือกความเมตตาของพระองค์สำหรับผู้ที่พระองค์ทรงประสงค์. ແລະອັນລໍຫ໌ทรงเป็นเจ้าของความโปรดปรานอันยิ่งใหญ่.", english: "He selects for His mercy whom He wills. And Allah is the possessor of great bounty." },
  { number: "3:75", arabic: "وَمِنْ أَهْلِ الْكِتَابِ مَنْ إِن تَأْمَنْهُ بِقِنطَarٍ يُؤَدِّهِ إِلَيْكَ وَمِنْهُم mَّنْ إِن تَأْمَنْهُ بِdِينَarٍ لَّا يُؤَدِّهِ إِلَيْكَ إِلَّا مَا دُمْتَ عَلَيْهِ قَائِمًا ۗ ذَٰلِكَ بِأَنَّهُمْ قَالُوا لَيْsَ عَلَيْنَا فِي الْأُمِّيِّينَ سَبِilٌ وَيَقُولُونَ عَلَى اللَّهِ الْكَذِبَ وَهُمْ يَعْلَمُونَ", lao: "ແລະในหมู่ชาวคัมภีร์, ມີผู้ที่ຖ້າเจ้าฝากทรัพย์สินมากมายไว้กับเขา, ລາວจะคืนให้เจ้า. ແລະในหมู่พวกเขา, ມີผู้ที่ຖ້າเจ้าฝากเหรียญเดียวไว้กับเขา, ລາວจะไม่คืนให้เจ้าจนกว่าเจ้าจะยืนยัน. ນັ້ນเป็นเพราะพวกเขากล่าวว่า: 'ไม่มีข้อผูกมัดใดๆ ต่อเราเกี่ยวกับผู้ที่ไม่รู้หนังสือ.' และพวกเขาพูดเท็จเกี่ยวกับอัลลอฮ์ທັງที่พวกเขารู้.", english: "And among the People of the Scripture is he who, if you entrust him with a great amount [of wealth], he will return it to you. And among them is he who, if you entrust him with a [single] silver coin, he will not return it to you unless you are constantly standing over him [demanding it]. That is because they say, 'There is no blame upon us concerning the unlearned.' And they speak untruth about Allah while they know [it]." },
  { number: "3:76", arabic: "بَلَىٰ مَنْ أَوْfَىٰ بِعَهْدِهِ وَاتَّقَىٰ فَإِنَّ اللَّهَ يُحِبُّ الْمُتَّقِينَ", lao: "ບໍ່, ຜູ້ໃດที่ปฏิบัติตามสัญญาของเขาແລະຢຳເກງ, ແທ້ຈິງອັນລໍຫ໌ทรงรักผู้ที่ยำเกรง.", english: "But yes, whoever fulfills his commitment and fears Allah - then indeed, Allah loves those who fear Him." },
  { number: "3:77", arabic: "إِنَّ الَّذِينَ يَشْتَرُونَ بِعَهْدِ اللَّهِ وَأَيْمَانِهِمْ ثَمَنًا قَلِيلًا أُولَٰئِكَ لَا خَلَاقَ لَهُمْ فِي الْآخِرَةِ وَلَا يُكَلِّمُهُمُ اللَّهُ وَلَا يَنظُرُ إِلَيْهِمْ يَوْmَ الْقِيَامَةِ وَلَا يُزَكِّيهِمْ وَلَهُمْ عَذَابٌ أَلِيمٌ", lao: "ແທ້ຈິງ, ຜູ້ທີ່ຂາຍສັນຍາของอัลลอฮ์และคำสาบานของพวกเขาในราคาถูก, ພວກເຂົາຈະບໍ່ມີສ່ວນแบ่งໃນโลกหน้า. ອັນລໍຫ໌จะไม่ทรงตรัสกับพวกเขา, ບໍ່ทรงมองพวกเขาในวันกิยามะ, ແລະບໍ່ทรงชำระล้างพวกเขา. และพวกเขาจะได้รับการลงโทษที่เจ็บปวด.", english: "Indeed, those who exchange the covenant of Allah and their [own] oaths for a small price will have no share in the Hereafter, and Allah will not speak to them or look at them on the Day of Resurrection, nor will He purify them; and they will have a painful punishment." },
  { number: "3:78", arabic: "وَإِنَّ مِنْهُمْ لَفَرِيقًا يَلْوُونَ أَلْسِنَتَهُم بِالْكِتَابِ لِتَحْسَبُوهُ مِنَ الْكِتَابِ وَمَا هُوَ مِنَ الْكِتَابِ وَيَقُولُونَ هُوَ مِنْ عِندِ اللَّهِ وَمَا هُوَ مِنْ عِndِ اللَّهِ وَيَقُولُونَ عَلَى اللَّهِ الْكَذِبَ وَهُمْ يَعْلَمُونَ", lao: "ແລະແທ້ຈິງ, ในหมู่พวกเขามีกลุ่มหนึ่งที่บิดเบือนลิ้นของพวกเขาเมื่ออ่านคัมภีร์, ເພື່ອให้พวกเจ้าคิดว่ามันมาจากคัมภีร์, ແຕ່ມັນไม่ได้มาจากคัมภีร์. ແລະພວກเขากล่าวว่า: 'มันมาจากอัลลอฮ์', ແຕ່มันไม่ได้มาจากอัลลอฮ์. และพวกเขาพูดเท็จเกี่ยวกับอัลลอฮ์ທັງที่พวกเขารู้.", english: "And indeed, there is among them a party who alter the Scripture with their tongues so you may think it is from the Scripture, but it is not from the Scripture. And they say, 'This is from Allah,' but it is not from Allah. And they speak untruth about Allah while they know." },
  { number: "3:79", arabic: "مَا كَانَ لِبَشَرٍ أَن يُؤْتِيَهُ اللَّهُ الْكِتَابَ وَالْحُكْمَ وَالنُّbُوَّةَ ثُمَّ يَقُولَ لِلنَّاسِ كُونُوا عِبَادًا لِّي مِن دُونِ اللَّهِ وَلَٰكِن كُونُوا رَبَّانِيِّينَ بِمَا كُنتُمْ تُعَلِّمُونَ الْكِتَابَ وَبِمَا كُنتُمْ تَدْرُsُونَ", lao: "ບໍ່ມີມະນຸດຄົນໃດທີ່ອັນລໍຫ໌ทรงให้คัมภีร์, ปัญญา, และการเป็นศาสดา, ແລ້ວเขาจะกล่าวแก่ผู้คนว่า: 'จงเป็นบ่าวของข้าแทนที่จะเป็นของอัลลอฮ์.' ແຕ່[เขาจะกล่าวว่า]: 'จงเป็นผู้ที่อุทิศตนเพื่อพระเจ้า, ດ້ວຍการที่พวกเจ้าสอนคัมภีร์และด้วยการที่พวกเจ้าศึกษา.'", english: "It is not for a human [prophet] that Allah should give him the Scripture and authority and prophethood and then he would say to the people, 'Be servants to me rather than Allah,' but [instead, he would say], 'Be pious scholars of the Lord because of what you have taught of the Scripture and because of what you have studied.'" },
  { number: "3:80", arabic: "وَلَا يَأْمُرَكُمْ أَن تَتَّخِذُوا الْمَلَائِكَةَ وَالنَّbِيِّينَ أَرْbَابًا ۗ أَيَأْمُرُكُم بِالْكُfْرِ بَعْدَ إِذْ أَنتُم mُّsْلِمُونَ", lao: "ແລະລາวจะไม่สั่งให้พวกเจ้าเอาทูตสวรรค์และศาสดามาเป็นเจ้า. ລາວจะสั่งให้พวกเจ้าปฏิเสธหลังจากที่พวกเจ้าเป็นมุสลิมแล้วหรือ?", english: "Nor would he order you to take the angels and the prophets as lords. Would he order you to disbelief after you had been Muslims?" },
  { number: "3:81", arabic: "وَإِذْ أَخَذَ اللَّهُ مِيثَاقَ النَّbِيِّينَ لَمَا آتَيْتُكُم mِّن كِتَابٍ وَحِكْمَةٍ ثُمَّ jَاءَكُمْ رَسُولٌ mُّصَدِّqٌ lِّ مَا مَعَكُمْ لَتُؤْمِنُنَّ بِهِ وَلَتَنصُرُنَّهُ ۚ قَالَ أَأَقْرَرْتُمْ وَأَخَذْتُمْ عَلَىٰ ذَٰلِكُمْ إِصْرِي ۖ قَالُوا أَقْرَرْنَا ۚ قَالَ فَاشْهَدُوا وَأَنَا مَعَكُم mِّنَ الشَّاهِدِينَ", lao: "ແລະເມື່ອອັນລໍຫ໌ได้ทำสัญญาจากศาสดาว่า: 'เมื่อข้าได้ให้คัมภีร์และปัญญาแก่พวกเจ้า, ຫຼັງຈາກນັ້ນມີศาสดามาหาพวกเจ้า, ยืนยันสิ่งที่อยู่กับพวกเจ้า, พวกเจ้าจะต้องเชื่อในเขาและช่วยเหลือเขา.' ພຣະອົງກ່າວວ່າ: 'พวกเจ้ายอมรับແລະรับสัญญาของข้าในเรื่องนี้หรือไม่?' ພວກເຂົາກ່າວວ່າ: 'เรายอมรับ.' ພຣະອົງກ່າວວ່າ: 'ดังนั้นจงเป็นพยาน, และข้าอยู่กับพวกเจ้าในหมู่พยาน.'", english: "And [recall, O People of the Scripture], when Allah took the covenant of the prophets, [saying], 'Whatever I give you of the Scripture and wisdom and then there comes to you a messenger confirming what is with you, you [must] believe in him and support him.' [Allah] said, 'Have you acknowledged and taken upon that My commitment?' They said, 'We have acknowledged.' He said, 'Then bear witness, and I am with you among the witnesses.'" },
  { number: "3:82", arabic: "فَمَن تَوَلَّىٰ بَعْدَ ذَٰلِكَ فَأُولَٰئِكَ هُمُ الْfَاسِقُونَ", lao: "ດັ່ງນັ້ນผู้ใดที่หันหลังกลับหลังจากนั้น, ພວກເຂົາຄືผู้ที่ละเมิด.", english: "And whoever turns away after that - they are the defiantly disobedient." },
  { number: "3:83", arabic: "أَفَغَيْرَ دِينِ اللَّهِ يَبْغُونَ وَلَهُ أَsْلَمَ مَن فِي السَّمَاوَاتِ وَالْأَرْضِ طَوْعًا وَكَرْهًا وَإِلَيْهِ يُرْjَعُونَ", lao: "ພວກເຂົາแสวงหาศาสนาอื่นนอกจากศาสนาของอัลลอฮ์หรือ? ແລະผู้ที่อยู่ในชั้นฟ้าและแผ่นดินยอมจำนนต่อพระองค์, ໂດຍสมัครใจหรือโดยถูกบังคับ, ແລະພວກເຂົາจะถูกนำกลับไปหาพระองค์.", english: "So is it other than the religion of Allah they desire, while to Him have submitted [all] those within the heavens and the earth, willingly or by compulsion, and to Him they will be returned?" },
  { number: "3:84", arabic: "قُلْ آمَنَّا بِاللَّهِ وَمَا أُNzِلَ عَلَيْنَا وَمَا أُNzِلَ عَلَىٰ إِبْرَاهِيمَ وَإِسْمَاعِيلَ وَإِسْحَاقَ وَيَعْقُوبَ وَالْأَسْبَاطِ وَمَا أُوتِيَ مُوسَىٰ وَعِيسَىٰ وَالنَّbِيُّونَ مِن rَّbِّهِمْ لَا نُfَرِّقُ بَيْنَ أَحَدٍ mِّنْهُمْ وَنَحْنُ لَهُ مُsْلِمُونَ", lao: "ຈົ່ງກ່າວວ່າ: 'ພວກເຮົາເຊື່ອในอัลลอฮ์, ແລະสิ่งที่ถูกເປີດເຜີຍລົງมาให้เรา, ແລະสิ่งที่ถูกເປີດເຜີຍລົງมาให้อับราฮัม, อิสมาอีล, อิสฮาก, ยะอ์กูบ, ແລະເຜົ່າຕ່າງໆ, และสิ่งที่มูซาและอีซาและศาสดาได้รับจากพระเจ้าของพวกเขา. เราไม่ແຍກແຍะລະຫວ່າງໃຜໃນพวกเขา, ແລະเรายอมจำนนต่อพระองค์.'", english: "Say, 'We have believed in Allah and in what was revealed to us and what was revealed to Abraham, Ishmael, Isaac, Jacob, and the Descendants, and in what was given to Moses and Jesus and to the prophets from their Lord. We make no distinction between any of them, and we are Muslims [submitting] to Him.'" },
  { number: "3:85", arabic: "وَمَن يَبْتَغِ غَيْرَ الْإِسْلَامِ دِينًا فَلَن يُقْبَلَ مِنْهُ وَهُوَ فِي الْآخِرَةِ مِنَ الْخَاسِرِينَ", lao: "ແລະຜູ້ໃດที่แสวงหาศาสนาอื่นนอกจากอิสลาม, ມັນจะไม่ถูกยอมรับจากเขา, ແລະໃນโลกหน้าเขาจะอยู่ในກຸ່ມผู้ที่ขาดทุน.", english: "And whoever desires other than Islam as religion - never will it be accepted from him, and he, in the Hereafter, will be among the losers." },
  { number: "3:86", arabic: "كَيْfَ يَهْدِي اللَّهُ قَوْmًا كَفَرُوا بَعْدَ إِيمَانِهِمْ وَشَهِدُوا أَنَّ الرَّsُولَ حَقٌّ وَjَاءَهُمُ الْbَيِّنَاتُ ۚ وَاللَّهُ لَا يَهْدِي الْقَوْmَ الظَّالِمِينَ", lao: "ອັນລໍຫ໌จะชี้นำกลุ่มคนที่ปฏิเสธหลังจากที่พวกเขาได้ศรัทธาและเป็นพยานว่าศาสดาเป็นความจริงและหลักฐานที่ชัดเจนได้มาถึงพวกเขาได้อย่างไร? และอัลลอฮ์ไม่ทรงชี้นำผู้ที่ไม่ยุติธรรม.", english: "How shall Allah guide a people who disbelieved after their belief and had witnessed that the Messenger is true and clear signs had come to them? And Allah does not guide the wrongdoing people." },
  { number: "3:87", arabic: "أُولَٰئِكَ jَزَاؤُهُمْ أَنَّ عَلَيْهِمْ لَعْنَةَ اللَّهِ وَالْمَلَائِكَةِ وَالنَّاسِ أَjْمَعِينَ", lao: "พวกเขาคือผู้ที่การตอบแทนของพวกเขาคือคำสาปแช่งของอัลลอฮ์, ทูตสวรรค์, และมนุษย์ทั้งหมดอยู่กับพวกเขา.", english: "Those - their recompense is that upon them is the curse of Allah and the angels and the people, all together." },
  { number: "3:88", arabic: "خَالِدِينَ فِيهَا ۖ لَا يُخَفَّfُ عَنْهُمُ الْعَذَابُ وَلَا هُمْ يُنظَرُونَ", lao: "ພວກເຂົາຈະอยู่ในนั้นตลอดไป. ການລົງໂທດจะไม่ถูกลดหย่อนให้พวกเขา, ແລະພວກເຂົາຈະບໍ່ถูกรอคอย.", english: "Abiding eternally therein. The punishment will not be lightened for them, nor will they be reprieved." },
  { number: "3:89", arabic: "إِلَّا الَّذِينَ تَابُوا مِن بَعْدِ ذَٰلِكَ وَأَصْلَحُوا فَإِنَّ اللَّهَ غَفُورٌ rَّحِيمٌ", lao: "ยกเว้นผู้ที่กลับใจหลังจากนั้นและแก้ไข, ແທ້ຈິງອັນລໍຫ໌ทรงอภัย, ทรงเมตตา.", english: "Except for those who repent after that and correct themselves, for indeed, Allah is Forgiving and Merciful." },
  { number: "3:90", arabic: "إِنَّ الَّذِينَ كَفَرُوا بَعْدَ إِيمَانِهِمْ ثُمَّ ازْدَادُوا كُfْرًا لَّن تُقْبَلَ تَوْbَتُهُمْ وَأُولَٰئِكَ هُمُ الضَّالُّونَ", lao: "ແທ້ຈິງ, ຜູ້ທີ່ປະຕິເສດຫຼັງຈາກທີ່พวกเขาໄດ້ศรัทธาแล้วเพิ่มการปฏิเสธ, ການກັບໃຈของพวกเขาจะไม่ถูกยอมรับ, ແລະພວກເຂົາຄືผู้ที่หลงทาง.", english: "Indeed, those who disbelieve after their belief and then increase in disbelief - never will their [claimed] repentance be accepted, and they are the ones who are astray." },
  { number: "3:91", arabic: "إِنَّ الَّذِينَ كَفَرُوا وَمَاتُوا وَهُمْ كُfَّarٌ فَلَن يُقْبَلَ مِنْ أَحَدِهِم mِّلْءُ الْأَرْضِ ذَهَبًا وَلَوِ افْتَدَىٰ بِهِ ۗ أُولَٰئِكَ لَهُمْ عَذَابٌ أَلِيمٌ وَمَا لَهُم mِّن nَّاصِرِينَ", lao: "ແທ້ຈິງ, ຜູ້ທີ່ປະຕິເສດແລະຕາຍໃນຂະນະທີ່ยังเป็นผู้ปฏิเสธ, ຈະບໍ່ມີໃຜໃນພວກເຂົາที่จะได้รับการยอมรับแม้จะไถ่ตัวเองด้วยทองคำเต็มแผ่นดิน. ພວກເຂົາຈະได้รับการลงโทษที่เจ็บปวด, ແລະພວກເຂົາจะไม่มีผู้ช่วยเหลือ.", english: "Indeed, those who disbelieve and die while they are disbelievers - never would the earth full of gold be accepted from one of them if he were to offer it as a ransom. For them is a painful punishment, and they will have no helpers." },
  { number: "3:92", arabic: "لَن تَنَالُوا الْbِرَّ حَتَّىٰ تُnfِقُوا مِمَّا تُحِبُّونَ ۚ وَمَا تُnfِقُوا مِن شَيْءٍ فَإِنَّ اللَّهَ بِهِ عَلِيمٌ", lao: "ພວກເຈົ້າຈະບໍ່บรรลุความดีงามຈົນກວ່າพวกเจ้าจะบริจาคຈາກสิ่งที่พวกเจ้ารัก. ແລະສິ່ງໃດກໍຕາມที่พวกเจ้าบริจาค, ແທ້ຈິງອັນລໍຫ໌ทรงรู้.", english: "Never will you attain the good [reward] until you spend [in the way of Allah] from that which you love. And whatever you spend - indeed, Allah is Knowing of it." },
  { number: "3:93", arabic: "كُلُّ الطَّعَامِ كَانَ حِلًّا لِّbَنِي إِسْرَائِيلَ إِلَّا مَا حَرَّمَ إِسْرَائِيلُ عَلَىٰ نَفْسِهِ مِن قَبْلِ أَن تُنَzَّلَ التَّوْrَاةُ ۗ قُلْ فَأْتُوا بِالتَّوْrَاةِ فَاتْلُوهَا إِن كُنتُمْ صَادِقِينَ", lao: "ອາຫານທຸກຢ່າງຖືກອະນຸຍາດให้แก่ลูกหลานของอิสราเอล, ยกเว้นสิ่งที่อิสราเอลห้ามตัวเองก่อนที่เตารอตจะถูกเปิดเผย. ຈົ່ງກ່າວວ່າ: 'ຈົ່ງนำเตารอตมาแล้วอ่านมัน, ຫາກพวกเจ้าเป็นผู้ที่สัตย์จริง.'", english: "All food was lawful to the Children of Israel except what Israel had made unlawful to himself before the Torah was revealed. Say, [O Muhammad], 'So bring the Torah and recite it, if you should be truthful.'" },
  { number: "3:94", arabic: "فَمَنِ افْتَرَىٰ عَلَى اللَّهِ الْكَذِبَ مِن بَعْدِ ذَٰلِكَ فَأُولَٰئِكَ هُمُ الظَّالِمُونَ", lao: "ດັ່ງນັ້ນຜູ້ໃດที่สร้างเรื่องเท็จเกี่ยวกับอัลลอฮ์หลังจากนั้น, ພວກເຂົາຄືผู้ที่ไม่ยุติธรรม.", english: "And whoever invents about Allah the lie after that - then it is those who are the wrongdoers." },
  { number: "3:95", arabic: "قُلْ صَدَقَ اللَّهُ ۗ فَاتَّbِعُوا مِلَّةَ إِبْرَاهِيمَ حَنِيفًا وَمَا كَانَ مِنَ الْمُشْرِكِينَ", lao: "ຈົ່ງກ່າວວ່າ: 'ອັນລໍຫ໌ໄດ້ทรงตรัสความจริง. ດັ່ງນັ້ນຈົ່ງปฏิบัติตามศาสนาของอับราฮัม, ผู้ที่ยึดมั่นในความจริง, และเขาไม่ได้อยู่ในກຸ່ມผู้ที่ตั้งภาคี.'", english: "Say, 'Allah has told the truth. So follow the religion of Abraham, inclining toward truth; and he was not of the polytheists.'" },
  { number: "3:96", arabic: "إِنَّ أَوَّلَ بَيْتٍ وُضِعَ لِلنَّاسِ لَلَّذِي بِbَكَّةَ مُbَarَكًا وَهُدًى لِّلْعَالَمِينَ", lao: "ແທ້ຈິງ, ບ້ານແຫ່ງທຳອິດที่ถูกสร้างขึ้นสำหรับมนุษย์ຄືບ້ານที่บักกะ (เมกกะ) - ເປັນບ່ອນที่ได้รับพรและเป็นทางนำสำหรับโลก.", english: "Indeed, the first House [of worship] established for mankind was that at Bakkah - blessed and a guidance for the worlds." },
  { number: "3:97", arabic: "فِيهِ آيَاتٌ بَيِّنَاتٌ mَّقَامُ إِبْرَاهِيمَ ۖ وَمَن دَخَلَهُ كَانَ آمِنًا ۗ وَلِلَّهِ عَلَى النَّاسِ حِjُّ الْbَيْتِ مَنِ اسْتَطَاعَ إِلَيْهِ سَبِilًا ۚ وَمَن كَفَرَ فَإِنَّ اللَّهَ غَنِيٌّ عَنِ الْعَالَمِينَ", lao: "ໃນນັ້ນມີສັນຍານທີ່ຊັດเจน [ເຊັ່ນ:] ສະຖານທີ່ຂອງອັບຣາຮາມ. ແລະຜູ້ໃດที่เข้าไปໃນນັ້ນจะปลอดภัย. ແລະການทำฮัจญ์ที่บ้านเป็นหน้าที่ต่ออัลลอฮ์สำหรับผู้ที่สามารถเดินทางไปได้. ແລະຜູ້ໃດที่ปฏิเสธ, ແທ້ຈິງອັນລໍຫ໌ทรงเป็นอิสระจากโลก.", english: "In it are clear signs [such as] the standing place of Abraham. And whoever enters it shall be safe. And [due] to Allah from the people is a pilgrimage to the House - for whoever is able to find thereto a way. But whoever disbelieves - then indeed, Allah is free from need of the worlds." },
  { number: "3:98", arabic: "قُلْ يَا أَهْلَ الْكِتَابِ لِمَ تَكْfُرُونَ بِآيَاتِ اللَّهِ وَاللَّهُ شَهِيدٌ عَلَىٰ مَا تَعْمَلُونَ", lao: "ຈົ່ງກ່າວວ່າ: 'ໂອ້ ชาวคัมภีร์, ເປັນຫຍັງพวกเจ้าຈຶ່ງปฏิเสธສັນຍານของอัลลอฮ์ທັງที่อัลลอฮ์ทรงเป็นพยานในสิ่งที่พวกเจ้าทำ?'", english: "Say, 'O People of the Scripture, why do you disbelieve in the verses of Allah while Allah is Witness over what you do?'" },
  { number: "3:99", arabic: "قُلْ يَا أَهْلَ الْكِتَابِ لِمَ تَصُdُّونَ عَن سَبِilِ اللَّهِ مَنْ آمَنَ تَبْغُونَهَا عِوَjًا وَأَنتُمْ شُهَدَاءُ ۗ وَمَا اللَّهُ بِغَافِلٍ عَمَّا تَعْمَلُونَ", lao: "ຈົ່ງກ່າວວ່າ: 'ໂອ້ ชาวคัมภีร์, ເປັນຫຍັງพวกเจ้าຈຶ່ງกีดกันผู้ที่ศรัทธาจากหนทางของอัลลอฮ์, ໂດຍພະຍາຍາມทำให้ມັນคดเคี้ยว, ທັງที่พวกเจ้าเป็นพยาน? ແລະອັນລໍຫ໌ไม่ทรงละเลยในสิ่งที่พวกเจ้าทำ.'", english: "Say, 'O People of the Scripture, why do you avert from the way of Allah those who believe, seeking to make it [appear] crooked, while you are witnesses? And Allah is not unaware of what you do.'" },
  { number: "3:100", arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا إِن تُطِيعُوا فَرِيقًا mِّنَ الَّذِينَ أُوتُوا الْكِتَابَ يَرُdُّوكُم بَعْدَ إِيمَانِكُمْ كَافِرِينَ", lao: "ໂອ້ ຜູ້ທີ່ເຊື່ອ, ຫາກพวกเจ้าเชื่อฟังกຸ່ມໜຶ່ງຂອງผู้ที่ได้รับคัมภีร์, ພວກເຂົາจะทำให้พวกเจ้ากลับไปเป็นผู้ปฏิเสธหลังจากที่พวกเจ้าได้ศรัทธาแล้ว.", english: "O you who have believed, if you obey a party of those who were given the Scripture, they would turn you back, after your belief, [to being] unbelievers." },
  { number: "3:101", arabic: "وَكَيْfَ تَكْfُرُونَ وَأَنتُمْ تُتْلَىٰ عَلَيْكُمْ آيَاتُ اللَّهِ وَفِيكُمْ رَسُولُهُ ۗ وَمَن يَعْتَصِم بِاللَّهِ فَقَدْ هُdِيَ إِلَىٰ صِرَاطٍ mُّsْتَقِيمٍ", lao: "ແລະພວກເຈົ້າຈະປະຕິເສດສັດທາໄດ້ແນວໃດ ໃນຂະນະທີ່ອາຍະຕ່າງໆຂອງອັນລໍຖືກອ່ານໃຫ້ພວກເຈົ້າຟັງ ແລະສາດສະດາຂອງພຣະອົງກໍຢູ່ກັບພວກເຈົ້າ? ແລະຜູ້ໃດທີ່ຍຶດໝັ້ນໃນອັນລໍ, ແນ່ນອນລາວໄດ້ຖືກນຳພາໄປສູ່ເສັ້ນທາງທີ່ຊື່ກົງ.", english: "And how could you disbelieve while to you are being recited the verses of Allah and among you is His Messenger? And whoever holds firmly to Allah has [indeed] been guided to a straight path." },
  { number: "3:102", arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ حَقَّ تُقَاتِهِ وَلَا تَمُوتُنَّ إِلَّا وَأَنتُم mُّsْلِمُونَ", lao: "ໂອ້ ຜູ້ທີ່ເຊື່ອ, ຈົ່ງຢຳເກງອັນລໍຢ່າງແທ້ຈິງ ແລະຢ່າຕາຍເວັ້ນເສຍແຕ່ໃນສະພາບທີ່ເປັນມຸດສະລິມ.", english: "O you who have believed, fear Allah as He should be feared and do not die except as Muslims [in submission to Him]." },
  { number: "3:103", arabic: "وَاعْتَصِمُوا بِحَبْلِ اللَّهِ jَمِيعًا وَلَا تَfَرَّقُوا ۚ وَاذْكُرُوا نِعْمَتَ اللَّهِ عَلَيْكُمْ إِذْ كُنتُمْ أَعْدَاءً فَأَلَّfَ بَيْنَ قُلُوبِكُمْ فَأَصْبَحْتُم بِنِعْمَتِهِ إِخْوَانًا وَكُنتُمْ عَلَىٰ شَفَا حُfْرَةٍ mِّنَ النَّarِ فَأَنقَذَكُم mِّنْهَا ۗ كَذَٰلِكَ يُbَيِّنُ اللَّهُ لَكُمْ آيَاتِهِ لَعَلَّكُمْ تَهْتَدُونَ", lao: "ແລະຈົ່ງຍຶດໝັ້ນໃນເຊືອກຂອງອັນລໍທັງໝົດ ແລະຢ່າແຕກແຍກກັນ. ແລະຈົ່ງລະນຶກເຖິງຄວາມໂປດປານຂອງອັນລໍທີ່ມີຕໍ່ພວກເຈົ້າ ເມື່ອພວກເຈົ້າເຄີຍເປັນສັດຕູກັນ ແລ້ວພຣະອົງໄດ້ເຮັດໃຫ້ຫົວໃຈຂອງພວກເຈົ້າເປັນອັນໜຶ່ງອັນດຽວກັນ ແລ້ວພວກເຈົ້າກໍກາຍເປັນອ້າຍນ້ອງກັນດ້ວຍຄວາມໂປດປານຂອງພຣະອົງ. ແລະພວກເຈົ້າເຄີຍຢູ່ເທິງປາກເຫວແຫ່ງໄຟນະລົກ ແລ້ວພຣະອົງໄດ້ຊ່ວຍພວກເຈົ້າໃຫ້ພົ້ນ. ເຊັ່ນນັ້ນແຫຼະ, ອັນລໍຊົງຊີ້ແຈງອາຍະຕ່າງໆໃຫ້ພວກເຈົ້າ, ເພື່ອພວກເຈົ້າຈະໄດ້ຮັບການຊີ້ແນະ.", english: "And hold firmly to the rope of Allah all together and do not become divided. And remember the favor of Allah upon you - when you were enemies and He brought your hearts together and you became, by His favor, brothers. And you were on the edge of a pit of the Fire, and He saved you from it. Thus does Allah make clear to you His verses that you may be guided." },
  { number: "3:104", arabic: "وَلْتَكُن mِّنكُمْ أُمَّةٌ يَدْعُونَ إِلَى الْخَيْرِ وَيَأْمُرُونَ بِالْمَعْرُوfِ وَيَنْهَوْnَ عَنِ الْمُنكَرِ ۚ وَأُولَٰئِكَ هُمُ الْمُfْلِحُونَ", lao: "ແລະຈົ່ງໃຫ້ມີກຸ່ມໜຶ່ງໃນພວກເຈົ້າທີ່ເຊີນຊວນໄປສູ່ຄວາມດີ, ສັ່ງສອນສິ່ງທີ່ຖືກຕ້ອງ, ແລະຫ້າມປາມສິ່ງທີ່ຜິດ. ແລະພວກເຂົາຄືຜູ້ທີ່ໄດ້ຮັບຄວາມສຳເລັດ.", english: "And let there be [arising] from you a nation inviting to [all that is] good, enjoining what is right and forbidding what is wrong, and those will be the successful." },
  { number: "3:105", arabic: "وَلَا تَكُونُوا كَالَّذِينَ تَfَرَّقُوا وَاخْتَلَفُوا مِن بَعْدِ مَا jَاءَهُمُ الْbَيِّنَاتُ ۚ وَأُولَٰئِكَ لَهُمْ عَذَابٌ عَظِيمٌ", lao: "ແລະຢ່າເປັນເໝືອນຜູ້ທີ່ແຕກແຍກແລະຂັດແຍ່ງກັນຫຼັງຈາກທີ່ຫຼັກຖານທີ່ຊັດເຈນໄດ້ມາເຖິງພວກເຂົາ. ແລະພວກເຂົາຈະໄດ້ຮັບການລົງໂທດອັນຍິ່ງໃຫຍ່.", english: "And do not be like the ones who became divided and differed after the clear proofs had come to them. And those will have a great punishment." },
  { number: "3:106", arabic: "يَوْمَ تَبْيَضُّ وُjُوهٌ وَتَسْوَدُّ وُjُوهٌ ۚ فَأَمَّا الَّذِينَ اسْوَدَّتْ وُjُوهُهُمْ أَكَfَرْتُم بَعْدَ إِيمَانِكُم فَذُوقُوا الْعَذَابَ بِمَا كُنتُمْ تَكْfُرُونَ", lao: "ວັນທີ່ບາງໃບໜ້າຈະຂາວ ແລະບາງໃບໜ້າຈະດຳ. ສ່ວນຜູ້ທີ່ໃບໜ້າຂອງພວກເຂົາດຳ, [ຈະຖືກຖາມວ່າ]: 'ພວກເຈົ້າປະຕິເສດຫຼັງຈາກທີ່ໄດ້ເຊື່ອແລ້ວບໍ? ດັ່ງນັ້ນຈົ່ງຊີມລົດຊາດຂອງການລົງໂທດຍ້ອນການປະຕິເສດຂອງພວກເຈົ້າ.'", english: "On the Day [some] faces will turn white and [some] faces will turn black. As for those whose faces turn black, [to them it will be said], 'Did you disbelieve after your belief? Then taste the punishment for what you used to disbelieve.'" },
  { number: "3:107", arabic: "وَأَمَّا الَّذِينَ ابْيَضَّتْ وُjُوهُهُمْ فَfِي رَحْمَةِ اللَّهِ هُمْ فِيهَا خَالِدُونَ", lao: "ແລະສ່ວນຜູ້ທີ່ໃບໜ້າຂອງພວກເຂົາຂາວ, ພວກເຂົາຈະຢູ່ໃນຄວາມເມດຕາຂອງອັນລໍ. ພວກເຂົາຈະຢູ່ໃນນັ້ນຕະຫຼອດໄປ.", english: "But as for those whose faces turn white, they will be within the mercy of Allah. They will abide therein eternally." },
  { number: "3:108", arabic: "تِلْكَ آيَاتُ اللَّهِ نَتْلُوهَا عَلَيْكَ بِالْحَقِّ ۗ وَمَا اللَّهُ يُرِيدُ ظُلْمًا لِّلْعَالَمِينَ", lao: "ນັ້ນຄືອາຍະຕ່າງໆຂອງອັນລໍ, ພວກເຮົາອ່ານມັນໃຫ້ເຈົ້າຟັງດ້ວຍຄວາມຈິງ. ແລະອັນລໍບໍ່ປະສົງທີ່ຈະອະທຳຕໍ່ໂລກ.", english: "These are the verses of Allah. We recite them to you, [O Muhammad], in truth; and Allah wants no injustice for the worlds." },
  { number: "3:109", arabic: "وَلِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۚ وَإِلَى اللَّهِ تُرْjَعُ الْأُمُورُ", lao: "ແລະສິ່ງທີ່ຢູ່ໃນຊັ້ນຟ້າและสิ่งที่อยู่ในแผ่นดินเป็นของອັລລໍຮ໌. ແລະທຸກເລື່ອງจะถูกนำกลับไปหาອັລລໍຮ໌.", english: "To Allah belongs whatever is in the heavens and whatever is on the earth. And to Allah are returned all matters." },
  { number: "3:110", arabic: "كُنتُمْ خَيْرَ أُمَّةٍ أُخْرِjَتْ لِلنَّاسِ تَأْمُرُونَ بِالْمَعْرُوفِ وَتَنْهَوْnَ عَنِ الْمُنكَرِ وَتُؤْمِنُونَ بِاللَّهِ ۗ وَلَوْ آمَنَ أَهْلُ الْكِتَابِ لَكَانَ خَيْرًا لَّهُم ۚ mِّنْهُمُ الْمُؤْمِنُونَ وَأَكْثَرُهُمُ الْfَاسِقُونَ", lao: "ພວກເຈົ້າຄືປະຊາຊາດທີ່ດີທີ່ສຸດທີ່ຖືກສ້າງຂຶ້ນມາສຳລັບມະນຸດ, ໂດຍສັ່ງສອນສິ່ງທີ່ຖືກຕ້ອງ ແລະຫ້າມປາມສິ່ງທີ່ຜິດ, ແລະເຊື່ອໃນອັນລໍ. และถ้าชาวคัมภีร์ได้ศรัทธา, มันก็ดีกว่าสำหรับพวกเขา. ในหมู่พวกเขามีผู้ศรัทธา, ແຕ່ສ່ວນຫຼາຍของพวกเขาเป็นผู้ละเมิด.", english: "You are the best nation produced [as an example] for mankind. You enjoin what is right and forbid what is wrong and believe in Allah. If only the People of the Scripture had believed, it would have been better for them. Among them are believers, but most of them are defiantly disobedient." },
  { number: "3:111", arabic: "لَن يَضُرُّوكُمْ إِلَّا أَذًى ۖ وَإِن يُقَاتِلُوكُمْ يُوَلُّوكُمُ الْأَدْبَarَ ثُمَّ لَا يُnصَرُونَ", lao: "ພວກເຂົາຈະບໍ່ສາມາດທຳຮ້າຍພວກເຈົ້າໄດ້ນອກຈາກການລົບກວນເລັກນ້ອຍ. และถ้าพวกเขาต่อสู้กับพวกเจ้า, ພວກເຂົາຈະຫັນຫຼັງหนี. ຫຼັງຈາກນັ້ນພວກເຂົາຈະບໍ່ໄດ້ຮັບການຊ່ວຍເຫຼືອ.", english: "They will not harm you except for [some] annoyance. And if they fight you, they will show you their backs; then they will not be aided." },
  { number: "3:112", arabic: "ضُرِبَتْ عَلَيْهِمُ الذِّلَّةُ أَيْنَ مَا ثُقِfُوا إِلَّا بِحَبْلٍ mِّنَ اللَّهِ وَحَبْلٍ mِّنَ النَّاسِ وَbَاءُوا بِغَضَبٍ mِّنَ اللَّهِ وَضُرِبَتْ عَلَيْهِمُ الْمَسْكَنَةُ ۚ ذَٰلِكَ بِأَنَّهُمْ كَانُوا يَكْfُرُونَ بِآيَاتِ اللَّهِ وَيَقْتُلُونَ الْأَنbِيَاءَ بِغَيْرِ حَقٍّ ۚ ذَٰلِكَ بِمَا عَصَوا وَّكَانُوا يَعْتَدُونَ", lao: "ความอัปยศได้ถูกกำหนดไว้สำหรับพวกเขาไม่ว่าพวกเขาจะอยู่ที่ไหน, ยกเว้นด้วยเชือกจากอัลลอฮ์และเชือกจากผู้คน. ແລະພວກເຂົາໄດ້ຮັບຄວາມໂກດແຄ້ນຈາກອັນລໍ, ແລະຄວາມທຸກຍາກໄດ້ຖືກກຳນົດໃຫ້ພວກເຂົາ. ນັ້ນເປັນເພາະວ່າພວກເຂົາປະຕິເສດອາຍະຕ່າງໆຂອງອັນລໍແລະຂ້າສາດສະດາໂດຍບໍ່ຍຸດຕິທຳ. ນັ້ນເປັນເພາະວ່າພວກເຂົາບໍ່ເຊື່ອຟັງและเคยละเมิด.", english: "They have been put under humiliation wherever they are overtaken, except for a covenant from Allah and a rope from the Muslims. And they have drawn upon themselves anger from Allah and have been put under destitution. That is because they disbelieved in the verses of Allah and killed the prophets without right. That is because they disobeyed and used to transgress." },
  { number: "3:113", arabic: "لَيْsُوا سَوَاءً ۗ mِّنْ أَهْلِ الْكِتَابِ أُمَّةٌ قَائِمَةٌ يَتْلُونَ آيَاتِ اللَّهِ آنَاءَ اللَّيْلِ وَهُمْ يَsْjُdُونَ", lao: "ພວກເຂົາບໍ່ເໝືອນກັນ. ในหมู่ชาวคัมภีร์, ມີກຸ່ມໜຶ່ງที่ยืนหยัด, อ่านอายะต่างๆ ของอัลลอฮ์ในยามค่ำคืนและกราบไหว้.", english: "They are not [all] the same; among the People of the Scripture is a community standing [in obedience], reciting the verses of Allah during periods of the night and prostrating [in prayer]." },
  { number: "3:114", arabic: "يُؤْمِنُونَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ وَيَأْمُرُونَ بِالْمَعْرُوfِ وَيَنْهَوْnَ عَنِ الْمُنكَرِ وَيُsَarِعُونَ فِي الْخَيْرَاتِ ۖ وَأُولَٰئِكَ مِنَ الصَّالِحِينَ", lao: "ພວກເຂົາເຊື່ອในอัลลอฮ์และวันสุดท้าย, ສັ່ງສອນສິ່ງທີ່ຖືກຕ້ອງและห้ามปรามสิ่งที่ผิด, และรีบเร่งในการทำความดี. ແລະພວກເຂົາอยู่ในກຸ່ມผู้ที่ชอบธรรม.", english: "They believe in Allah and the Last Day, and they enjoin what is right and forbid what is wrong and hasten to good deeds. And those are among the righteous." },
  { number: "3:115", arabic: "وَمَا يَfْعَلُوا مِنْ خَيْرٍ فَلَن يُكْfَرُوهُ ۗ وَاللَّهُ عَلِيمٌ بِالْمُتَّقِينَ", lao: "และความดีใดๆ ที่พวกเขาทำ, ມັນຈະບໍ່ຖືກປະຕິເສດ. และอัลลอฮ์ทรงรอบรู้เกี่ยวกับผู้ที่ยำเกรง.", english: "And whatever good they do - never will it be removed from them. And Allah is Knowing of the righteous." },
  { number: "3:116", arabic: "إِنَّ الَّذِينَ كَفَرُوا لَن تُغْنِيَ عَنْهُمْ أَمْوَالُهُمْ وَلَا أَوْلَادُهُم mِّنَ اللَّهِ شَيْئًا ۖ وَأُولَٰئِكَ أَصْحَابُ النَّarِ ۖ هُمْ فِيهَا خَالِدُونَ", lao: "ແທ້ຈິງ, ຜູ້ທີ່ປະຕິເສດ, ຊັບສິນຂອງພວກເຂົາແລະລູກຫຼານຂອງພວກເຂົາຈະບໍ່สามารถຊ່ວຍพวกเขาจากอัลลอฮ์ได้เลย. ແລະພວກເຂົາຄືชาวนรก; ພວກເຂົາจะอยู่ในນັ້ນຕະຫຼອດໄປ.", english: "Indeed, those who disbelieve - never will their wealth or their children avail them against Allah at all, and those are the companions of the Fire; they will abide eternally therein." },
  { number: "3:117", arabic: "مَثَلُ مَا يُnfِقُونَ فِي هَٰذِهِ الْحَيَاةِ الدُّنْيَا كَمَثَلِ رِيحٍ فِيهَا صِرٌّ أَصَابَتْ حَرْثَ قَوْmٍ ظَلَمُوا أَنfُsَهُمْ فَأَهْلَكَتْهُ ۚ وَمَا ظَلَمَهُمُ اللَّهُ وَلَٰكِنْ أَنfُsَهُمْ يَظْلِمُونَ", lao: "ຕົວຢ່າງຂອງສິ່ງທີ່ພວກເຂົາບໍລິຈາກในຊີວິດນີ້ຄືກັບลมที่มีความเย็นจัดพัดมาทำลายพืชผลของกลุ่มคนที่ทำร้ายตัวเอง. และอัลลอฮ์ไม่ทรงทำร้ายพวกเขา, ແຕ່พวกเขาทຳຮ້າຍຕົວເອງ.", english: "The example of what they spend in this worldly life is like that of a wind containing frost which strikes the harvest of a people who have wronged themselves and destroys it. And Allah has not wronged them, but they wrong themselves." },
  { number: "3:118", arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَتَّخِذُوا بِطَانَةً mِّن دُونِكُمْ لَا يَأْلُونَكُمْ خَبَالًا وَدُّوا مَا عَنِتُّمْ قَدْ بَدَتِ الْbَغْضَاءُ مِنْ أَfْوَاهِهِمْ وَمَا تُخْfِي صُdُورُهُمْ أَكْبَرُ ۚ قَدْ بَيَّnَّا لَكُمُ الْآيَاتِ ۖ إِن كُنتُمْ تَعْقِلُونَ", lao: "ໂອ້ ຜູ້ທີ່ເຊື່ອ, ຢ່າເອົາຄົນທີ່ບໍ່ແມ່ນພວກເຈົ້າມາເປັນທີ່ປຶກສາ. ພວກເຂົາຈະບໍ່ລົ້ມເຫລວໃນການສ້າງຄວາມເສຍຫາຍໃຫ້ພວກເຈົ້າ. ພວກເຂົາປາດຖະຫນາສິ່ງທີ່ຈະເຮັດໃຫ້ພວກເຈົ້າລຳບາກ. ຄວາມກຽດຊັງໄດ້ປາກົດອອກມາຈາກປາກຂອງພວກເຂົາ, ແລະສິ່ງທີ່ຫົວໃຈຂອງພວກເຂົາປິດບັງນັ້ນໃຫຍ່ກວ່າ. ພວກເຮົາໄດ້ຊີ້ແຈງອາຍະຕ່າງໆໃຫ້ພວກເຈົ້າ, ຖ້າພວກເຈົ້າຄິດ.", english: "O you who have believed, do not take as intimates those other than yourselves, for they will not spare you [any] ruin. They wish you would have hardship. Hatred has already appeared from their mouths, and what their breasts conceal is greater. We have certainly made clear to you the signs, if you will use reason." },
  { number: "3:119", arabic: "هَا أَنتُمْ أُولَاءِ تُحِبُّونَهُمْ وَلَا يُحِبُّونَكُمْ وَتُؤْمِنُونَ بِالْكِتَابِ كُلِّهِ وَإِذَا لَقُوكُمْ قَالُوا آمَنَّا وَإِذَا خَلَوْا عَضُّوا عَلَيْكُمُ الْأَنَامِلَ مِنَ الْغَيْظِ ۚ قُلْ مُوتُوا بِغَيْظِكُمْ ۗ إِنَّ اللَّهَ عَلِيمٌ بِذَاتِ الصُّdُورِ", lao: "ເບິ່ງແມ, ພວກເຈົ້າຮັກພວກເຂົາ, ແຕ່ພວກເຂົາບໍ່ຮັກພວກເຈົ້າ, ແລະພວກເຈົ້າເຊື່ອໃນຄຳພີທັງໝົດ. ແລະເມື່ອພວກເຂົາພົບພວກເຈົ້າ, ພວກເຂົາກ່າວວ່າ: 'ພວກເຮົາເຊື່ອແລ້ວ.' ແຕ່ເມື່ອພວກເຂົາຢູ່ຕາມລຳພັງ, ພວກເຂົາກັດນິ້ວມືໃສ່ພວກເຈົ້າດ້ວຍຄວາມໂກດແຄ້ນ. ຈົ່ງກ່າວວ່າ: 'ຈົ່ງຕາຍດ້ວຍຄວາມໂກດແຄ້ນຂອງພວກເຈົ້າ.' ແທ້ຈິງອັນລໍຊົງຮອບຮູ້ในสิ่งที่อยู่ในใจ.", english: "Here you are loving them but they do not love you, and you believe in the whole of the Scripture. And when they meet you, they say, 'We believe.' But when they are alone, they bite their fingertips at you in rage. Say, 'Die in your rage. Indeed, Allah is Knowing of that within the breasts.'" },
  { number: "3:120", arabic: "إِن تَمْسَسْكُمْ حَسَنَةٌ تَسُؤْهُمْ وَإِن تُصِبْكُمْ سَيِّئَةٌ يَfْرَحُوا بِهَا ۖ وَإِن تَصْبِرُوا وَتَتَّقُوا لَا يَضُرُّكُمْ كَيْdُهُمْ شَيْئًا ۗ إِنَّ اللَّهَ بِمَا يَعْمَلُونَ مُحِيطٌ", lao: "ຖ້າຄວາມດີເກີດຂຶ້ນກັບພວກເຈົ້າ, ມັນເຮັດໃຫ້ພວກເຂົາໂສກເສົ້າ. ແລະຖ້າຄວາມຊົ່ວເກີດຂຶ້ນກັບພວກເຈົ້າ, ພວກເຂົາກໍດີໃຈ. ແຕ່ຖ້າພວກເຈົ້າອົດທົນແລະຢຳເກງ, ແຜນການຂອງພວກເຂົາຈະບໍ່ສາມາດທຳຮ້າຍພວກເຈົ້າໄດ້. ແທ້ຈິງອັນລໍຊົງรอบรู้ในสิ่งที่พวกเขาทำ.", english: "If good touches you, it distresses them; but if harm strikes you, they rejoice at it. And if you are patient and fear Allah, their plot will not harm you at all. Indeed, Allah is encompassing of what they do." },
  { number: "3:121", arabic: "وَإِذْ غَدَوْتَ مِنْ أَهْلِكَ تُbَوِّئُ الْمُؤْمِنِينَ مَقَاعِدَ لِلْقِتَالِ ۗ وَاللَّهُ سَمِيعٌ عَلِيمٌ", lao: "ແລະຈົ່ງລະນຶກເຖິງເມື່ອເຈົ້າອອກຈາກຄອບຄົວຂອງເຈົ້າໃນຕອນເຊົ້າ ເພື່ອຈັດຕັ້ງຜູ້ສັດທາໃນຕຳແໜ່ງສຳລັບການສູ້ຮົບ. ແລະອັນລໍຊົງໄດ້ຍິນ, ຊົງຮອບຮູ້.", english: "And [remember] when you, [O Muhammad], left your family in the morning to post the believers at their stations for the battle [of Uhud]. And Allah is Hearing and Knowing." },
  { number: "3:122", arabic: "إِذْ هَمَّت طَّائِfَتَانِ مِنكُمْ أَن تَfْشَلَا وَاللَّهُ وَلِيُّهُمَا ۗ وَعَلَى اللَّهِ فَلْيَتَوَكَّلِ الْمُؤْمِنُونَ", lao: "ເມື່ອສອງກຸ່ມໃນພວກເຈົ້າເກືອບຈະລົ້ມເຫລວ, ແຕ່ອັນລໍເປັນຜູ້ປົກປ້ອງຂອງພວກເຂົາ. ແລະຜູ້ສັດທາຄວນໄວ້ວາງໃຈในอัลลอฮ์.", english: "When two parties among you were about to lose courage, but Allah was their ally. And upon Allah let the believers rely." },
  { number: "3:123", arabic: "وَلَقَدْ نَصَرَكُمُ اللَّهُ بِbَدْرٍ وَأَنتُمْ أَذِلَّةٌ ۖ فَاتَّقُوا اللَّهَ لَعَلَّكُمْ تَشْكُرُونَ", lao: "ແລະແນ່ນອນ, ອັນລໍໄດ້ຊົງຊ່ວຍເຫຼືອພວກເຈົ້າที่ບັດຣ໌, ໃນຂະນະທີ່ພວກເຈົ້າອ່ອນແອ. ດັ່ງນັ້ນຈົ່ງຢຳເກງອັນລໍ, ເພື່ອພວກເຈົ້າຈະໄດ້ຂອບໃຈ.", english: "And already had Allah given you victory at [the battle of] Badr while you were few in number. Then fear Allah; perhaps you will be grateful." },
  { number: "3:124", arabic: "إِذْ تَقُولُ لِلْمُؤْمِنِينَ أَلَن يَكْfِيَكُمْ أَن يُمِدَّكُمْ رَبُّكُم بِثَلَاثَةِ آلَافٍ mِّنَ الْمَلَائِكَةِ مُnzَلِينَ", lao: "ເມື່ອເຈົ້າກ່າວແກ່ຜູ້ສັດທາວ່າ: 'ມັນບໍ່ພຽງພໍບໍທີ່ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຈົ້າຈະຊ່ວຍເຫຼືອພວກເຈົ້າດ້ວຍທູດສະຫວັນສາມພັນອົງທີ່ถูกส่งลงมา?'", english: "[Remember] when you said to the believers, 'Is it not sufficient for you that your Lord should reinforce you with three thousand angels sent down?'" },
  { number: "3:125", arabic: "بَلَىٰ ۚ إِن تَصْبِرُوا وَتَتَّقُوا وَيَأْتُوكُم mِّن فَوْrِهِمْ هَٰذَا يُمْdِدْكُمْ رَبُّكُم بِخَمْسَةِ آلَافٍ mِّنَ الْمَلَائِكَةِ مُsَوِّمِينَ", lao: "ແມ່ນແລ້ວ, ຖ້າພວກເຈົ້າອົດທົນແລະຢຳເກງ, ແລະພວກເຂົາโจมตีพวกเจ้าอย่างກະທັນຫັນ, ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຈົ້າจะຊ່ວຍເຫຼືອพวกเจ้าด้วยທູດສະຫວັນຫ້າພັນອົງที่มีเครื่องหมาย.", english: "Yes, if you remain patient and conscious of Allah and the enemy come upon you [attacking] in rage, your Lord will reinforce you with five thousand angels having marks [of distinction]" },
  { number: "3:126", arabic: "وَمَا jَعَلَهُ اللَّهُ إِلَّا بُشْرَىٰ لَكُمْ وَلِتَطْمَئِنَّ قُلُوبُكُم بِهِ ۗ وَمَا النَّصْرُ إِلَّا مِنْ عِndِ اللَّهِ الْعَzِيزِ الْحَكِيمِ", lao: "ແລະອັນລໍບໍ່ໄດ້ເຮັດສິ່ງນີ້ຍົກເວັ້ນເປັນຂ່າວດີสำหรับพวกเจ้าและเพื่อให้ຫົວใจของพวกเจ้าสงบ. ແລະໄຊຊະນະບໍ່ได้มาจากໃຜນອກຈາກຈາກอัลลอฮ์, ผู้ทรงอำนาจ, ผู้ทรงมีปัญญา.", english: "And Allah made it not except as good tidings for you and to reassure your hearts thereby. And victory is not except from Allah, the Exalted in Might, the Wise." },
  { number: "3:127", arabic: "لِيَقْطَعَ طَرَfًا mِّنَ الَّذِينَ كَفَرُوا أَوْ يَكْبِتَهُمْ فَيَنqَلِبُوا خَائِبِينَ", lao: "ເພື່ອຕັດສ່ວນໜຶ່ງของผู้ที่ปฏิเสธหรือເພື່ອເຮັດให้ພວກເຂົາอัปยศ, ແລ້ວພວກເຂົາຈະกลับไปเป็นผู้แพ้.", english: "That He might cut off a party of those who disbelieved or suppress them so that they turn back disappointed." },
  { number: "3:128", arabic: "لَيْsَ لَكَ مِنَ الْأَمْرِ شَيْءٌ أَوْ يَتُوبَ عَلَيْهِمْ أَوْ يُعَذِّbَهُمْ فَإِنَّهُمْ ظَالِمُونَ", lao: "ເຈົ້າບໍ່มีอำนาจในเรื่องนี้. ພຣະອົງอาจจะอภัยให้พวกเขาหรือลงโทษพวกเขา, ເພາະແທ້ຈິງພວກເຂົາเป็นผู้ที่ไม่ยุติธรรม.", english: "Not for you, [O Muhammad, is any] part of the matter; whether He turns to them in mercy or punishes them, for indeed, they are wrongdoers." },
  { number: "3:129", arabic: "وَلِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۚ يَغْfِرُ لِمَن يَشَاءُ وَيُعَذِّbُ مَن يَشَاءُ ۚ وَاللَّهُ غَفُورٌ rَّحِيمٌ", lao: "และສິ່ງທີ່ຢູ່ໃນຊັ້ນຟ້າและสิ่งที่อยู่ในแผ่นดินเป็นของອັລລໍຮ໌. ພຣະອົງทรงอภัยให้ผู้ที่พระองค์ทรงประสงค์ແລະลงโทษผู้ที่พระองค์ทรงประสงค์. ແລະອັລລໍຮ໌ทรงอภัย, ทรงเมตตา.", english: "To Allah belongs whatever is in the heavens and whatever is on the earth. He forgives whom He wills and punishes whom He wills. And Allah is Forgiving and Merciful." },
  { number: "3:130", arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَأْكُلُوا الرِّbَا أَضْعَافًا mُّضَاعَفَةً ۖ وَاتَّقُوا اللَّهَ لَعَلَّكُمْ تُfْلِحُونَ", lao: "ໂອ້ ຜູ້ທີ່ເຊື່ອ, ຢ່າກິນດອກເບี้ย, ເພີ່ມຂຶ້ນຫຼາຍເທົ່າ. และจงยำเกรงอัลลอฮ์, ເພື່ອພວກเจ้าจะได้ประสบความสำเร็จ.", english: "O you who have believed, do not consume usury, doubled and multiplied, but fear Allah that you may be successful." },
  { number: "3:131", arabic: "وَاتَّقُوا النَّarَ الَّتِي أُعِدَّتْ لِلْكَافِرِينَ", lao: "ແລະຈົ່ງຢຳເກງໄຟນະລົກທີ່ຖືກກະກຽມໄວ້ສຳລັບຜູ້ປະຕິເສດ.", english: "And fear the Fire, which has been prepared for the disbelievers." },
  { number: "3:132", arabic: "وَأَطِيعُوا اللَّهَ وَالرَّsُولَ لَعَلَّكُمْ تُرْحَمُونَ", lao: "ແລະຈົ່ງເຊື່ອຟັງອັນລໍແລະສາດສະດາ, ເພື່ອพวกเจ้าจะได้รับความเมตตา.", english: "And obey Allah and the Messenger that you may obtain mercy." },
  { number: "3:133", arabic: "وَsَarِعُوا إِلَىٰ مَغْfِرَةٍ mِّن rَّbِّكُمْ وَjَنَّةٍ عَرْضُهَا السَّمَاوَاتُ وَالْأَرْضُ أُعِدَّتْ لِلْمُتَّقِينَ", lao: "ແລະจงรีบเร่งไปสู่การอภัยจากพระเจ้าของพวกเจ้าและสวนสวรรค์ที่กว้างใหญ่เท่าชั้นฟ้าและแผ่นดิน, ที่ถูกກະກຽມໄວ້ສຳລັບผู้ที่ยำเกรง.", english: "And hasten to forgiveness from your Lord and a garden as wide as the heavens and earth, prepared for the righteous" },
  { number: "3:134", arabic: "الَّذِينَ يُnfِقُونَ فِي السَّrَّاءِ وَالضَّrَّاءِ وَالْكَاظِمِينَ الْغَيْظَ وَالْعَافِينَ عَنِ النَّاسِ ۗ وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ", lao: "ຜູ້ที่บริจาคทั้งในยามสุขและยามทุกข์, ແລະผู้ที่ระงับความโกรธ, และผู้ที่ให้อภัยผู้คน. ແລະອັລລໍຮ໌ทรงรักผู้ที่ทำความดี.", english: "Who spend [in the cause of Allah] during ease and hardship and who restrain anger and who pardon the people - and Allah loves the doers of good;" },
  { number: "3:135", arabic: "وَالَّذِينَ إِذَا فَعَلُوا فَاحِشَةً أَوْ ظَلَمُوا أَنfُsَهُمْ ذَكَرُوا اللَّهَ فَاسْتَغْfَرُوا لِذُنُوبِهِمْ وَمَن يَغْfِرُ الذُّنُوبَ إِلَّا اللَّهُ وَلَمْ يُصِرُّوا عَلَىٰ مَا فَعَلُوا وَهُمْ يَعْلَمُونَ", lao: "ແລະຜູ້ที่ເມື່ອทำความผิดหรือทำร้ายตัวเองแล้วระลึกถึงอัลลอฮ์และขออภัยในบาปของพวกเขา - และใครจะอภัยบาปได้นอกจากอัลลอฮ์? - และไม่ยืนกรานในสิ่งที่พวกเขาได้ทำในขณะที่พวกเขารู้.", english: "And those who, when they commit an immorality or wrong themselves [by transgression], remember Allah and seek forgiveness for their sins - and who can forgive sins except Allah? - and [who] do not persist in what they have done while they know." },
  { number: "3:136", arabic: "أُولَٰئِكَ jَzَاؤُهُم mَّغْfِرَةٌ mِّن rَّbِّهِمْ وَjَنَّاتٌ تَjْرِي مِن تَحْتِهَا الْأَنْهَarُ خَالِدِينَ فِيهَا ۚ وَنِعْمَ أَjْرُ الْعَامِلِينَ", lao: "พวกเขาคือผู้ที่การตอบแทนของพวกเขาคือการอภัยจากพระเจ้าของพวกเขาและสวนสวรรค์ที่มีแม่น้ำไหลผ่าน, ພວກເຂົາຈະຢູ່ໃນນັ້ນຕະຫຼອດໄປ. และช่างเป็นรางวัลที่ดีสำหรับผู้ที่ทำงาน!", english: "Those - their reward is forgiveness from their Lord and gardens beneath which rivers flow, wherein they will abide eternally; and excellent is the reward of the [righteous] workers." },
  { number: "3:137", arabic: "قَدْ خَلَتْ مِن قَبْلِكُمْ sُنَنٌ فَsِيرُوا فِي الْأَرْضِ فَانظُرُوا كَيْfَ كَانَ عَاقِبَةُ الْمُكَذِّbِينَ", lao: "ແນ່ນอน, ວິຖີຊີວິດໄດ້ຜ່ານไปກ່ອນหน้าพวกเจ้าแล้ว. ດັ່ງນັ້ນจงเดินทางไปในแผ่นดินแล้วดูว่าผลสุดท้ายของผู้ที่ปฏิเสธเป็นอย่างไร.", english: "Similar situations [as yours] have passed on before you, so proceed throughout the land and observe how was the end of those who denied." },
  { number: "3:138", arabic: "هَٰذَا بَيَانٌ لِّلنَّاسِ وَهُدًى وَمَوْعِظَةٌ لِّلْمُتَّقِينَ", lao: "ນີ້ຄືຄຳຊี้ແຈງสำหรับผู้คนແລະເປັນທາງນຳและคำตักเตือนสำหรับผู้ที่ยำเกรง.", english: "This is a clear statement to the people, and a guidance and instruction for the righteous." },
  { number: "3:139", arabic: "وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنتُمُ الْأَعْلَوْnَ إِن كُنتُم mُّؤْمِنِينَ", lao: "ແລະຢ່າອ່ອນແອและຢ່າໂສກເສົ້າ, ແລະพวกเจ้าจะเหนือกว่าຫາກพวกเจ้าເປັນຜູ້ศรัທธา.", english: "So do not weaken and do not grieve, and you will be superior if you are [true] believers." },
  { number: "3:140", arabic: "إِن يَمْسَسْكُمْ قَرْحٌ فَقَدْ مَسَّ الْقَوْmَ قَرْحٌ mِّثْلُهُ ۚ وَتِلْكَ الْأَيَّامُ نُdَاوِلُهَا بَيْنَ النَّاسِ وَلِيَعْلَمَ اللَّهُ الَّذِينَ آمَنُوا وَيَتَّخِذَ مِنكُمْ شُهَدَاءَ ۗ وَاللَّهُ لَا يُحِبُّ الظَّالِمِينَ", lao: "ຫາກພວກเจ้าได้รับบาดแผล, ກຸ່ມຄົນອື່ນກໍได้รับบาดแผลເໝືອນກັນ. ແລະວັນเวลาເຫຼົ່ານັ້ນ, ພວກເຮົາสลับสับเปลี่ยนมันระหว่างผู้คน, ເພື່ອอัลลอฮ์จะทรงรู้ผู้ที่ศรัทธาและทรงเลือกพยานจากพวกเจ้า. ແລະອັລລໍຮ໌ບໍ່ทรงรักผู้ที่ไม่ยุติธรรม.", english: "If a wound should touch you - there has already touched the [opposing] people a wound similar to it. And these days [of varying conditions] We alternate among the people so that Allah may make evident those who believe and [may] take to Himself from among you martyrs - and Allah does not like the wrongdoers -" },
  { number: "3:141", arabic: "وَلِيُمَحِّصَ اللَّهُ الَّذِينَ آمَنُوا وَيَمْحَقَ الْكَافِرِينَ", lao: "และเพื่ออัลลอฮ์จะทรงชำระล้างผู้ที่ศรัทธาและทำลายผู้ที่ไม่เชื่อ.", english: "And that Allah may purify the believers [through trials] and destroy the disbelievers." },
  { number: "3:142", arabic: "أَمْ حَسِبْتُمْ أَن تَدْخُلُوا الْjَنَّةَ وَلَمَّا يَعْلَمِ اللَّهُ الَّذِينَ jَاهَدُوا مِنكُمْ وَيَعْلَمَ الصَّابِرِينَ", lao: "หรือພວກเจ้าคิดว่าจะได้เข้าสวรรค์โดยที่อัลลอฮ์ยังไม่ทรงรู้ผู้ที่ต่อสู้ในหมู่พวกเจ้าและทรงรู้ผู้ที่อดทน?", english: "Or do you think that you will enter Paradise while Allah has not yet made evident those of you who fight in His cause and made evident those who are patient?" },
  { number: "3:143", arabic: "وَلَقَدْ كُنتُمْ تَمَنَّوْnَ الْمَوْتَ مِن قَبْلِ أَن تَلْقَوْهُ فَقَدْ رَأَيْتُمُوهُ وَأَنتُمْ تَنظُرُونَ", lao: "และແນ່ນອນ, ພວກเจ้าเคยปรารถนาความตายก่อนที่จะได้พบมัน. ດັ່ງນັ້ນพวกเจ้าได้เห็นมันแล้วในขณะที่กำลังมองดู.", english: "And you had certainly wished for death before you met it. So you have seen it while you were looking on." },
  { number: "3:144", arabic: "وَمَا مُحَمَّdٌ إِلَّا رَسُولٌ قَدْ خَلَتْ مِن قَبْلِهِ الرُّsُلُ ۚ أَfَإِن mَّاتَ أَوْ قُتِلَ انقَلَبْتُمْ عَلَىٰ أَعْقَابِكُمْ ۚ وَمَن يَنqَلِبْ عَلَىٰ عَقِبَيْهِ فَلَن يَضُرَّ اللَّهَ شَيْئًا ۗ وَsَيَjْzِي اللَّهُ الشَّاكِرِينَ", lao: "ມູຮຳມັດເປັນພຽງສາດສະດາຄົນໜຶ່ງ, ກ່ອນຫນ້ານັ້ນກໍมีศาสดาหลายท่านได้ล่วงลับไปแล้ว. ຫາກລາวຕາຍหรือถูกฆ่า, ພວກเจ้าจะหันหลังกลับหรือ? ແລະຜູ້ໃດທີ່ຫັນຫຼັງกลับ, ລາວจะไม่ทำร้ายอัลลอฮ์เลย. และอัลลอฮ์จะทรงตอบแทนผู้ที่ขอบคุณ.", english: "Muhammad is not but a messenger. [Other] messengers have passed on before him. So if he was to die or be killed, would you turn back on your heels [to unbelief]? And he who turns back on his heels will never harm Allah at all; but Allah will reward the grateful." },
  { number: "3:145", arabic: "وَمَا كَانَ لِنَفْسٍ أَن تَمُوتَ إِلَّا بِإِذْنِ اللَّهِ كِتَابًا mُّؤَjَّلًا ۗ وَمَن يُrِدْ ثَوَابَ الدُّنْيَا نُؤْتِهِ مِنْهَا وَمَن يُrِدْ ثَوَابَ الْآخِرَةِ نُؤْتِهِ مِنْهَا ۚ وَsَنَjْzِي الشَّاكِرِينَ", lao: "ແລະไม่มีใครจะตายได้ยกเว้นด้วยการอนุมัติของอัลลอฮ์, ໃນເວລາที่ถูกกำหนดไว้. และผู้ใดที่ต้องการรางวัลในโลกนี้, เราจะให้เขา. และผู้ใดที่ต้องการรางวัลในโลกหน้า, เราจะให้เขา. และเราจะตอบแทนผู้ที่ขอบคุณ.", english: "And it is not [possible] for one to die except by permission of Allah at a decree determined. And whoever desires the reward of this world - We will give him thereof; and whoever desires the reward of the Hereafter - We will give him thereof. And We will reward the grateful." },
  { number: "3:146", arabic: "وَكَأَيِّن mِّن nَّbِيٍّ قَاتَلَ مَعَهُ رِبِّيُّونَ كَثِيرٌ فَمَا وَهَنُوا لِمَا أَصَابَهُمْ فِي سَبِilِ اللَّهِ وَمَا ضَعُfُوا وَمَا اسْتَكَانُوا ۗ وَاللَّهُ يُحِبُّ الصَّابِرِينَ", lao: "ແລະมีศาสดาຈັກຄົນที่ต่อสู้พร้อมกับผู้ศรัทธาจำนวนมาก, ແຕ່ພວກເຂົາບໍ່ໄດ້ອ່ອນແອຍ້ອນສິ່ງที่เกิดขึ้นกับพวกเขาในหนทางของอัลลอฮ์, ບໍ່ໄດ້ອ່ອນແອ, และไม่ยอมแพ้. ແລະອັລລໍຮ໌ทรงรักผู้ที่อดทน.", english: "And how many a prophet [fought and] with him fought many religious scholars. But they never lost assurance due to what afflicted them in the cause of Allah, nor did they weaken or submit. And Allah loves the steadfast." },
  { number: "3:147", arabic: "وَمَا كَانَ قَوْلَهُمْ إِلَّا أَن قَالُوا رَبَّnَا اغْfِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْmِ الْكَافِرِينَ", lao: "ແລະຄຳເວົ້າຂອງພວກເຂົາບໍ່ມີຫຍັງນອກຈາກ: 'ໂອ້ ພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຮົາ, ຂໍให้อภัยบาปของเราและการล่วงเกินของเรา, และເຮັດໃຫ້เท้าของพวกเรามั่นคง, ແລະຊ່ວຍให้พวกเราเอาชนะກຸ່ມผู้ปฏิเสธ.'", english: "And their words were not but that they said, 'Our Lord, forgive us our sins and the excess [committed] in our affairs and plant firmly our feet and give us victory over the disbelieving people.'" },
  { number: "3:148", arabic: "فَآتَاهُمُ اللَّهُ ثَوَابَ الدُّنْيَا وَحُsْنَ ثَوَابِ الْآخِرَةِ ۗ وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ", lao: "ດັ່ງນັ້ນອັລລໍຮ໌ໄດ້ให้รางวัลแก่พวกเขาในโลกนี้และรางวัลที่ดีในโลกหน้า. และอัลลอฮ์ทรงรักผู้ที่ทำความดี.", english: "So Allah gave them the reward of this world and the good reward of the Hereafter. And Allah loves the doers of good." },
  { number: "3:149", arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا إِن تُطِيعُوا الَّذِينَ كَفَرُوا يَرُdُّوكُمْ عَلَىٰ أَعْقَابِكُمْ فَتَنqَلِبُوا خَاسِرِينَ", lao: "ໂອ້ ຜູ້ທີ່ເຊື່ອ, ຫາກພວກเจ้าเชื่อฟังผู้ที่ปฏิเสธ, ພວກເຂົາจะทำให้พวกเจ้าหันหลังกลับ, ແລ້ວพวกเจ้าจะกลายเป็นผู้ที่ขาดทุน.", english: "O you who have believed, if you obey those who disbelieve, they will turn you back on your heels, and you will become losers." },
  { number: "3:150", arabic: "بَلِ اللَّهُ مَوْلَاكُمْ ۖ وَهُوَ خَيْرُ النَّاصِرِينَ", lao: "ບໍ່, ອັນລໍຄືผู้พิทักษ์ของพวกเจ้า, และพระองค์คือผู้ช่วยเหลือที่ดีที่สุด.", english: "But Allah is your protector, and He is the best of helpers." }
];

export default function SurahAalImranView({ goBack }: SurahAalImranViewProps) {
  const [searchQuery, setSearchQuery] = useState('');

  const filteredVerses = verses.filter(verse =>
    verse.number.includes(searchQuery) ||
    verse.lao.toLowerCase().includes(searchQuery.toLowerCase()) ||
    verse.english.toLowerCase().includes(searchQuery.toLowerCase()) ||
    verse.arabic.includes(searchQuery)
  );

  return (
    <div className="flex flex-col">
      <ViewHeader title="ສູຣໍ ອາລ ອິມຣອນ" onBack={goBack} />
      <div className="p-4 sticky top-0 bg-background z-10">
        <Input
          type="text"
          placeholder="ຄົ້ນຫາອາຍັດ..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full"
        />
      </div>
      <main className="p-4 pt-0">
        {filteredVerses.length > 0 ? (
          filteredVerses.map(v => <VerseCard key={v.number} {...v} />)
        ) : (
          <p className="text-center text-muted-foreground">ບໍ່ພົບອາຍັດທີ່ທ່ານຄົ້ນຫາ.</p>
        )}
        <SummaryCard title="ສະຫຼຸບ">
          ອາຍັດເຫຼົ່ານີ້ຢືນຢັນເຖິງຄວາມເປັນເອກະພາບຂອງອັນລໍ, ການປະທານຄຳພີຕ່າງໆ, ແລະ ໄດ້ກ່າວເຖິງການໂຕ້ຖຽງຂອງຜູ້ປະຕິເສດ. ມັນຍັງເລົ່າເລື່ອງການເກີດທີ່ມະຫັດສະຈັນຂອງນາງມາຣີຍຳ ແລະ ການເລີ່ມຕົ້ນພາລະກິດຂອງສາດສະດາອີຊາ.
        </SummaryCard>
      </main>
    </div>
  );
}
