'use client';
import ViewHeader from '@/components/shared/ViewHeader';
import VerseCard from '@/components/shared/VerseCard';
import SummaryCard from '@/components/shared/SummaryCard';

interface SurahAlBaqarahViewProps {
  goBack: () => void;
}

const verses = [
  { number: "2:1", arabic: "الم", lao: "ອາລີຟ, ລາມ, ມີມ.", english: "Alif, Lam, Meem." },
  { number: "2:2", arabic: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ هُدًى لِّلْمُتَّقِينَ", lao: "ຄໍາພີນີ້ (ກຸຣອານ), ບໍ່ມີຄວາມສົງໄສໃດໆໃນມັນ, ເປັນການຊີ້ແນະແກ່ບັນດາຜູ້ທີ່ມີຄວາມຍຳເກງ.", english: "This is the Book about which there is no doubt, a guidance for those conscious of Allah -" },
  { number: "2:3", arabic: "الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ", lao: "ບັນດາຜູ້ທີ່ເຊື່ອໃນສິ່ງທີ່ລັບເລິກ, ແລະດຳລົງການລະໝາດ, ແລະຈາກສິ່ງທີ່ເຮົາໄດ້ປະທານໃຫ້ພວກເຂົາ ພວກເຂົາກໍບໍລິຈາກ.", english: "Who believe in the unseen, establish prayer, and spend out of what We have provided for them," },
  { number: "2:4", arabic: "وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنزِلَ إِلَيْكَ وَمَا أُنزِلَ مِن قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوقِنُونَ", lao: "ແລະບັນດາຜູ້ທີ່ເຊື່ອໃນສິ່ງທີ່ຖືກເປີດເຜີຍລົງມາຫາເຈົ້າ, ແລະສິ່ງທີ່ຖືກເປີດເຜີຍລົງມາກ່ອນເຈົ້າ, ແລະພວກເຂົາກໍມີຄວາມເຊື່ອໝັ້ນຢ່າງເຕັມທີ່ໃນໂລກຫນ້າ.", english: "And who believe in what has been revealed to you, [O Muhammad], and what was revealed before you, and of the Hereafter they are certain [in faith]." },
  { number: "2:5", arabic: "أُولَٰئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ", lao: "ພວກເຂົານັ້ນຢູ່ເທິງເສັ້ນທາງທີ່ຖືກຕ້ອງຈາກພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຂົາ, ແລະພວກເຂົານັ້ນຄືບັນດາຜູ້ທີ່ໄດ້ຮັບຄວາມສຳເລັດ.", english: "Those are upon [right] guidance from their Lord, and it is those who are the successful." },
  { number: "2:6", arabic: "إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ", lao: "ແທ້ຈິງບັນດາຜູ້ທີ່ປະຕິເສດຄວາມເຊື່ອ, ບໍ່ວ່າເຈົ້າຈະຕັກເຕືອນພວກເຂົາຫຼືບໍ່ຕັກເຕືອນພວກເຂົາກໍຕາມ, ພວກເຂົາຈະບໍ່ເຊື່ອ.", english: "Indeed, those who disbelieve - it is all the same for them whether you warn them or do not warn them - they will not believe." },
  { number: "2:7", arabic: "خَتَمَ اللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ وَعَلَىٰ أَبْصَارِهِمْ غِشَاوَةٌ وَلَهُمْ عَذَابٌ عَظِيمٌ", lao: "ອັລລໍຮ໌ໄດ້ຊົງປະທັບຕາໄວ້ເທິງຫົວໃຈຂອງພວກເຂົາ ແລະເທິງການໄດ້ຍິນຂອງພວກເຂົາ, ແລະເທິງສາຍຕາຂອງພວກເຂົາມີຜ້າປິດໄວ້; ແລະສຳລັບພວກເຂົາຈະໄດ້ຮັບການທໍລະມານຢ່າງໃຫຍ່ຫຼວງ.", english: "Allah has set a seal upon their hearts and upon their hearing, and over their vision is a veil. And for them is a great punishment." },
  { number: "2:8", arabic: "وَمِنَ النَّاسِ مَن يَقُولُ آمَنَّا بِاللَّهِ وَبِالْيَوْمِ الْآخِرِ وَمَا هُم بِمُؤْمِنِينَ", lao: "ແລະໃນບັນດາມະນຸດ ມີຜູ້ທີ່ກ່າວວ່າ “ພວກເຮົາເຊື່ອໃນອັລລໍຮ໌ ແລະໃນວັນສຸດທ້າຍ” ແຕ່ພວກເຂົາບໍ່ແມ່ນຜູ້ທີ່ເຊື່ອ.", english: "And of the people are some who say, 'We believe in Allah and the Last Day,' but they are not believers." },
  { number: "2:9", arabic: "يُخَادِعُونَ اللَّهَ وَالَّذِينَ آمَنُوا وَمَا يَخْدَعُونَ إِلَّا أَنفُسَهُمْ وَمَا يَشْعُرُونَ", lao: "ພວກເຂົາຫຼອກລວງອັລລໍຮ໌ ແລະບັນດາຜູ້ທີ່ເຊື່ອ, ແຕ່ພວກເຂົາບໍ່ໄດ້ຫຼອກລວງໃຜນອກຈາກຕົວເອງເທົ່ານັ້ນ, ແລະພວກເຂົາກໍບໍ່ຮູ້ສຶກຕົວ.", english: "They [think to] deceive Allah and those who believe, but they deceive not except themselves and perceive [it] not." },
  { number: "2:10", arabic: "فِي قُلُوبِهِم مَّرَضٌ فَزَادَهُمُ اللَّهُ مَرَضًا وَلَهُمْ عَذَابٌ أَلِيمٌ بِمَا كَانُوا يَكْذِبُونَ", lao: "ໃນຫົວໃຈຂອງພວກເຂົາມີພະຍາດ, ແລ້ວອັລລໍຮ໌ກໍຊົງເພີ່ມພະຍາດໃຫ້ພວກເຂົາ, ແລະພວກເຂົາຈະໄດ້ຮັບການທໍລະມານຢ່າງເຈັບປວດເນື່ອງຈາກສິ່ງທີ່ພວກເຂົາເຄີຍຕົວະ.", english: "In their hearts is disease, so Allah has increased their disease; and for them is a painful punishment because they [habitually] used to lie." },
  { number: "2:11", arabic: "وَإِذَا قِيلَ لَهُمْ لَا تُفْسِدُوا فِي الْأَرْضِ قَالُوا إِنَّمَا نَحْنُ مُصْلِحُونَ", lao: "ແລະເມື່ອຖືກກ່າວແກ່ພວກເຂົາວ່າ: 'ຈົ່ງຢ່າສ້າງຄວາມເສຍຫາຍໃນແຜ່ນດິນ', ພວກເຂົາກ່າວວ່າ: 'ພວກເຮົາເປັນພຽງຜູ້ປັບປຸງແກ້ໄຂເທົ່ານັ້ນ'.", english: "And when it is said to them, 'Do not cause corruption on the earth,' they say, 'We are but reformers.'" },
  { number: "2:12", arabic: "أَلَا إِنَّهُمْ هُمُ الْمُفْسِدُونَ وَلَٰكِن لَّا يَشْعُرُونَ", lao: "ຈົ່ງຮູ້ໄວ້ວ່າ, ແທ້ຈິງແລ້ວ ພວກເຂົາຄືຜູ້ທີ່ສ້າງຄວາມເສຍຫາຍ, ແຕ່ພວກເຂົາບໍ່ຮູ້ສຶກຕົວ.", english: "Unquestionably, it is they who are the corrupters, but they perceive [it] not." },
  { number: "2:13", arabic: "وَإِذَا قِيلَ لَهُمْ آمِنُوا كَمَا آمَنَ النَّاسُ قَالُوا أَنُؤْمِنُ كَمَا آمَنَ السُّفَهَاءُ ۗ أَلَا إِنَّهُمْ هُمُ السُّفَهَاءُ وَلَٰكِن لَّا يَعْلَمُونَ", lao: "ແລະເມື່ອຖືກກ່າວແກ່ພວກເຂົາວ່າ: 'ຈົ່ງເຊື່ອເໝືອນດັ່ງທີ່ຄົນທັງຫຼາຍໄດ້ເຊື່ອ', ພວກເຂົາກ່າວວ່າ: 'ພວກເຮົາຈະເຊື່ອເໝືອນດັ່ງທີ່ຄົນໂງ່ໄດ້ເຊື່ອບໍ?' ຈົ່ງຮູ້ໄວ້ວ່າ, ແທ້ຈິງແລ້ວ ພວກເຂົາຄືຄົນໂງ່, ແຕ່ພວກເຂົາບໍ່ຮູ້.", english: "And when it is said to them, 'Believe as the people have believed,' they say, 'Should we believe as the foolish have believed?' Unquestionably, it is they who are the foolish, but they know it not." },
  { number: "2:14", arabic: "وَإِذَا لَقُوا الَّذِينَ آمَنُوا قَالُوا آمَنَّا وَإِذَا خَلَوْا إِلَىٰ شَيَاطِينِهِمْ قَالُوا إِنَّا مَعَكُمْ إِنَّمَا نَحْنُ مُسْتَهْزِئُونَ", lao: "ແລະເມື່ອພວກເຂົາພົບກັບບັນດາຜູ້ທີ່ເຊື່ອ, ພວກເຂົາກ່າວວ່າ: 'ພວກເຮົາເຊື່ອແລ້ວ'. ແຕ່ເມື່ອພວກເຂົາຢູ່ກັບພວກຜີມານຂອງພວກເຂົາ, ພວກເຂົາກ່າວວ່າ: 'ແທ້ຈິງ ພວກເຮົາຢູ່ກັບພວກເຈົ້າ, ພວກເຮົາເປັນພຽງຜູ້ທີ່ເຍາະເຍີ້ຍເທົ່ານັ້ນ'.", english: "And when they meet those who believe, they say, 'We believe'; but when they are alone with their evil ones, they say, 'Indeed, we are with you; we were only mockers.'" },
  { number: "2:15", arabic: "اللَّهُ يَسْتَهْزِئُ بِهِمْ وَيَمُدُّهُمْ فِي طُغْيَانِهِمْ يَعْمَهُونَ", lao: "ອັລລໍຮ໌ຈະຊົງເຍາະເຍີ້ຍພວກເຂົາ ແລະຈະຊົງປ່ອຍໃຫ້ພວກເຂົາຢູ່ໃນການລະເມີດຂອງພວກເຂົາຢ່າງບໍ່ມີຈຸດໝາຍ.", english: "Allah mocks them and prolongs them in their transgression [while] they wander blindly." },
  { number: "2:16", arabic: "أُولَٰئِكَ الَّذِينَ اشْتَرَوُا الضَّلَالَةَ بِالْهُدَىٰ فَمَا رَبِحَت تِّجَارَتُهُمْ وَمَا كَانُوا مُهْتَدِينَ", lao: "ພວກເຂົາຄືຜູ້ທີ່ໄດ້ຊື້ການຫຼົງທາງດ້ວຍການຊີ້ແນະ, ດັ່ງນັ້ນການຄ້າຂອງພວກເຂົາຈຶ່ງບໍ່ໄດ້ກຳໄລ ແລະ ພວກເຂົາບໍ່ໄດ້ເປັນຜູ້ທີ່ຖືກຊີ້ແນະ.", english: "Those are the ones who have purchased error [in exchange] for guidance, so their transaction has brought no profit, nor were they guided." },
  { number: "2:17", arabic: "مَثَلُهُمْ كَمَثَلِ الَّذِي اسْتَوْقَدَ نَارًا فَلَمَّا أَضَاءَتْ مَا حَوْلَهُ ذَهَبَ اللَّهُ بِنُورِهِمْ وَتَرَكَهُمْ فِي ظُلُمَاتٍ لَّا يُبْصِرُونَ", lao: "ຕົວຢ່າງຂອງພວກເຂົາຄືກັບຜູ້ທີ່ໄດ້ຈູດໄຟ, ເມື່ອໄຟໄດ້ສ່ອງແສງສິ່ງທີ່ຢູ່ອ້ອມຮອບລາວ, ອັລລໍຮ໌ກໍໄດ້ເອົາແສງສະຫວ່າງຂອງພວກເຂົາໄປ ແລະ ປ່ອຍພວກເຂົາໄວ້ໃນຄວາມມືດ, ພວກເຂົາບໍ່ສາມາດເຫັນໄດ້.", english: "Their example is that of one who kindled a fire, but when it illuminated what was around him, Allah took away their light and left them in darkness [so] they could not see." },
  { number: "2:18", arabic: "صُمٌّ بُكْمٌ عُمْيٌ فَهُمْ لَا يَرْجِعُونَ", lao: "ຫູໜວກ, ເປັນໃບ້, ຕາບອດ, ດັ່ງນັ້ນພວກເຂົາຈະບໍ່ກັບມາ.", english: "Deaf, dumb and blind - so they will not return [to the right path]." },
  { number: "2:19", arabic: "أَوْ كَصَيِّبٍ مِّنَ السَّمَاءِ فِيهِ ظُلُمَاتٌ وَرَعْدٌ وَبَرْقٌ يَجْعَلُونَ أَصَابِعَهُمْ فِي آذَانِهِم مِّنَ الصَّوَاعِقِ حَذَرَ الْمَوْتِ ۚ وَاللَّهُ مُحِيطٌ بِالْكَافِرِينَ", lao: "ຫຼືຄືກັບຝົນທີ່ຕົກລົງມາຈາກຟ້າ, ໃນນັ້ນມີຄວາມມືດ, ສຽງຟ້າຮ້ອງ, ແລະຟ້າແມບ. ພວກເຂົາເອົານິ້ວມືອັດຫູຂອງພວກເຂົາຈາກສຽງຟ້າຜ່າ ເພາະຢ້ານຄວາມຕາຍ. ແລະອັລລໍຮ໌ຊົງລ້ອມຜູ້ປະຕິເສດຄວາມເຊື່ອໄວ້.", english: "Or [it is] like a rainstorm from the sky within which is darkness, thunder and lightning. They put their fingers in their ears against the thunderclaps in dread of death. But Allah is encompassing of the disbelievers." },
  { number: "2:20", arabic: "يَكَادُ الْبَرْقُ يَخْطَفُ أَبْصَارَهُمْ ۖ كُلَّمَا أَضَاءَ لَهُم مَّشَوْا فِيهِ وَإِذَا أَظْلَمَ عَلَيْهِمْ قَامُوا ۚ وَلَوْ شَاءَ اللَّهُ لَذَهَبَ بِسَمْعِهِمْ وَأَبْصَارِهِمْ ۚ إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", lao: "ຟ້າແມບເກືອບຈະເອົາສາຍຕາຂອງພວກເຂົາໄປ. ທຸກຄັ້ງທີ່ມັນສ່ອງແສງໃຫ້ພວກເຂົາ, ພວກເຂົາກໍຍ່າງໄປໃນແສງນັ້ນ; ແລະເມື່ອມັນມືດລົງ, ພວກເຂົາກໍຢຸດ. ແລະຖ້າອັລລໍຮ໌ຊົງປະສົງ, ພຣະອົງຈະເອົາການໄດ້ຍິນແລະສາຍຕາຂອງພວກເຂົາໄປ. ແທ້ຈິງ, ອັລລໍຮ໌ຊົງມີອຳນາດເໜືອທຸກສິ່ງ.", english: "The lightning almost snatches away their sight. Every time it lights [the way] for them, they walk therein; but when darkness comes over them, they stand [still]. And if Allah had willed, He could have taken away their hearing and their sight. Indeed, Allah is over all things competent." },
  { number: "2:21", arabic: "يَا أَيُّهَا النَّاسُ اعْبُدُوا رَبَّكُمُ الَّذِي خَلَقَكُمْ وَالَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ", lao: "ໂອ້ ມະນຸດເອີຍ, ຈົ່ງນະມັດສະການພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຈົ້າ, ຜູ້ທີ່ໄດ້ສ້າງພວກເຈົ້າ ແລະຜູ້ທີ່ຢູ່ກ່ອນໜ້າພວກເຈົ້າ, ເພື່ອວ່າພວກເຈົ້າຈະໄດ້ມີຄວາມຢຳເກງ.", english: "O mankind, worship your Lord, who created you and those before you, that you may become righteous -" },
  { number: "2:22", arabic: "الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً وَأَنزَلَ مِنَ السَّمَاءِ مَاءً فَأَخْرَجَ بِهِ مِنَ الثَّمَرَاتِ رِزْقًا لَّكُمْ ۖ فَلَا تَجْعَلُوا لِلَّهِ أَندَادًا وَأَنتُمْ تَعْلَمُونَ", lao: "ຜູ້ທີ່ໄດ້ເຮັດໃຫ້ແຜ່ນດິນເປັນທີ່ນອນສຳລັບພວກເຈົ້າ, ແລະຟ້າເປັນຫຼັງຄາ, ແລະໄດ້ສົ່ງນ້ຳລົງມາຈາກຟ້າ, ແລ້ວໄດ້ເອົານ້ຳນັ້ນອອກມາເປັນໝາກໄມ້ເພື່ອເປັນອາຫານສຳລັບພວກເຈົ້າ. ດັ່ງນັ້ນ, ຢ່າຕັ້ງສິ່ງໃດເປັນຄູ່ແຂ່ງກັບອັລລໍຮ໌, ທັງທີ່ພວກເຈົ້າຮູ້.", english: "[He] who made for you the earth a bed [spread out] and the sky a ceiling and sent down from the sky, rain and brought forth thereby fruits as provision for you. So do not attribute to Allah equals while you know [that there is nothing similar to Him]." },
  { number: "2:23", arabic: "وَإِن كُنتُمْ فِي رَيْبٍ مِّمَّا نَزَّلْنَا عَلَىٰ عَبْدِنَا فَأْتُوا بِسُورَةٍ مِّن مِّثْلِهِ وَادْعُوا شُهَدَاءَكُم مِّن دُونِ اللَّهِ إِن كُنتُمْ صَادِقِينَ", lao: "ແລະຖ້າພວກເຈົ້າສົງໄສໃນສິ່ງທີ່ເຮົາໄດ້ເປີດເຜີຍລົງມາໃຫ້ແກ່ຂ້າທາດຂອງເຮົາ, ກໍຈົ່ງນຳມາຊັກບົດໜຶ່ງທີ່ເໝືອນກັບມັນ, ແລະຈົ່ງເອີ້ນພະຍານຂອງພວກເຈົ້ານອກຈາກອັລລໍຮ໌, ຖ້າພວກເຈົ້າເປັນຜູ້ທີ່ສັດຈິງ.", english: "And if you are in doubt about what We have sent down upon Our Servant [Muhammad], then produce a surah the like thereof and call upon your witnesses other than Allah, if you should be truthful." },
  { number: "2:24", arabic: "فَإِن لَّمْ تَفْعَلُوا وَلَن تَفْعَلُوا فَاتَّقُوا النَّارَ الَّتِي وَقُودُهَا النَّاسُ وَالْحِجَارَةُ ۖ أُعِدَّتْ لِلْكَافِرِينَ", lao: "ແຕ່ຖ້າພວກເຈົ້າບໍ່ສາມາດເຮັດໄດ້, ແລະພວກເຈົ້າຈະບໍ່ສາມາດເຮັດໄດ້ຢ່າງແນ່ນອນ, ກໍຈົ່ງຢ້ານກົວໄຟນະລົກ, ຊຶ່ງເຊື້ອໄຟຂອງມັນຄືມະນຸດແລະຫີນ, ທີ່ຖືກກະກຽມໄວ້ສຳລັບຜູ້ປະຕິເສດຄວາມເຊື່ອ.", english: "But if you do not - and you will never be able to - then fear the Fire, whose fuel is men and stones, prepared for the disbelievers." },
  { number: "2:25", arabic: "وَبَشِّرِ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أَنَّ لَهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ ۖ كُلَّمَا رُزِقُوا مِنْهَا مِن ثَمَرَةٍ رِّزْقًا ۙ قَالُوا هَٰذَا الَّذِي رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا بِهِ مُتَشَابِهًا ۖ وَلَهُمْ فِيهَا أَزْوَاجٌ مُّطَهَّرَةٌ ۖ وَهُمْ فِيهَا خَالِدُونَ", lao: "ແລະຈົ່ງແຈ້ງຂ່າວດີແກ່ບັນດາຜູ້ທີ່ເຊື່ອແລະເຮັດຄວາມດີວ່າ ສຳລັບພວກເຂົາຈະມີສວນສະຫວັນ, ຊຶ່ງມີແມ່ນ້ຳໄຫຼຜ່ານຢູ່ເບື້ອງລຸ່ມ. ທຸກຄັ້ງທີ່ພວກເຂົາໄດ້ຮັບໝາກໄມ້ຈາກສວນສະຫວັນເປັນອາຫານ, ພວກເຂົາຈະກ່າວວ່າ: 'ນີ້ຄືສິ່ງທີ່ພວກເຮົາເຄີຍໄດ້ຮັບມາກ່ອນ'. ແລະພວກເຂົາຈະໄດ້ຮັບມັນໃນລັກສະນະທີ່ຄ້າຍຄືກັນ. ແລະໃນນັ້ນພວກເຂົາຈະມີຄູ່ຄອງທີ່ບໍລິສຸດ, ແລະພວກເຂົາຈະຢູ່ໃນນັ້ນຕະຫຼອດໄປ.", english: "And give good tidings to those who believe and do righteous deeds that they will have gardens [in Paradise] beneath which rivers flow. Whenever they are provided with a provision of fruit therefrom, they will say, 'This is what we were provided with before.' And it will be given to them in likeness. And they will have therein purified spouses, and they will abide therein eternally." },
  { number: "2:26", arabic: "۞ إِنَّ اللَّهَ لَا يَسْتَحْيِي أَن يَضْرِبَ مَثَلًا مَّا بَعُوضَةً فَمَا فَوْقَهَا ۚ فَأَمَّا الَّذِينَ آمَنُوا فَيَعْلَمُونَ أَنَّهُ الْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا الَّذِينَ كَفَرُوا فَيَقُولُونَ مَاذَا أَرَادَ اللَّهُ بِهَٰذَا مَثَلًا ۘ يُضِلُّ بِهِ كَثِيرًا وَيَهْدِي بِهِ كَثِيرًا ۚ وَمَا يُضِلُّ بِهِ إِلَّا الْفَاسِقِينَ", lao: "ແທ້ຈິງ, ອັລລໍຮ໌ບໍ່ຊົງລະອາຍທີ່ຈະຍົກຕົວຢ່າງໃດໆ, ແມ້ຈະເປັນຍຸງ ຫຼືສິ່ງທີ່ເໜືອມັນ. ສ່ວນຜູ້ທີ່ເຊື່ອ, ພວກເຂົາຮູ້ວ່າມັນເປັນຄວາມຈິງຈາກພຣະຜູ້ເປັນເຈົ້າຂອງພວກເຂົາ. ແຕ່ສ່ວນຜູ້ທີ່ປະຕິເສດ, ພວກເຂົາກ່າວວ່າ: 'ອັລລໍຮ໌ປະສົງສິ່ງໃດດ້ວຍຕົວຢ່າງນີ້?' ພຣະອົງຊົງເຮັດໃຫ້ຫຼາຍຄົນຫຼົງທາງດ້ວຍມັນ ແລະຊົງຊີ້ແນະຫຼາຍຄົນດ້ວຍມັນ. ແລະພຣະອົງບໍ່ໄດ້ເຮັດໃຫ້ຜູ້ໃດຫຼົງທາງດ້ວຍມັນນອກຈາກຜູ້ທີ່ລະເມີດ.", english: "Indeed, Allah is not timid to present an example - that of a mosquito or what is smaller than it. And those who believe know that it is the truth from their Lord. But as for those who disbelieve, they say, 'What did Allah intend by this as an example?' He misleads many thereby and guides many thereby. And He misleads not thereby except the defiantly disobedient," },
  { number: "2:27", arabic: "الَّذِينَ يَنقُضُونَ عَهْدَ اللَّهِ مِن بَعْدِ مِيثَاقِهِ وَيَقْطَعُونَ مَا أَمَرَ اللَّهُ بِهِ أَن يُوصَلَ وَيُفْسِدُونَ فِي الْأَرْضِ ۚ أُولَٰئِكَ هُمُ الْخَاسِرُونَ", lao: "ຜູ້ທີ່ລະເມີດສັນຍາຂອງອັລລໍຮ໌ຫຼັງຈາກທີ່ໄດ້ຢືນຢັນມັນ, ແລະຕັດສິ່ງທີ່ອັລລໍຮ໌ໄດ້ສັ່ງໃຫ້ເຊື່ອມຕໍ່, ແລະສ້າງຄວາມເສຍຫາຍໃນແຜ່ນດິນ. ພວກເຂົາຄືຜູ້ທີ່ຂາດທຶນ.", english: "Who break the covenant of Allah after contracting it and sever that which Allah has ordered to be joined and cause corruption on earth. It is those who are the losers." },
  { number: "2:28", arabic: "كَيْفَ تَكْفُرُونَ بِاللَّهِ وَكُنتُمْ أَمْوَاتًا فَأَحْيَاكُمْ ۖ ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَ", lao: "ພວກເຈົ້າຈະປະຕິເສດອັລລໍຮ໌ໄດ້ແນວໃດ, ທັງທີ່ພວກເຈົ້າເຄີຍຕາຍ ແລ້ວພຣະອົງໄດ້ໃຫ້ພວກເຈົ້າມີຊີວິດ? ຫຼັງຈາກນັ້ນ, ພຣະອົງຈະໃຫ້ພວກເຈົ້າຕາຍ, ແລ້ວຈະໃຫ້ພວກເຈົ້າມີຊີວິດອີກ, ແລ້ວພວກເຈົ້າຈະຖືກນຳກັບໄປຫາພຣະອົງ.", english: "How can you disbelieve in Allah when you were lifeless and He brought you to life; then He will cause you to die, then He will bring you [back] to life, and then to Him you will be returned." },
  { number: "2:29", arabic: "هُوَ الَّذِي خَلَقَ لَكُم مَّا فِي الْأَرْضِ جَمِيعًا ثُمَّ اسْتَوَىٰ إِلَى السَّمَاءِ فَسَوَّاهُنَّ سَبْعَ سَمَاوَاتٍ ۚ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ", lao: "ພຣະອົງຄືຜູ້ທີ່ໄດ້ສ້າງທຸກສິ່ງໃນແຜ່ນດິນໄວ້ສຳລັບພວກເຈົ້າ, ຫຼັງຈາກນັ້ນພຣະອົງໄດ້ຫັນໄປຫາທ້ອງຟ້າ ແລະໄດ້ເຮັດໃຫ້ມັນສົມບູນເປັນເຈັດຊັ້ນຟ້າ. ແລະພຣະອົງຊົງຮູ້ທຸກສິ່ງ.", english: "It is He who created for you all of that which is on the earth. Then He directed Himself to the heaven, [His being above all creation], and made them seven heavens, and He is Knowing of all things." },
  { number: "2:30", arabic: "وَإِذْ قَالَ رَبُّكَ لِلْمَلَائِكَةِ إِنِّي جَاعِلٌ فِي الْأَرْضِ خَلِيفَةً ۖ قَالُوا أَتَجْعَلُ فِيهَا مَن يُفْسِدُ فِيهَا وَيَسْفِكُ الدِّمَاءَ وَنَحْنُ نُسَبِّحُ بِحَمْدِكَ وَنُقَدِّسُ لَكَ ۖ قَالَ إِنِّي أَعْلَمُ مَا لَا تَعْلَمُونَ", lao: "ແລະຈົ່ງລະນຶກເຖິງເວລາທີ່ພຣະຜູ້ເປັນເຈົ້າຂອງເຈົ້າໄດ້ກ່າວແກ່ທູດສະຫວັນວ່າ: 'ແທ້ຈິງ, ຂ້ອຍຈະຕັ້ງຜູ້ຕາງໜ້າໄວ້ໃນແຜ່ນດິນ.' ພວກເຂົາກ່າວວ່າ: 'ພຣະອົງຈະຕັ້ງຜູ້ທີ່ຈະສ້າງຄວາມເສຍຫາຍແລະເຮັດໃຫ້ເລືອດໄຫຼໃນນັ້ນບໍ, ທັງທີ່ພວກເຮົາສັນລະເສີນພຣະອົງແລະຍ້ອງຍໍຄວາມບໍລິສຸດຂອງພຣະອົງ?' ພຣະອົງກ່າວວ່າ: 'ແທ້ຈິງ, ຂ້ອຍຮູ້ໃນສິ່ງທີ່ພວກເຈົ້າບໍ່ຮູ້.'", english: "And [mention, O Muhammad], when your Lord said to the angels, 'Indeed, I will make upon the earth a successive authority.' They said, 'Will You place upon it one who causes corruption therein and sheds blood, while we declare Your praise and sanctify You?' Allah said, 'Indeed, I know that which you do not know.'" },
];

export default function SurahAlBaqarahView({ goBack }: SurahAlBaqarahViewProps) {
  return (
    <div className="flex flex-col">
      <ViewHeader title="ສູຣໍ ອັລບາກໍຣໍ" onBack={goBack} />
      <main className="p-4">
        {verses.map(v => <VerseCard key={v.number} {...v} />)}
        <SummaryCard title="ສະຫຼຸບ">
          ອາຍັດເຫຼົ່ານີ້ອະທິບາຍເຖິງກຸ່ມຄົນຕ່າງໆ: ຜູ້ສັດທາ, ຜູ້ປະຕິເສດ, ແລະ ຜູ້ໜ້າຊື່ໃຈຄົດ. ມັນໄດ້ທ້າທາຍຜູ້ທີ່ສົງໄສໃນຄຳພີກຸຣອານ, ໄດ້ສັນຍາລາງວັນແກ່ผู้ທີ່ເຊື່ອ, ແລະໄດ້ຢືນຢັນເຖິງອຳນາດຂອງອັນລໍຫ໌ໃນການສ້າງຈັກກະວານ ແລະ ມະນຸດ.
        </SummaryCard>
      </main>
    </div>
  );
}
