'use client';
import React, { useState } from 'react';
import ViewHeader from '@/components/shared/ViewHeader';
import VerseCard from '@/components/shared/VerseCard';
import SummaryCard from '@/components/shared/SummaryCard';
import { Input } from '@/components/ui/input';

interface SurahAnNisaViewProps {
  goBack: () => void;
}

const verses = [
    { number: "4:1", arabic: "يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ الَّذِي خَلَقَكُم مِّن نَّفْسٍ وَاحِدَةٍ وَخَلَقَ مِنْهَا زَوْجَهَا وَبَثَّ مِنْهُمَا رِجَالًا كَثِيرًا وَنِسَاءً ۚ وَاتَّقُوا اللَّهَ الَّذِي تَسَاءَلُونَ بِهِ وَالْأَرْحَامَ ۚ إِنَّ اللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا", lao: "Placeholder", english: "O mankind, fear your Lord, who created you from one soul and created from it its mate and dispersed from both of them many men and women. And fear Allah, through whom you ask one another, and the wombs. Indeed Allah is ever, over you, an Observer." },
    { number: "4:2", arabic: "وَآتُوا الْيَتَامَىٰ أَمْوَالَهُمْ ۖ وَلَا تَتَبَدَّلُوا الْخَبِيثَ بِالطَّيِّبِ ۖ وَلَا تَأْكُلُوا أَمْوَالَهُمْ إِلَىٰ أَمْوَالِكُمْ ۚ إِنَّهُ كَانَ حُوبًا كَبِيرًا", lao: "Placeholder", english: "And give to the orphans their properties and do not substitute the defective [of your own] for the good [of theirs]. And do not consume their properties into your own. Indeed, that is ever a great sin." },
    { number: "4:3", arabic: "وَإِنْ خِفْتُمْ أَلَّا تُقْسِطُوا فِي الْيَتَامَىٰ فَانكِحُوا مَا طَابَ لَكُم مِّنَ النِّسَاءِ مَثْنَىٰ وَثُلَاثَ وَرُبَاعَ ۖ فَإِنْ خِفْتُمْ أَلَّا تَعْدِلُوا فَوَاحِدَةً أَوْ مَا مَلَكَتْ أَيْمَانُكُمْ ۚ ذَٰلِكَ أَدْنَىٰ أَلَّا تَعُولُوا", lao: "Placeholder", english: "And if you fear that you will not deal justly with the orphan girls, then marry those that please you of [other] women, two or three or four. But if you fear that you will not be just, then [marry only] one or those your right hand possesses. That is more suitable that you may not incline [to injustice]." },
    { number: "4:4", arabic: "وَآتُوا النِّسَاءَ صَدُقَاتِهِنَّ نِحْلَةً ۚ فَإِن طِبْنَ لَكُمْ عَن شَيْءٍ مِّنْهُ نَفْسًا فَكُلُوهُ هَنِيئًا مَّرِيئًا", lao: "Placeholder", english: "And give the women [upon marriage] their [bridal] gift graciously. But if they give up willingly to you anything of it, then take it in satisfaction and ease." },
    { number: "4:5", arabic: "وَلَا تُؤْتُوا السُّفَهَاءَ أَمْوَالَكُمُ الَّتِي جَعَلَ اللَّهُ لَكُمْ قِيَامًا وَارْزُقُوهُمْ فِيهَا وَاكْسُوهُمْ وَقُولُوا لَهُمْ قَوْلًا مَّعْرُوفًا", lao: "Placeholder", english: "And do not give the foolish [i.e., those who are irresponsible] your wealth, which Allah has made a means of maintenance for you, but provide for them with it and clothe them and speak to them words of appropriate kindness." },
    { number: "4:6", arabic: "وَابْتَلُوا الْيَتَامَىٰ حَتَّىٰ إِذَا بَلَغُوا النِّكَاحَ فَإِنْ آنَسْتُم مِّنْهُمْ رُشْدًا فَادْفَعُوا إِلَيْهِمْ أَمْوَالَهُمْ ۖ وَلَا تَأْكُلُوهَا إِسْرَافًا وَبِدَارًا أَن يَكْبَرُوا ۚ وَمَن كَانَ غَنِيًّا فَلْيَسْتَعْفِفْ ۖ وَمَن كَانَ فَقِيرًا فَلْيَأْكُلْ بِالْمَعْرُوفِ ۚ فَإِذَا دَفَعْتُمْ إِلَيْهِمْ أَمْوَالَهُمْ فَأَشْهِدُوا عَلَيْهِمْ ۚ وَكَفَىٰ بِاللَّهِ حَسِيبًا", lao: "Placeholder", english: "And test the orphans [in their abilities] until they reach marriageable age. Then if you perceive in them sound judgment, release their property to them. And do not consume it excessively and quickly, [anticipating] that they will grow up. And whoever, [when acting as guardian], is self-sufficient should refrain [from taking a fee]; and whoever is poor - let him take according to what is acceptable. Then when you release their property to them, bring witnesses upon them. And sufficient is Allah as Accountant." },
    { number: "4:7", arabic: "لِّلرِّجَالِ نَصِيبٌ مِّمَّا تَرَكَ الْوَالِدَانِ وَالْأَقْرَبُونَ وَلِلنِّسَاءِ نَصِيبٌ مِّمَّا تَرَكَ الْوَالِدَانِ وَالْأَقْرَبُونَ مِمَّا قَلَّ مِنْهُ أَوْ كَثُرَ ۚ نَصِيبًا مَّفْرُوضًا", lao: "Placeholder", english: "For men is a share of what the parents and close relatives leave, and for women is a share of what the parents and close relatives leave, be it little or much - an obligatory share." },
    { number: "4:8", arabic: "وَإِذَا حَضَرَ الْقِسْمَةَ أُولُو الْقُرْبَىٰ وَالْيَتَamَىٰ وَالْمَسَاكِينُ فَarْزُقُوهُم مِّنْهُ وَقُولُوا لَهُمْ قَوْلًا مَّعْرُوفًا", lao: "Placeholder", english: "And when [other] relatives and orphans and the needy are present at the [time of] division, then provide for them [something] out of the estate and speak to them words of appropriate kindness." },
    { number: "4:9", arabic: "وَلْيَخْشَ الَّذِينَ لَوْ تَرَكُوا مِنْ خَلْfِهِمْ ذُرِّيَّةً ضِعَافًا خَافُوا عَلَيْهِمْ فَلْيَتَّقُوا اللَّهَ وَلْيَقُولُوا قَوْلًا سَدِيدًا", lao: "Placeholder", english: "And let those [executors and guardians] fear [injustice] as if they [themselves] had left weak offspring behind and feared for them. So let them fear Allah and speak words of appropriate justice." },
    { number: "4:10", arabic: "إِنَّ الَّذِينَ يَأْكُلُونَ أَمْوَالَ الْيَتَamَىٰ ظُلْمًا إِنَّمَا يَأْكُلُونَ فِي بُطُونِهِمْ نَarًا ۖ وَسَيَصْلَوْنَ سَعِيرًا", lao: "Placeholder", english: "Indeed, those who devour the property of orphans unjustly are only consuming into their bellies fire. And they will be burned in a Blaze." },
    { number: "4:11", arabic: "يُوصِيكُمُ اللَّهُ فِي أَوْلَادِكُمْ ۖ لِلذَّكَرِ مِثْلُ حَظِّ الْأُنثَيَيْنِ ۚ فَإِن كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ ۖ وَإِن كَانَتْ وَاحِدَةً فَلَهَا النِّصْfُ ۚ وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِّنْهُمَا السُّdُسُ مِمَّا تَرَكَ إِن كَانَ لَهُ وَلَدٌ ۚ فَإِن لَّمْ يَكُن لَّهُ وَلَدٌ وَوَرِثَهُ أَبَوَاهُ فَلِأُمِّهِ الثُّلُثُ ۚ فَإِن كَانَ لَهُ إِخْوَةٌ فَلِأُمِّهِ السُّdُسُ ۚ مِن بَعْدِ وَصِيَّةٍ يُوصِي بِهَا أَوْ دَيْنٍ ۗ آبَاؤُكُمْ وَأَبْنَاؤُكُمْ لَا تَدْرُونَ أَيُّهُمْ أَقْرَبُ لَكُمْ نَفْعًا ۚ فَرِيضَةً مِّنَ اللَّهِ ۗ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا", lao: "Placeholder", english: "Allah instructs you concerning your children: for the male, what is equal to the share of two females. But if there are [only] daughters, two or more, for them is two-thirds of what he left. And if there is only one, for her is half. And for one's parents, to each one of them is a sixth of what he left if he has a child. But if he has no child and his parents inherit from him, then for his mother is one-third. And if he has brothers [or sisters], for his mother is a sixth, after any bequest he [may have] made or debt. Your parents or your children - you know not which of them are nearest to you in benefit. [These shares are] an obligation [imposed] by Allah. Indeed, Allah is ever Knowing and Wise." },
    { number: "4:12", arabic: "وَلَكُمْ نِصْfُ مَا تَرَكَ أَزْوَajُكُمْ إِن لَّمْ يَكُن لَّهُنَّ وَلَدٌ ۚ فَإِن كَانَ لَهُنَّ وَلَدٌ فَلَكُمُ الرُّbُعُ مِمَّا تَرَكْنَ ۚ مِن بَعْدِ وَصِيَّةٍ يُوصِينَ بِهَا أَوْ دَيْنٍ ۚ وَلَهُنَّ الرُّbُعُ مِمَّا تَرَكْتُمْ إِن لَّمْ يَكُن لَّكُمْ وَلَدٌ ۚ فَإِن كَانَ لَكُمْ وَلَدٌ فَلَهُنَّ الثُّمُنُ مِمَّا تَرَكْتُم ۚ مِّن بَعْدِ وَصِيَّةٍ تُوصُونَ بِهَا أَوْ دَيْنٍ ۗ وَإِن كَانَ رَjُلٌ يُورَثُ كَلَالَةً أَوِ امْرَأَةٌ وَلَهُ أَخٌ أَوْ أُخْتٌ فَلِكُلِّ وَاحِدٍ مِّنْهُمَا السُّdُسُ ۚ فَإِن كَانُوا أَكْثَرَ مِن ذَٰلِكَ فَهُمْ شُرَكَاءُ فِي الثُّلُثِ ۚ مِن بَعْدِ وَصِيَّةٍ يُوصَىٰ بِهَا أَوْ دَيْنٍ غَيْرَ مُضَarٍّ ۚ وَصِيَّةً مِّنَ اللَّهِ ۗ وَاللَّهُ عَلِيمٌ حَلِيمٌ", lao: "Placeholder", english: "And for you is half of what your wives leave if they have no child. But if they have a child, for you is one-fourth of what they leave, after any bequest they [may have] made or debt. And for the wives is one-fourth if you leave no child. But if you leave a child, for them is an eighth of what you leave, after any bequest you [may have] made or debt. And if a man or woman leaves neither ascendants nor descendants but has a brother or a sister, then for each one of them is a sixth. But if they are more than two, they share a third, after any bequest which was made or debt, as long as there is no detriment [caused]. [This is] an ordinance from Allah, and Allah is Knowing and Forbearing." },
    { number: "4:13", arabic: "تِلْكَ حُdُودُ اللَّهِ ۚ وَمَن يُطِعِ اللَّهَ وَرَسُولَهُ يُdْخِلْهُ jَنَّاتٍ تَjْرِي مِن تَحْتِهَا الْأَنْهَarُ خَالِدِينَ فِيهَا ۚ وَذَٰلِكَ الْfَوْزُ الْعَظِيمُ", lao: "Placeholder", english: "These are the limits [set by] Allah, and whoever obeys Allah and His Messenger will be admitted by Him to gardens [in Paradise] under which rivers flow, abiding eternally therein; and that is the great attainment." },
    { number: "4:14", arabic: "وَمَن يَعْصِ اللَّهَ وَرَسُولَهُ وَيَتَعَدَّ حُdُودَهُ يُdْخِلْهُ نَarًا خَالِدًا فِيهَا وَلَهُ عَذَابٌ mُّهِينٌ", lao: "Placeholder", english: "And whoever disobeys Allah and His Messenger and transgresses His limits - He will put him into the Fire to abide eternally therein, and he will have a humiliating punishment." },
    { number: "4:15", arabic: "وَاللَّاتِي يَأْتِينَ الْfَاحِشَةَ مِن nِّsَائِكُمْ فَاسْتَشْهِdُوا عَلَيْهِنَّ أَرْbَعَةً mِّنكُمْ ۖ فَإِن شَهِdُوا فَأَمْسِكُوهُنَّ فِي الْbُيُوتِ حَتَّىٰ يَتَوَfَّاهُنَّ الْمَوْتُ أَوْ يَjْعَلَ اللَّهُ لَهُنَّ سَبِilًا", lao: "Placeholder", english: "Those who commit unlawful sexual intercourse of your women - bring against them four [witnesses] from among you. And if they testify, confine the guilty women to houses until death takes them or Allah ordains for them [another] way." },
    { number: "4:16", arabic: "وَاللَّذَانِ يَأْتِيَانِهَا مِنكُمْ فَآذُوهُمَا ۖ فَإِن تَابَا وَأَصْلَحَا فَأَعْرِضُوا عَنْهُمَا ۗ إِنَّ اللَّهَ كَانَ تَوَّابًا rَّحِيمًا", lao: "Placeholder", english: "And the two who commit it among you, dishonor them both. But if they repent and correct themselves, leave them alone. Indeed, Allah is ever Accepting of repentance and Merciful." },
    { number: "4:17", arabic: "إِنَّمَا التَّوْbَةُ عَلَى اللَّهِ لِلَّذِينَ يَعْمَلُونَ السُّوءَ بِjَهَالَةٍ ثُمَّ يَتُوبُونَ مِن قَرِيبٍ فَأُولَٰئِكَ يَتُوبُ اللَّهُ عَلَيْهِمْ ۗ وَكَانَ اللَّهُ عَلِيمًا حَكِيمًا", lao: "Placeholder", english: "The repentance accepted by Allah is only for those who do wrong in ignorance [or carelessness] and then repent soon after. It is those to whom Allah will turn in forgiveness, and Allah is ever Knowing and Wise." },
    { number: "4:18", arabic: "وَلَيْsَتِ التَّوْbَةُ لِلَّذِينَ يَعْمَلُونَ السَّيِّئَاتِ حَتَّىٰ إِذَا حَضَرَ أَحَدَهُمُ الْمَوْتُ قَالَ إِنِّي تُbْتُ الْآنَ وَلَا الَّذِينَ يَمُوتُونَ وَهُمْ كُfَّarٌ ۚ أُولَٰئِكَ أَعْتَدْنَا لَهُمْ عَذَابًا أَلِيمًا", lao: "Placeholder", english: "But repentance is not [accepted] of those who [continue to] do evil deeds up until, when death comes to one of them, he says, 'Indeed, I have repented now,' or of those who die while they are disbelievers. For them We have prepared a painful punishment." },
    { number: "4:19", arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا يَحِلُّ لَكُمْ أَن تَرِثُوا النِّsَاءَ كَرْهًا ۖ وَلَا تَعْضُلُوهُنَّ لِتَذْهَبُوا بِbَعْضِ مَا آتَيْتُمُوهُنَّ إِلَّا أَن يَأْتِينَ بِfَاحِشَةٍ mُّbَيِّنَةٍ ۚ وَعَاشِرُوهُنَّ بِالْمَعْرُوفِ ۚ فَإِن كَرِهْتُمُوهُنَّ فَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَيَjْعَلَ اللَّهُ فِيهِ خَيْرًا كَثِيرًا", lao: "Placeholder", english: "O you who have believed, it is not lawful for you to inherit women by compulsion. And do not make difficulties for them in order to take [back] part of what you gave them unless they commit a clear immorality. And live with them in kindness. For if you dislike them - perhaps you dislike a thing and Allah makes therein much good." },
    { number: "4:20", arabic: "وَإِنْ أَرَدتُّمُ اسْتِبْدَالَ زَوْjٍ mَّكَانَ زَوْjٍ وَآتَيْتُمْ إِحْدَاهُنَّ قِنطَarًا فَلَا تَأْخُذُوا مِنْهُ شَيْئًا ۚ أَتَأْخُذُونَهُ بُهْتَانًا وَإِثْمًا mُّbِينًا", lao: "Placeholder", english: "But if you want to replace one wife with another and you have given one of them a great amount [in gifts], do not take [back] from it anything. Would you take it in injustice and manifest sin?" },
    { number: "4:21", arabic: "وَكَيْfَ تَأْخُذُونَهُ وَقَدْ أَfْضَىٰ بَعْضُكُمْ إِلَىٰ بَعْضٍ وَأَخَذْنَ مِنكُم mِّيثَاقًا غَلِيظًا", lao: "Placeholder", english: "And how could you take it while you have gone in unto each other and they have taken from you a solemn covenant?" },
    { number: "4:22", arabic: "وَلَا تَنكِحُوا مَا نَكَحَ آبَاؤُكُم mِّنَ النِّsَاءِ إِلَّا مَا قَدْ سَلَفَ ۚ إِنَّهُ كَانَ فَاحِشَةً وَمَقْتًا وَsَاءَ سَبِilًا", lao: "Placeholder", english: "And do not marry those [women] whom your fathers married, except what has already occurred. Indeed, it was an immorality and hateful [to Allah] and was evil as a way." },
    { number: "4:23", arabic: "حُرِّمَتْ عَلَيْكُمْ أُمَّهَاتُكُمْ وَbَنَاتُكُمْ وَأَخَوَاتُكُمْ وَعَمَّاتُكُمْ وَخَالَاتُكُمْ وَbَنَاتُ الْأَخِ وَbَنَاتُ الْأُخْتِ وَأُمَّهَاتُكُمُ اللَّاتِي أَرْضَعْنَكُمْ وَأَخَوَاتُكُم mِّنَ الرَّضَاعَةِ وَأُمَّهَاتُ نِسَائِكُمْ وَرَبَائِبُكُمُ اللَّاتِي فِي حُjُورِكُم mِّن nِّsَائِكُمُ اللَّاتِي دَخَلْتُم بِهِنَّ فَإِن لَّمْ تَكُونُوا دَخَلْتُم بِهِنَّ فَلَا jُنَاحَ عَلَيْكُمْ وَحَلَائِلُ أَبْنَائِكُمُ الَّذِينَ مِنْ أَصْلَابِكُمْ وَأَن تَjْمَعُوا بَيْنَ الْأُخْتَيْنِ إِلَّا مَا قَدْ sَلَفَ ۗ إِنَّ اللَّهَ كَانَ غَفُورًا rَّحِيمًا", lao: "Placeholder", english: "Prohibited to you [for marriage] are your mothers, your daughters, your sisters, your father's sisters, your mother's sisters, your brother's daughters, your sister's daughters, your [milk] mothers who nursed you, your sisters through nursing, your wives' mothers, and your step-daughters under your guardianship [born] of your wives unto whom you have gone in. But if you have not gone in unto them, there is no sin upon you. And [also prohibited are] the wives of your sons who are from your [own] loins, and that you take in marriage two sisters simultaneously, except for what has already occurred. Indeed, Allah is ever Forgiving and Merciful." },
    { number: "4:24", arabic: "وَالْمُحْصَنَاتُ مِنَ النِّsَاءِ إِلَّا مَا مَلَكَتْ أَيْمَانُكُمْ ۖ كِتَابَ اللَّهِ عَلَيْكُمْ ۚ وَأُحِلَّ لَكُم mَّا وَرَاءَ ذَٰلِكُمْ أَن تَبْتَغُوا بِأَمْوَالِكُم mُّحْصِنِينَ غَيْرَ مُsَافِحِينَ ۚ فَمَا اسْتَمْتَعْتُم بِهِ مِنْهُنَّ فَآتُوهُنَّ أُjُورَهُنَّ فَرِيضَةً ۚ وَلَا jُنَاحَ عَلَيْكُمْ فِيمَا تَرَاضَيْتُم بِهِ مِن بَعْدِ الْfَرِيضَةِ ۚ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا", lao: "Placeholder", english: "And [also prohibited to you are all] married women except those your right hands possess. [This is] the decree of Allah upon you. And lawful to you are [all others] beyond these, [provided] that you seek them [in marriage] with [gifts from] your property, desiring chastity, not unlawful sexual intercourse. So for whatever you enjoy of them, give them their due compensation as an obligation. And there is no blame upon you for what you mutually agree to beyond the obligation. Indeed, Allah is ever Knowing and Wise." },
    { number: "4:25", arabic: "وَمَن لَّمْ يَsْتَطِعْ مِنكُمْ طَوْلًا أَن يَنكِحَ الْمُحْصَنَاتِ الْمُؤْمِنَاتِ فَمِن mَّا مَلَكَتْ أَيْمَانُكُم mِّن فَتَيَاتِكُمُ الْمُؤْمِنَاتِ ۚ وَاللَّهُ أَعْلَمُ بِإِيمَانِكُم ۚ بَعْضُكُم mِّن بَعْضٍ ۚ فَانكِحُوهُنَّ بِإِذْنِ أَهْلِهِنَّ وَآتُوهُنَّ أُjُورَهُنَّ بِالْمَعْرُوفِ مُحْصَنَاتٍ غَيْرَ مُsَافِحَاتٍ وَلَا مُتَّخِذَاتِ أَخْدَانٍ ۚ فَإِذَا أُحْصِنَّ فَإِنْ أَتَيْنَ بِfَاحِشَةٍ فَعَلَيْهِنَّ نِصْfُ مَا عَلَى الْمُحْصَنَاتِ مِنَ الْعَذَابِ ۚ ذَٰلِكَ لِمَنْ خَشِيَ الْعَنَتَ مِنكُمْ ۚ وَأَن تَصْبِرُوا خَيْرٌ لَّكُمْ ۗ وَاللَّهُ غَفُورٌ rَّحِيمٌ", lao: "Placeholder", english: "And whoever among you cannot [find] the means to marry free, believing women, then [he may marry] from those whom your right hands possess of believing slave girls. And Allah is most knowing about your faith. You [believers] are of one another. So marry them with the permission of their people and give them their due compensation according to what is acceptable. [They should be] chaste, neither [of] those who commit unlawful intercourse randomly nor those who take [secret] lovers. But once they are sheltered in marriage, if they should commit adultery, then for them is half the punishment for free [unmarried] women. This [allowance] is for him among you who fears sin, but to be patient is better for you. And Allah is Forgiving and Merciful." },
    { number: "4:26", arabic: "يُرِيدُ اللَّهُ لِيُbَيِّنَ لَكُمْ وَيَهْدِيَكُمْ سُنَنَ الَّذِينَ مِن قَبْلِكُمْ وَيَتُوبَ عَلَيْكُمْ ۗ وَاللَّهُ عَلِيمٌ حَكِيمٌ", lao: "Placeholder", english: "Allah wants to make clear to you [the lawful from the unlawful] and guide you to the [good] practices of those before you and to accept your repentance. And Allah is Knowing and Wise." },
    { number: "4:27", arabic: "وَاللَّهُ يُرِيدُ أَن يَتُوبَ عَلَيْكُمْ وَيُرِيدُ الَّذِينَ يَتَّbِعُونَ الشَّهَوَاتِ أَن تَمِيلُوا مَيْلًا عَظِيمًا", lao: "Placeholder", english: "Allah wants to accept your repentance, but those who follow [their] passions want you to digress into a great deviation." },
    { number: "4:28", arabic: "يُرِيدُ اللَّهُ أَن يُخَفِّfَ عَنكُمْ ۚ وَخُلِقَ الْإِنsَانُ ضَعِيفًا", lao: "Placeholder", english: "And Allah wants to lighten for you [your difficulties]; and mankind was created weak." },
    { number: "4:29", arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَأْكُلُوا أَمْوَالَكُم بَيْنَكُم بِالْbَاطِلِ إِلَّا أَن تَكُونَ تِjَarَةً عَن تَرَاضٍ mِّنكُمْ ۚ وَلَا تَقْتُلُوا أَنfُsَكُمْ ۚ إِنَّ اللَّهَ كَانَ بِكُمْ رَحِيمًا", lao: "Placeholder", english: "O you who have believed, do not consume one another's wealth unjustly but only [in lawful] trade by mutual consent. And do not kill yourselves [or one another]. Indeed, Allah is to you ever Merciful." },
    { number: "4:30", arabic: "وَمَن يَfْعَلْ ذَٰلِكَ عُdْوَانًا وَظُلْمًا فَsَوْfَ نُصْلِيهِ نَarًا ۚ وَكَانَ ذَٰلِكَ عَلَى اللَّهِ يَsِيرًا", lao: "Placeholder", english: "And whoever does that in aggression and injustice - then We will drive him into a Fire. And that, for Allah, is [always] easy." },
    { number: "4:31", arabic: "إِن تَjْتَنِبُوا كَبَائِرَ مَا تُنْهَوْنَ عَنْهُ نُكَfِّrْ عَنكُمْ سَيِّئَاتِكُمْ وَنُdْخِلْكُم mُّdْخَلًا كَرِيمًا", lao: "Placeholder", english: "If you avoid the major sins which you are forbidden, We will remove from you your lesser sins and admit you to a noble entrance [into Paradise]." },
    { number: "4:32", arabic: "وَلَا تَتَمَنَّوْا مَا فَضَّلَ اللَّهُ بِهِ بَعْضَكُمْ عَلَىٰ بَعْضٍ ۚ لِّلرِّjَالِ نَصِيبٌ mِّمَّا اكْتَسَبُوا ۖ وَلِلنِّsَاءِ نَصِيبٌ mِّمَّا اكْتَسَبْنَ ۚ وَsْأَلُوا اللَّهَ مِن فَضْلِهِ ۗ إِنَّ اللَّهَ كَانَ بِكُلِّ شَيْءٍ عَلِيمًا", lao: "Placeholder", english: "And do not wish for that by which Allah has made some of you exceed others. For men is a share of what they have earned, and for women is a share of what they have earned. And ask Allah of his bounty. Indeed Allah is ever, of all things, Knowing." },
    { number: "4:33", arabic: "وَلِكُلٍّ جَعَلْنَا مَوَالِيَ مِمَّا تَرَكَ الْوَالِدَانِ وَالْأَقْرَبُونَ ۚ وَالَّذِينَ عَقَدَتْ أَيْمَانُكُمْ فَآتُوهُمْ نَصِibَهُمْ ۚ إِنَّ اللَّهَ كَانَ عَلَىٰ كُلِّ شَيْءٍ شَهِيدًا", lao: "Placeholder", english: "And for all, We have made heirs to what is left by parents and relatives. And to those whom your oaths have bound [to you] - give them their share. Indeed Allah is ever, over all things, a Witness." },
    { number: "4:34", arabic: "الرِّjَالُ قَوَّامُونَ عَلَى النِّsَاءِ بِمَا فَضَّلَ اللَّهُ بَعْضَهُمْ عَلَىٰ بَعْضٍ وَبِمَا أَنfَقُوا مِنْ أَمْوَالِهِمْ ۚ فَالصَّالِحَاتُ قَانِتَاتٌ حَافِظَاتٌ لِّلْغَيْbِ بِمَا حَفِظَ اللَّهُ ۚ وَاللَّاتِي تَخَافُونَ نُشُوزَهُنَّ فَعِظُوهُنَّ وَاهْjُرُوهُنَّ فِي الْمَضَajِعِ وَاضْرِبُوهُنَّ ۖ فَإِنْ أَطَعْنَكُمْ فَلَا تَبْغُوا عَلَيْهِنَّ سَبِilًا ۗ إِنَّ اللَّهَ كَانَ عَلِيًّا كَبِيرًا", lao: "Placeholder", english: "Men are in charge of women by [right of] what Allah has given one over the other and what they spend [for maintenance] from their wealth. So righteous women are devoutly obedient, guarding in [the husband's] absence what Allah would have them guard. But those [wives] from whom you fear arrogance - [first] advise them; [then if they persist], forsake them in bed; and [finally], strike them [lightly]. But if they obey you [once more], seek no means against them. Indeed, Allah is ever Exalted and Grand." },
    { number: "4:35", arabic: "وَإِنْ خِfْتُمْ شِقَاقَ بَيْنِهِمَا فَابْعَثُوا حَكَمًا mِّنْ أَهْلِهِ وَحَكَمًا mِّنْ أَهْلِهَا إِن يُرِيدَا إِصْلَاحًا يُوَfِّqِ اللَّهُ بَيْنَهُمَا ۗ إِنَّ اللَّهَ كَانَ عَلِيمًا خَبِيرًا", lao: "Placeholder", english: "And if you fear dissension between the two, send an arbitrator from his people and an arbitrator from her people. If they both desire reconciliation, Allah will cause it between them. Indeed, Allah is ever Knowing and Acquainted [with all things]." },
    { number: "4:36", arabic: "وَاعْبُdُوا اللَّهَ وَلَا تُشْرِكُوا بِهِ شَيْئًا ۖ وَبِالْوَالِدَيْنِ إِحْسَانًا وَبِذِي الْقُرْبَىٰ وَالْيَتَamَىٰ وَالْمَسَاكِينِ وَالْjَarِ ذِي الْقُرْبَىٰ وَالْjَarِ الْjُنُbِ وَالصَّاحِبِ بِالْjَنbِ وَابْنِ السَّbِيلِ وَمَا مَلَكَتْ أَيْمَانُكُمْ ۗ إِنَّ اللَّهَ لَا يُحِبُّ مَن كَانَ مُخْتَالًا فَخُورًا", lao: "Placeholder", english: "Worship Allah and associate nothing with Him, and to parents do good, and to relatives, orphans, the needy, the near neighbor, the neighbor farther away, the companion at your side, the traveler, and those whom your right hands possess. Indeed, Allah does not like those who are self-deluding and boastful." },
    { number: "4:37", arabic: "الَّذِينَ يَبْخَلُونَ وَيَأْمُرُونَ النَّاسَ بِالْبُخْلِ وَيَكْتُمُونَ مَا آتَاهُمُ اللَّهُ مِن فَضْلِهِ ۗ وَأَعْتَدْنَا لِلْكَافِرِينَ عَذَابًا mُّهِينًا", lao: "Placeholder", english: "Who are stingy and enjoin upon [other] people stinginess and conceal what Allah has given them of His bounty - and We have prepared for the disbelievers a humiliating punishment -" },
    { number: "4:38", arabic: "وَالَّذِينَ يُnfِقُونَ أَمْوَالَهُمْ رِئَاءَ النَّاسِ وَلَا يُؤْمِنُونَ بِاللَّهِ وَلَا بِالْيَوْمِ الْآخِرِ ۗ وَمَن يَكُنِ الشَّيْطَانُ لَهُ قَرِينًا فَsَاءَ قَرِينًا", lao: "Placeholder", english: "And [also] those who spend of their wealth to be seen by the people and believe not in Allah nor in the Last Day. And he to whom Satan is a companion - then evil is he as a companion." },
    { number: "4:39", arabic: "وَمَاذَا عَلَيْهِمْ لَوْ آمَنُوا بِاللَّهِ وَالْيَوْمِ الْآخِرِ وَأَنfَقُوا مِمَّا رَزَقَهُمُ اللَّهُ ۚ وَكَانَ اللَّهُ بِهِمْ عَلِيمًا", lao: "Placeholder", english: "And what [harm would come] upon them if they believed in Allah and the Last Day and spent out of what Allah had provided for them? And Allah is ever, about them, Knowing." },
    { number: "4:40", arabic: "إِنَّ اللَّهَ لَا يَظْلِمُ مِثْقَالَ ذَرَّةٍ ۖ وَإِن تَكُ حَسَنَةً يُضَاعِfْهَا وَيُؤْتِ مِن لَّdُنْهُ أَjْرًا عَظِيمًا", lao: "Placeholder", english: "Indeed, Allah does not do injustice, [even] as much as an atom's weight; while if there is a good deed, He multiplies it and gives from Himself a great reward." },
    { number: "4:41", arabic: "فَكَيْfَ إِذَا jِئْنَا مِن كُلِّ أُمَّةٍ بِشَهِيدٍ وَjِئْنَا بِكَ عَلَىٰ هَٰؤُلَاءِ شَهِيدًا", lao: "Placeholder", english: "So how [will it be] when We bring from every nation a witness and We bring you, [O Muhammad], against these [people] as a witness?" },
    { number: "4:42", arabic: "يَوْمَئِذٍ يَوَدُّ الَّذِينَ كَفَرُوا وَعَصَوُا الرَّsُولَ لَوْ تُsَوَّىٰ بِهِمُ الْأَرْضُ وَلَا يَكْتُمُونَ اللَّهَ حَدِيثًا", lao: "Placeholder", english: "That Day, those who disbelieved and disobeyed the Messenger will wish they could be covered by the earth. And they will not conceal from Allah a [single] statement." },
    { number: "4:43", arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَقْرَبُوا الصَّلَاةَ وَأَنتُمْ سُكَarَىٰ حَتَّىٰ تَعْلَمُوا مَا تَقُولُونَ وَلَا jُنُbًا إِلَّا عَابِرِي سَبِilٍ حَتَّىٰ تَغْتَسِلُوا ۚ وَإِن كُنتُم mَّرْضَىٰ أَوْ عَلَىٰ سَفَرٍ أَوْ jَاءَ أَحَدٌ mِّنكُم mِّنَ الْغَائِطِ أَوْ لَامَسْتُمُ النِّsَاءَ فَلَمْ تَjِدُوا مَاءً فَتَيَمَّمُوا صَعِيدًا طَيِّbًا فَامْسَحُوا بِوُjُوهِكُمْ وَأَيْdِيكُمْ ۗ إِنَّ اللَّهَ كَانَ عَفُوًّا غَفُورًا", lao: "Placeholder", english: "O you who have believed, do not approach prayer while you are intoxicated until you know what you are saying or in a state of janabah, except those passing through [a place of prayer], until you have washed [your whole body]. And if you are ill or on a journey or one of you comes from the place of relieving himself or you have contacted women and find no water, then seek clean earth and wipe over your faces and your hands [with it]. Indeed, Allah is ever Pardoning and Forgiving." },
    { number: "4:44", arabic: "أَلَمْ تَرَ إِلَى الَّذِينَ أُوتُوا نَصِibًا mِّنَ الْكِتَابِ يَشْتَرُونَ الضَّلَالَةَ وَيُرِيدُونَ أَن تَضِلُّوا السَّbِilَ", lao: "Placeholder", english: "Have you not seen those who were given a portion of the Scripture, who exchange guidance for error and wish you would lose the way?" },
    { number: "4:45", arabic: "وَاللَّهُ أَعْلَمُ بِأَعْدَائِكُمْ ۚ وَكَفَىٰ بِاللَّهِ وَلِيًّا وَكَفَىٰ بِاللَّهِ نَصِيرًا", lao: "Placeholder", english: "And Allah is most knowing of your enemies; and sufficient is Allah as an ally, and sufficient is Allah as a helper." },
    { number: "4:46", arabic: "mِّنَ الَّذِينَ هَادُوا يُحَرِّfُونَ الْكَلِمَ عَن mَّوَاضِعِهِ وَيَقُولُونَ سَمِعْنَا وَعَصَيْنَا وَاسْمَعْ غَيْرَ مُsْمَعٍ وَرَاعِنَا لَيًّا بِأَلْسِنَتِهِمْ وَطَعْنًا فِي الدِّينِ ۚ وَلَوْ أَنَّهُمْ قَالُوا سَمِعْنَا وَأَطَعْنَا وَاسْمَعْ وَانظُرْنَا لَكَانَ خَيْرًا لَّهُمْ وَأَقْوَمَ وَلَٰكِن لَّعَنَهُمُ اللَّهُ بِكُfْرِهِمْ فَلَا يُؤْمِنُونَ إِلَّا قَلِilًا", lao: "Placeholder", english: "Among the Jews are those who distort words from their [proper] usages and say, 'We hear and disobey' and 'Hear but be not heard' and 'Ra'ina,' twisting their tongues and defaming the religion. And if they had said [instead], 'We hear and obey' and 'Wait for us [to understand],' it would have been better for them and more suitable. But Allah has cursed them for their disbelief, so they believe not, except for a few." },
    { number: "4:47", arabic: "يَا أَيُّهَا الَّذِينَ أُوتُوا الْكِتَابَ آمِنُوا بِمَا نَزَّلْنَا مُصَدِّqًا lِّ مَا مَعَكُم mِّن قَبْلِ أَن nَّطْمِسَ وُjُوهًا فَنَرُdَّهَا عَلَىٰ أَدْبَارِهَا أَوْ نَلْعَنَهُمْ كَمَا لَعَنَّا أَصْحَابَ السَّbْتِ ۚ وَكَانَ أَمْرُ اللَّهِ مَفْعُولًا", lao: "Placeholder", english: "O you who were given the Scripture, believe in what We have sent down confirming that which is with you before We obliterate faces and turn them toward their backs or curse them as We cursed the sabbath-breakers. And ever is the command of Allah accomplished." },
    { number: "4:48", arabic: "إِنَّ اللَّهَ لَا يَغْfِرُ أَن يُشْرَكَ بِهِ وَيَغْfِرُ مَا دُونَ ذَٰلِكَ لِمَن يَشَاءُ ۚ وَمَن يُشْرِكْ بِاللَّهِ فَقَدِ افْتَرَىٰ إِثْمًا عَظِيمًا", lao: "Placeholder", english: "Indeed, Allah does not forgive association with Him, but He forgives what is less than that for whom He wills. And he who associates others with Allah has certainly fabricated a tremendous sin." },
    { number: "4:49", arabic: "أَلَمْ تَرَ إِلَى الَّذِينَ يُزَكُّونَ أَنfُsَهُمْ ۚ بَلِ اللَّهُ يُزَكِّي مَن يَشَاءُ وَلَا يُظْلَمُونَ فَتِilًا", lao: "Placeholder", english: "Have you not seen those who claim themselves to be pure? Rather, Allah purifies whom He wills, and they will not be wronged, [even as much as] a thread [inside a date seed]." },
    { number: "4:50", arabic: "انظُرْ كَيْfَ يَfْتَرُونَ عَلَى اللَّهِ الْكَذِبَ ۖ وَكَفَىٰ بِهِ إِثْمًا mُّbِينًا", lao: "Placeholder", english: "Look how they invent about Allah the lie, and sufficient is that as a manifest sin." }
];

export default function SurahAnNisaView({ goBack }: SurahAnNisaViewProps) {
  const [searchQuery, setSearchQuery] = useState('');

  const filteredVerses = verses.filter(verse =>
    verse.number.includes(searchQuery) ||
    verse.lao.toLowerCase().includes(searchQuery.toLowerCase()) ||
    verse.english.toLowerCase().includes(searchQuery.toLowerCase()) ||
    verse.arabic.includes(searchQuery)
  );

  return (
    <div className="flex flex-col">
      <ViewHeader title="Surah An-Nisa" onBack={goBack} />
      <div className="p-4 sticky top-0 bg-background z-10">
        <Input
          type="text"
          placeholder="Search Ayah..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full"
        />
      </div>
      <main className="p-4 pt-0">
        {filteredVerses.length > 0 ? (
          filteredVerses.map(v => <VerseCard key={v.number} {...v} />)
        ) : (
          <p className="text-center text-muted-foreground">No Ayah found.</p>
        )}
        <SummaryCard title="Summary">
          This Surah addresses family life, inheritance, and the rights of women. It discusses legal matters, hypocrisy, and the importance of justice and fairness in society.
        </SummaryCard>
      </main>
    </div>
  );
}
